# -*- coding: utf-8 -*-
"""다코스수면극복최종.ipynb의 사본

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12NuUo50hRxEuWP-r9VNKkUa5Ug6s65BV
"""

# Commented out IPython magic to ensure Python compatibility.
# %%writefile README.md
# # 26-1-team5 프로젝트
# 
# 이 프로젝트는 Google Colab 환경에서 개발되었습니다.
# 
# ## 실행 방법
# 1. 코랩에서 이 노트북을 엽니다.
# 2. 상단 메뉴에서 `런타임` -> `모두 실행`을 누릅니다.

"""**Sleeptune**
사용자의 생체 데이터 수치를 머신러닝으로 정밀하게 '조율(Tune)'하여 최적의 수면 상태를 찾아준다는 의미.

#최종
"""

=============================================================================
# 수면 코치 서비스 — 최종 통합판 v4.0
#
# [통합 기준]
#   - 코드1: Gemini Secret 연동 + RF 수식 기반 페르소나
#   - 코드2: 정밀 하이브리드 입력 시스템 (숫자 수면시간 등)
#   - 코드3: KNN vs Gemini 비교 + 자유텍스트 입력 + K-Fold 검증
#
# [주요 수정 사항]
#   1. 페르소나: RF feature importance × |percentile - 0.5| × 2 수식 기반
#   2. KNN 목표값에 수면시간(Sleep Duration) 추가 → Gemini 비교 가능
#   3. 학습: K-Fold (5-Fold) 교차검증 + 혼동행렬·F1 출력
#   4. 입력 검증 강화 (나이 범위, 성별, 직업 목록 맞춤, 수치 범위 등)
#   5. 질문 한국어 친화적으로 개선 (입면→잠드는 시간, 야간각성→자다가 깨는 횟수 등)
#   6. 취침/기상 시간 선택 방식으로 변경 (선택 사항)
#   7. 기타 미입력 시 "없음" 자동 처리
# ==============================================================================

# ── 패키지 설치 (Colab 최초 1회) ──
# !pip install -q shap google-genai kaggle
# !sudo apt-get install -y fonts-nanum > /dev/null 2>&1

import os, json, re, textwrap
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import matplotlib as mpl
import matplotlib.font_manager as fm
import seaborn as sns

from sklearn.model_selection import train_test_split, StratifiedKFold, cross_val_score
from sklearn.preprocessing   import StandardScaler, MinMaxScaler
from sklearn.ensemble        import RandomForestClassifier
from sklearn.neighbors       import NearestNeighbors
from sklearn.metrics         import (classification_report, confusion_matrix,
                                      f1_score, accuracy_score)
import shap

# ── 한글 폰트 ──
font_path = '/usr/share/fonts/truetype/nanum/NanumGothic.ttf'
if os.path.exists(font_path):
    fm.fontManager.addfont(font_path)
    mpl.rc('font', family='NanumGothic')
else:
    mpl.rc('font', family='sans-serif')
mpl.rcParams['axes.unicode_minus'] = False
sns.set_theme(style='whitegrid')
print("✅ 라이브러리 및 한글 폰트 로드 완료")


# ==============================================================
# SECTION 1 — Gemini API 초기화 (Colab Secret 우선, 직접 입력 후순위)
# ==============================================================
GEMINI_ENABLED = False
gemini_client  = None
MODEL_NAME     = "gemini-2.5-flash"

try:
    from google import genai

    _api_key = None

    # 방법 1: Colab Secret
    try:
        from google.colab import userdata
        _api_key = userdata.get("GEMINI_API_KEY")
    except Exception:
        pass

    # 방법 2: 직접 하드코딩 (없으면 None 유지)
    if not _api_key:
        _DIRECT_KEY = ""   # ← 필요시 본인 키 입력
        if _DIRECT_KEY:
            _api_key = _DIRECT_KEY

    if _api_key:
        gemini_client  = genai.Client(api_key=_api_key)
        _test = gemini_client.models.generate_content(
            model=MODEL_NAME, contents="안녕")
        GEMINI_ENABLED = True
        print(f"🤖 [Gemini 모드 활성화] 모델: {MODEL_NAME}")
    else:
        print("ℹ️  GOOGLE_API_KEY 없음 → [순수 알고리즘 모드]")
except Exception as e:
    print(f"ℹ️  Gemini 연동 실패({e}) → [순수 알고리즘 모드]")


# ==============================================================
# SECTION 2 — Kaggle 데이터 로드 & 전처리
# ==============================================================
import subprocess

# ── Kaggle 인증 ──
KAGGLE_USERNAME = ""   # ← 본인 ID
KAGGLE_KEY      = ""   # ← 본인 KEY
# 또는 Colab 파일 업로드 방식 사용 (아래 주석 해제)
# from google.colab import files
# uploaded = files.upload()   # kaggle.json 업로드

os.makedirs('/root/.kaggle', exist_ok=True)
if KAGGLE_USERNAME and KAGGLE_KEY:
    with open('/root/.kaggle/kaggle.json', 'w') as f:
        json.dump({"username": KAGGLE_USERNAME, "key": KAGGLE_KEY}, f)
    os.chmod('/root/.kaggle/kaggle.json', 0o600)

subprocess.run(['kaggle','datasets','download','-d',
                'uom190346a/sleep-health-and-lifestyle-dataset'], check=True)
subprocess.run(['unzip','-q','-o',
                'sleep-health-and-lifestyle-dataset.zip'], check=True)

df = pd.read_csv('Sleep_health_and_lifestyle_dataset.csv')
df.columns = df.columns.str.strip()
print("원본 shape:", df.shape)
print("컬럼 목록:", df.columns.tolist())

# ── 기본 전처리 ──
df['Sleep Disorder'] = df['Sleep Disorder'].fillna('Normal')
df[['Systolic_BP','Diastolic_BP']] = (
    df['Blood Pressure'].str.split('/', expand=True).astype(int))

df['Gender'] = df['Gender'].map({'Female': 0, 'Male': 1})
df['BMI Category'] = df['BMI Category'].map(
    {'Normal': 0, 'Normal Weight': 0, 'Overweight': 1, 'Obese': 2})

# ── 직업 컬럼 확인 (입력 선택지 생성용) ──
if 'Occupation' in df.columns:
    JOB_LIST = sorted(df['Occupation'].dropna().unique().tolist())
else:
    JOB_LIST = ['Software Engineer','Doctor','Sales Representative',
                'Teacher','Nurse','Engineer','Accountant','Scientist',
                'Lawyer','Salesperson','Manager']
print("데이터셋 직업 목록:", JOB_LIST)

# ── 심박수 추정 수식 ──
def estimate_heart_rate(sbp: float, dbp: float) -> int:
    return int(np.clip(0.25 * sbp + 0.35 * dbp + 25, 45, 120))

if 'Heart Rate' not in df.columns or df['Heart Rate'].isnull().any():
    df['Heart Rate'] = df.apply(
        lambda r: estimate_heart_rate(r['Systolic_BP'], r['Diastolic_BP']), axis=1)
    print("⚠️  Heart Rate: 혈압 기반 추정값 사용")
else:
    print("✅ Heart Rate: 원본 데이터 사용")

print("\nSleep Disorder 분포:")
print(df['Sleep Disorder'].value_counts())


# ==============================================================
# SECTION 3 — EDA 시각화
# ==============================================================
fig, axes = plt.subplots(2, 2, figsize=(12, 8))
fig.suptitle('Sleep Disorder — EDA', fontsize=14)
sns.countplot(data=df, x='Sleep Disorder', ax=axes[0,0])
axes[0,0].set_title('Sleep Disorder 분포')
sns.boxplot(data=df, x='Sleep Disorder', y='Quality of Sleep', ax=axes[0,1])
axes[0,1].set_title('수면 질 by 진단')
sns.boxplot(data=df, x='Sleep Disorder', y='Stress Level', ax=axes[1,0])
axes[1,0].set_title('스트레스 수준 by 진단')
sns.scatterplot(data=df, x='Stress Level', y='Quality of Sleep',
                hue='Sleep Disorder', ax=axes[1,1])
axes[1,1].set_title('스트레스 vs 수면 질')
plt.tight_layout()
plt.show()


# ==============================================================
# SECTION 4 — 모델 학습 + K-Fold 교차검증
# ==============================================================
FEATURE_COLS = [
    'Gender', 'Age',
    'Quality of Sleep', 'Stress Level',
    'BMI Category', 'Heart Rate', 'Daily Steps',
    'Systolic_BP', 'Diastolic_BP',
]
TARGET_COL = 'Sleep Disorder'

X = df[FEATURE_COLS]
y = df[TARGET_COL]

# ── Train/Test 분할 ──
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42, stratify=y)

scaler         = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled  = scaler.transform(X_test)

model = RandomForestClassifier(
    n_estimators=200, max_depth=6,
    class_weight='balanced', random_state=42)
model.fit(X_train_scaled, y_train)

y_pred = model.predict(X_test_scaled)

print("\n" + "━"*60)
print("📊 수면 장애 진단 모델 — Hold-out Test 성능")
print("━"*60)
print(classification_report(y_test, y_pred))
print(f"✨ Macro F1 (Test): {f1_score(y_test, y_pred, average='macro'):.4f}")

# ── 혼동행렬 ──
plt.figure(figsize=(6, 5))
sns.heatmap(confusion_matrix(y_test, y_pred, labels=model.classes_),
            annot=True, fmt='d',
            xticklabels=model.classes_, yticklabels=model.classes_)
plt.title('Confusion Matrix (Test Set)')
plt.xlabel('Predicted'); plt.ylabel('Actual')
plt.tight_layout(); plt.show()

# ── Feature Importance ──
importance_df = pd.DataFrame({
    'Feature'   : FEATURE_COLS,
    'Importance': model.feature_importances_
}).sort_values('Importance', ascending=False)
plt.figure(figsize=(8, 4))
sns.barplot(data=importance_df, x='Importance', y='Feature')
plt.title('Feature Importance')
plt.tight_layout(); plt.show()

# ── K-Fold 교차검증 (5-Fold) ──
print("\n" + "="*60)
print("🔁 5-Fold Stratified 교차검증")
print("="*60)

scaler_kfold  = StandardScaler()
X_all_scaled  = scaler_kfold.fit_transform(X)

kf            = StratifiedKFold(n_splits=5, shuffle=True, random_state=42)
model_kfold   = RandomForestClassifier(
    n_estimators=200, max_depth=6,
    class_weight='balanced', random_state=42)

fold_f1s, fold_accs = [], []
print(f"\n{'Fold':<8} {'Accuracy':>12} {'Macro F1':>12}")
print("─"*35)

for fold, (tr_idx, val_idx) in enumerate(kf.split(X_all_scaled, y), 1):
    X_tr, X_val = X_all_scaled[tr_idx], X_all_scaled[val_idx]
    y_tr, y_val = y.iloc[tr_idx],       y.iloc[val_idx]
    model_kfold.fit(X_tr, y_tr)
    y_val_pred = model_kfold.predict(X_val)
    acc = accuracy_score(y_val, y_val_pred)
    f1  = f1_score(y_val, y_val_pred, average='macro')
    fold_f1s.append(f1); fold_accs.append(acc)
    print(f"Fold {fold:<3}  {acc:>12.4f}  {f1:>12.4f}")

cv_acc_mean = np.mean(fold_accs); cv_acc_std = np.std(fold_accs)
cv_f1_mean  = np.mean(fold_f1s);  cv_f1_std  = np.std(fold_f1s)
print("─"*35)
print(f"{'평균':<8} {cv_acc_mean:>12.4f}  {cv_f1_mean:>12.4f}")
print(f"{'표준편차':<8} {cv_acc_std:>12.4f}  {cv_f1_std:>12.4f}")

# K-Fold 시각화
fig2, ax2 = plt.subplots(1, 2, figsize=(10, 4))
ax2[0].bar(range(1,6), fold_accs, color='steelblue')
ax2[0].axhline(cv_acc_mean, color='red', linestyle='--',
               label=f'평균: {cv_acc_mean:.4f}')
ax2[0].set_title('K-Fold Accuracy'); ax2[0].legend()
ax2[1].bar(range(1,6), fold_f1s, color='darkorange')
ax2[1].axhline(cv_f1_mean, color='red', linestyle='--',
               label=f'평균: {cv_f1_mean:.4f}')
ax2[1].set_title('K-Fold Macro F1'); ax2[1].legend()
plt.tight_layout(); plt.show()

if cv_f1_std < 0.05:
    print("✅ 안정적인 모델 (표준편차 < 0.05)")
else:
    print("⚠️  모델 불안정 — 데이터 불균형 또는 과적합 의심")


# ── SHAP ──
explainer   = shap.TreeExplainer(model)
shap_values = explainer.shap_values(X_test_scaled)
shap.summary_plot(shap_values, X_test_scaled, feature_names=FEATURE_COLS)


# ==============================================================
# SECTION 5 — KNN 세팅 (수면시간 포함)
# ==============================================================
knn_scaler = StandardScaler()
# KNN에는 Sleep Duration도 포함하여 수면시간 비교 가능하게
KNN_COLS   = FEATURE_COLS + (['Sleep Duration'] if 'Sleep Duration' in df.columns else [])
knn_scaled = knn_scaler.fit_transform(df[KNN_COLS])
knn_model  = NearestNeighbors(n_neighbors=8, metric='euclidean')
knn_model.fit(knn_scaled)

def get_knn_targets(user_raw: dict) -> dict:
    """
    유사 수면 우수군의 데이터 기반 목표값 산출.
    수면시간(Sleep Duration)도 포함하여 Gemini 비교 가능하도록 수정.
    """
    # KNN_COLS에 Sleep Duration이 있으면 채워서 넣기
    knn_vec = {col: user_raw.get(col, df[col].mean()) for col in KNN_COLS}
    user_scaled = knn_scaler.transform(pd.DataFrame([knn_vec]))
    _, indices  = knn_model.kneighbors(user_scaled)
    similar     = df.iloc[indices[0]].copy()
    good        = similar[similar['Quality of Sleep'] >= 7]
    ref         = good if len(good) >= 2 else similar

    result = {
        'target_daily_steps'   : int(ref['Daily Steps'].mean()),
        'target_stress_level'  : round(ref['Stress Level'].mean(), 1),
        'target_quality'       : round(ref['Quality of Sleep'].mean(), 1),
        'target_hr'            : round(ref['Heart Rate'].mean(), 1),
        'reference_size'       : len(ref),
    }
    if 'Sleep Duration' in ref.columns:
        result['target_sleep_duration'] = round(ref['Sleep Duration'].mean(), 1)
    else:
        result['target_sleep_duration'] = None

    # 행동 팁 (KNN 직접 분석 문구)
    dur_str = f"{result['target_sleep_duration']}시간" if result['target_sleep_duration'] else "7~8시간"
    result['knn_behavioral_tips'] = [
        f"유사 우수 수면군은 하루 평균 {result['target_daily_steps']:,}보를 걸어 신체적 피로(아데노신)를 축적합니다.",
        f"우수 사례 그룹의 평균 실제 수면 시간은 {dur_str}입니다.",
        f"해당 그룹의 평균 스트레스 지수는 {result['target_stress_level']}/10 수준으로 통제됩니다."
    ]
    return result


# ==============================================================
# SECTION 6 — RF 수식 기반 페르소나 매핑 (코드1 로직 유지)
# ==============================================================
def assign_persona_rf(disorder: str, user_raw: dict) -> dict:
    """
    수식: Global Importance × |Percentile - 0.5| × 2
    → 사용자 개인 맞춤 최악의 방해 피처 도출 후 페르소나 매핑
    """
    global_importance = dict(zip(FEATURE_COLS, model.feature_importances_))
    user_contributions = {}
    user_percentiles   = {}

    for col in FEATURE_COLS:
        if col == 'Gender':
            continue
        percentile = (df[col] < user_raw[col]).mean()
        user_percentiles[col]   = percentile
        importance              = global_importance[col]
        user_contributions[col] = importance * abs(percentile - 0.5) * 2

    top_feature = max(user_contributions, key=user_contributions.get)

    feature_kr = {
        'Age'             : '나이 변동',
        'Quality of Sleep': '수면 질 부족',
        'Stress Level'    : '과도한 스트레스',
        'BMI Category'    : '체중 및 BMI 상태',
        'Heart Rate'      : '안정시 심박수 변동',
        'Daily Steps'     : '신체 활동 부족',
        'Systolic_BP'     : '수축기 혈압 지표',
        'Diastolic_BP'    : '이완기 혈압 지표',
    }
    top_name = feature_kr.get(top_feature, top_feature)

    # 진단 × 최악 피처 → 페르소나 매핑 트리
    if disorder == 'Normal':
        if top_feature in ['Daily Steps', 'Quality of Sleep']:
            ptype     = "🏃 Recovery Booster (활동 회복형)"
            desc      = (f"임상적 수면 장애는 없으나, [{top_name}] 요인이 "
                         "일상 회복 효율을 방해하는 1순위 인자로 식별되었습니다.")
            risk_level = "low"
        else:
            ptype     = "🌙 Deep Rest (안정적 수면형)"
            desc      = "생체 지표 및 생활 패턴이 전반적으로 이상적인 균형을 이루고 있습니다."
            risk_level = "low"

    elif disorder == 'Insomnia':
        if top_feature == 'Stress Level':
            ptype     = "⚡ Stress Sleeper (스트레스 과부하형)"
            desc      = (f"불면의 핵심 트리거는 [{top_name}]입니다. "
                         "코르티솔 과다 분비가 입면을 지속적으로 저해합니다.")
            risk_level = "high"
        else:
            ptype     = "🔄 Irregular Rhythm (수면 리듬 불균형형)"
            desc      = (f"[{top_name}]의 불균형이 주원인입니다. "
                         "일주기 리듬 회복을 위해 취침 시각 고정이 중요합니다.")
            risk_level = "medium"

    else:  # Sleep Apnea
        if top_feature in ['BMI Category', 'Systolic_BP', 'Diastolic_BP']:
            ptype     = "🫁 Obstructive Apnea Risk (체중·혈압성 호흡 불안형)"
            desc      = (f"위험 인자는 [{top_name}]입니다. "
                         "기도 협착 가능성과 심혈관계 과부하 위험이 동반될 수 있습니다.")
            risk_level = "high"
        else:
            ptype     = "🫁 Apnea Risk (일반 호흡 불안형)"
            desc      = (f"[{top_name}] 요인이 수면 중 호흡 효율 저하를 유발합니다. "
                         "자세 교정 및 모니터링이 권장됩니다.")
            risk_level = "high"

    return {
        'type'              : ptype,
        'desc'              : desc,
        'risk_level'        : risk_level,
        'top_feature'       : top_name,
        'contribution_score': round(user_contributions[top_feature], 4),
    }


# ==============================================================
# SECTION 7 — 생활습관 조언 (규칙 기반)
# ==============================================================
def lifestyle_advice(user_raw: dict, knn_target: dict) -> list:
    advice = []
    if user_raw['Stress Level'] > knn_target['target_stress_level']:
        advice.append("스트레스 지수가 건강군보다 높습니다. 명상 및 취침 전 스마트폰 차단을 권장합니다.")
    if user_raw['Daily Steps'] < knn_target['target_daily_steps']:
        gap = knn_target['target_daily_steps'] - user_raw['Daily Steps']
        advice.append(f"걸음 수가 목표 대비 {gap:,}보 부족합니다. 하루 20분 가벼운 걷기부터 시작하세요.")
    if user_raw['Heart Rate'] >= 80:
        advice.append("안정시 심박수가 높습니다. 카페인 섭취를 오후 2시 이전으로 제한하세요.")
    if user_raw['BMI Category'] >= 2:
        advice.append("비만 범주에 해당합니다. 체중 감량이 수면 무호흡 위험을 낮추는 근본 해결책입니다.")
    if not advice:
        advice.append("현재 패턴은 유사 건강 수면군과 비교해 매우 양호합니다! 이 습관을 유지하세요.")
    return advice


# ==============================================================
# SECTION 8 — 입력 검증 유틸리티
# ==============================================================
def _input_int(prompt: str, lo: int, hi: int, err_msg: str = None) -> int:
    """정수 입력 + 범위 검증 반복"""
    while True:
        raw = input(prompt).strip()
        try:
            val = int(raw)
            if lo <= val <= hi:
                return val
            print(f"  ⚠️  {lo}~{hi} 사이 숫자를 입력하세요.")
        except ValueError:
            print(f"  ⚠️  숫자를 입력해주세요.")

def _input_float(prompt: str, lo: float, hi: float) -> float:
    """실수 입력 + 범위 검증"""
    while True:
        raw = input(prompt).strip()
        try:
            val = float(raw)
            if lo < val <= hi:
                return val
            print(f"  ⚠️  {lo}~{hi} 사이 값을 입력하세요.")
        except ValueError:
            print("  ⚠️  숫자(소수점 가능)를 입력해주세요.")

def _input_choice(prompt: str, options: dict) -> str:
    """번호 → 값 매핑 선택 입력"""
    while True:
        raw = input(prompt).strip()
        if raw in options:
            return options[raw]
        print(f"  ⚠️  {list(options.keys())} 중 하나를 입력하세요.")

def _input_time_optional(prompt: str) -> str:
    """HH:MM 또는 Enter(모름/해당없음)"""
    raw = input(prompt + " (모르면 Enter 생략): ").strip()
    if not raw:
        return "미입력"
    # 간단 형식 허용 (23:30, 7:00 등)
    if re.match(r'^\d{1,2}:\d{2}$', raw):
        return raw
    print("  ⚠️  HH:MM 형식 또는 Enter로 생략하세요. 다시 입력합니다.")
    return _input_time_optional(prompt)


# ==============================================================
# SECTION 9 — 정밀 환자 데이터 입력 시스템 (최신 질문 개선)
# ==============================================================
def input_patient_data() -> tuple:
    """
    Returns
    -------
    user_raw   : ML 모델용 피처 딕셔너리
    lifestyle  : Gemini 프롬프트용 생활 습관 딕셔너리
    actual_sleep_hours : 사용자 직접 입력 수면 시간(float)
    """
    print("\n" + "="*60)
    print("    🛌 수면 건강 분석 — 정밀 데이터 입력")
    print("="*60)
    print("※ 번호로 선택하거나 숫자를 입력하세요. 모르는 항목은 Enter로 건너뛰세요.\n")

    # ──────────────────────────────────────────────
    # [1] 기본 인적 · 신체 정보
    # ──────────────────────────────────────────────
    print("[ 1. 기본 정보 ]")

    # 나이: 10~80세 범위 검증
    print("  나이를 입력하세요 (10세 미만 또는 80세 초과는 재입력 요청)")
    age = _input_int("  나이 (10~80): ", 10, 80)

    # 성별: 1=남성, 2=여성만 허용
    gender_code = _input_int("  성별 (1=남성, 2=여성): ", 1, 2) - 1  # 1→0, 2→1 매핑 아님
    gender_code = 1 if gender_code == 0 else 0   # 1=남성→1, 2=여성→0
    gender_txt  = "남성" if gender_code == 1 else "여성"

    # 직업: 데이터셋 실제 직업 목록
    print(f"\n  직업을 선택하세요:")
    job_options = {}
    for i, j in enumerate(JOB_LIST, 1):
        print(f"    {i:>2}. {j}")
        job_options[str(i)] = j
    job_options[str(len(JOB_LIST)+1)] = "기타"
    print(f"    {len(JOB_LIST)+1:>2}. 기타")
    job = _input_choice(f"  번호 입력 (1~{len(JOB_LIST)+1}): ", job_options)

    # BMI
    bmi_cat = _input_int("  BMI 등급 (0=정상체중, 1=과체중, 2=비만): ", 0, 2)

    # 걸음 수
    daily_steps = _input_int("  하루 평균 걸음 수 (예: 7000): ", 0, 100000)

    # 혈압 → 심박수 자동 추정
    sbp = _input_int("  수축기(최고) 혈압 mmHg (예: 120): ", 60, 220)
    dbp = _input_int("  이완기(최저) 혈압 mmHg (예: 80): ", 40, 140)
    hr  = estimate_heart_rate(sbp, dbp)
    print(f"  💓 혈압 연동 자동 추정 심박수: {hr} bpm")

    # ──────────────────────────────────────────────
    # [2] 수면 패턴
    # ──────────────────────────────────────────────
    print("\n[ 2. 수면 패턴 ]")

    # 취침·기상 시간은 선택 사항 (HH:MM 또는 Enter)
    bedtime  = _input_time_optional("  평소 취침 시간 (예: 23:30)")
    waketime = _input_time_optional("  평소 기상 시간 (예: 07:00)")

    # 실제 수면 시간 (정확한 숫자 입력)
    actual_sleep_hours = _input_float(
        "  ★ 실제 수면 시간은 몇 시간인가요? (예: 6.5): ", 0, 24)

    # 잠드는 데 걸리는 시간 (입면 소요)
    print("  잠드는 데 보통 얼마나 걸리나요?")
    sleep_onset_map = {
        "1": "5분 이내 (매우 빨리)", "2": "6~15분 (보통)",
        "3": "16~30분 (조금 걸림)", "4": "30분 이상 (오래 걸림)"
    }
    for k, v in sleep_onset_map.items():
        print(f"    {k}. {v}")
    sleep_onset_key  = _input_choice("  번호 입력 (1~4): ", sleep_onset_map)
    sleep_onset_weights = {"5분 이내 (매우 빨리)": 4, "6~15분 (보통)": 3,
                            "16~30분 (조금 걸림)": 2, "30분 이상 (오래 걸림)": 1}
    sq1_w = sleep_onset_weights[sleep_onset_key]

    # 자다가 깨는 횟수 (야간 각성 - 쉬운 표현)
    print("  자다가 깨는 경우가 얼마나 되나요?")
    wakeup_map = {
        "1": "거의 안 깸", "2": "1주일에 1~2번 깸",
        "3": "1주일에 3~4번 깸", "4": "매일 여러 번 깸"
    }
    for k, v in wakeup_map.items():
        print(f"    {k}. {v}")
    wakeup_key    = _input_choice("  번호 입력 (1~4): ", wakeup_map)
    wakeup_weights = {"거의 안 깸": 4, "1주일에 1~2번 깸": 3,
                       "1주일에 3~4번 깸": 2, "매일 여러 번 깸": 1}
    sq2_w = wakeup_weights[wakeup_key]

    # 자고 일어났을 때 개운한 정도 (수면의 질 대체)
    print("  자고 일어났을 때 얼마나 개운한가요?")
    refresh_map = {
        "1": "매우 개운함 (활기참)", "2": "어느 정도 개운함",
        "3": "약간 피로한 편", "4": "매우 피곤하고 무거움"
    }
    for k, v in refresh_map.items():
        print(f"    {k}. {v}")
    refresh_key     = _input_choice("  번호 입력 (1~4): ", refresh_map)
    refresh_weights = {"매우 개운함 (활기참)": 4, "어느 정도 개운함": 3,
                        "약간 피로한 편": 2, "매우 피곤하고 무거움": 1}
    sq3_w = refresh_weights[refresh_key]

    # 낮 동안 졸림/피로
    print("  낮 동안 졸리거나 피곤한 정도는?")
    daytime_map = {
        "1": "거의 없음", "2": "가끔 피곤함",
        "3": "자주 졸리고 피곤함", "4": "항상 너무 졸리고 힘듦"
    }
    for k, v in daytime_map.items():
        print(f"    {k}. {v}")
    daytime_key     = _input_choice("  번호 입력 (1~4): ", daytime_map)
    daytime_weights = {"거의 없음": 4, "가끔 피곤함": 3,
                        "자주 졸리고 피곤함": 2, "항상 너무 졸리고 힘듦": 1}
    sq5_w = daytime_weights[daytime_key]

    # 수면 시간 → 가중치 환산
    if   actual_sleep_hours >= 7.0: sq4_w = 4
    elif actual_sleep_hours >= 6.0: sq4_w = 3
    elif actual_sleep_hours >= 5.0: sq4_w = 2
    else:                            sq4_w = 1

    # 수면 질 종합 점수 계산 (5개 항목 합산 → 1~10 정규화)
    total_sleep_w = sq1_w + sq2_w + sq3_w + sq4_w + sq5_w
    min_sleep_w, max_sleep_w = 5, 20
    sleep_quality = int(round(np.clip(
        1 + 9 * (total_sleep_w - min_sleep_w) / (max_sleep_w - min_sleep_w), 1, 10)))

    # ──────────────────────────────────────────────
    # [3] 생활 습관
    # ──────────────────────────────────────────────
    print("\n[ 3. 생활 습관 ]")

    # 카페인 (음수·소수·100 초과 방지)
    caffeine_cups = _input_int("  하루 카페인 섭취 잔 수 (0~30, 예: 2): ", 0, 30)

    # 마지막 카페인 시간 (모름 옵션 포함)
    caffeine_time = _input_time_optional("  마지막 카페인 섭취 시간 (예: 15:00)")

    # 알코올
    alcohol = _input_choice(
        "  알코올 섭취 빈도 (0=없음, 1=주1~2회, 2=주3~4회, 3=매일): ",
        {"0": "없음", "1": "주 1~2회", "2": "주 3~4회", "3": "매일"}
    )

    # 취침 전 스마트폰 사용
    phone_minutes_raw = input("  취침 전 스마트폰 사용 시간(분, 없으면 Enter): ").strip()
    phone_minutes = phone_minutes_raw if phone_minutes_raw else "없음"

    # 운동 빈도 (0=없음 포함)
    exercise = _input_choice(
        "  운동 빈도 (0=없음, 1=주1~2회, 2=주3~4회, 3=매일): ",
        {"0": "없음", "1": "주 1~2회", "2": "주 3~4회", "3": "매일"}
    )

    # ──────────────────────────────────────────────
    # [4] 스트레스 정밀 설문
    # ──────────────────────────────────────────────
    print("\n[ 4. 스트레스 정밀 설문 ]")
    stress_qs = [
        ("SS1", "해야 할 일이 너무 많다는 느낌은?",
         {"1": (1,"거의 없음"), "2": (3,"가끔"), "3": (6,"자주"), "4": (9,"항상")}),
        ("SS2", "몸이 긴장되거나 어깨·목이 뭉치는 느낌은?",
         {"1": (1,"없음"), "2": (3,"가끔"), "3": (6,"자주"), "4": (9,"항상")}),
        ("SS3", "일상을 내가 스스로 컨트롤하고 있다는 느낌은?",
         {"1": (1,"충분히 통제"), "2": (3,"대체로 통제"), "3": (6,"통제 어려움"), "4": (9,"전혀 안 됨")}),
        ("SS4", "두통·소화불량 등 스트레스성 신체 증상은?",
         {"1": (1,"없음"), "2": (3,"가끔"), "3": (6,"자주"), "4": (9,"항상")}),
        ("SS5", "퇴근·하교 후 심리적으로 회복되는 느낌은?",
         {"1": (1,"충분히 회복"), "2": (3,"어느 정도"), "3": (6,"잘 안 됨"), "4": (9,"전혀 안 됨")}),
    ]
    stress_total = 0
    for sid, sq, opts in stress_qs:
        print(f"\n  {sq}")
        for k, (w, label) in opts.items():
            print(f"    {k}. {label}")
        key = _input_choice("  번호 입력 (1~4): ", {k: k for k in opts})
        stress_total += opts[key][0]

    # 스트레스 점수 정규화 → 1~10
    min_ss, max_ss = 5, 45
    stress_level = int(round(np.clip(
        1 + 9 * (stress_total - min_ss) / (max_ss - min_ss), 1, 10)))

    # 스트레스 수준 글자 표현
    if   stress_level <= 2: stress_label = "매우 낮음 (심리적 안정)"
    elif stress_level <= 4: stress_label = "낮음 (일상적 안정 상태)"
    elif stress_level <= 6: stress_label = "보통 (관리 필요 수준)"
    elif stress_level <= 8: stress_label = "높음 (코르티솔 과다 분비 가능)"
    else:                    stress_label = "매우 높음 ⚠️ (번아웃·불면 위험)"
    print(f"\n  📊 스트레스 점수: {stress_level}/10 — {stress_label}")

    # ──────────────────────────────────────────────
    # [5] 증상 및 기타
    # ──────────────────────────────────────────────
    print("\n[ 5. 주요 증상 선택 (쉼표로 구분, 없으면 Enter) ]")
    symptom_map = {
        "1": "잠들기 어려움", "2": "자다가 자주 깸", "3": "너무 일찍 잠에서 깸",
        "4": "낮에 심하게 졸림", "5": "만성 피로", "6": "잠자리 들면 잡생각이 많음",
        "7": "아침에 일어나도 피로함", "8": "두통"
    }
    for k, v in symptom_map.items():
        print(f"    {k}. {v}")
    symptom_input = input("  선택 번호 (예: 1,4,6 / 없으면 Enter): ").strip()
    if symptom_input:
        selected = [s.strip() for s in symptom_input.split(",") if s.strip()]
        symptoms = ", ".join(symptom_map[n] for n in selected if n in symptom_map) or "특이 증상 없음"
    else:
        symptoms = "없음"

    extra = input("\n  기타 특이사항 (복용 약물·기저질환, 없으면 Enter): ").strip() or "없음"

    # ── ML 피처 딕셔너리 ──
    user_raw = {
        'Gender'          : gender_code,
        'Age'             : age,
        'Quality of Sleep': sleep_quality,
        'Stress Level'    : stress_level,
        'BMI Category'    : bmi_cat,
        'Heart Rate'      : hr,
        'Daily Steps'     : daily_steps,
        'Systolic_BP'     : sbp,
        'Diastolic_BP'    : dbp,
    }

    # ── Gemini 프롬프트용 생활 습관 딕셔너리 ──
    lifestyle = {
        'age'               : age,
        'gender_txt'        : gender_txt,
        'job'               : job,
        'bmi_cat'           : ['정상', '과체중', '비만'][bmi_cat],
        'sbp'               : sbp,
        'dbp'               : dbp,
        'hr'                : hr,
        'bedtime'           : bedtime,
        'waketime'          : waketime,
        'actual_sleep_hours': actual_sleep_hours,
        'steps'             : daily_steps,
        'caffeine_cups'     : caffeine_cups,
        'caffeine_time'     : caffeine_time,
        'alcohol'           : alcohol,
        'phone_minutes'     : phone_minutes,
        'exercise'          : exercise,
        'symptoms'          : symptoms,
        'extra'             : extra,
    }

    print(f"\n✅ 입력 완료 | 수면 질 점수: {sleep_quality}/10 | 스트레스: {stress_level}/10")
    return user_raw, lifestyle, actual_sleep_hours


# ==============================================================
# SECTION 10 — Gemini 분석 엔진
# ==============================================================
def _gemini_call(prompt: str):
    """Gemini API 호출 공통 래퍼. 실패 시 None 반환."""
    if not GEMINI_ENABLED or not gemini_client:
        return None
    try:
        resp = gemini_client.models.generate_content(
            model=MODEL_NAME, contents=prompt)
        return resp.text.strip()
    except Exception as e:
        print(f"  ⚠️  Gemini 호출 실패: {e}")
        return None

def gemini_medical_analysis(persona: dict, lifestyle: dict, knn: dict,
                              sleep_score: int, stress_score: int) -> dict:
    """KNN 수면시간 포함 → Gemini 비교 가능."""
    knn_dur_str = (f"{knn['target_sleep_duration']}시간"
                   if knn['target_sleep_duration'] else "7~8시간")
    # 기타 특이사항(약물·기저질환) 별도 강조 블록으로 분리
    extra_block = ""
    if lifestyle.get("extra") and lifestyle["extra"] != "없음":
        extra_block = f"""
        [⚠️ 복용 약물 및 기저질환 — 반드시 아래 내용을 의학 소견에 명시적으로 반영할 것]
        {lifestyle["extra"]}
        위 약물·질환이 수면에 미치는 영향을 소견에 구체적으로 언급하세요.
        """

    prompt = textwrap.dedent(f"""
        당신은 수면의학 전문 AI 코치입니다.
        아래 통합 데이터를 분석하여 반드시 순수 JSON만 응답하세요 (마크다운 코드블록 없이).

        [환자 기본 데이터]
        - 인적: {lifestyle['age']}세 / {lifestyle['gender_txt']} / 직업: {lifestyle['job']}
        - 생체: BMI {lifestyle['bmi_cat']} / 혈압 {lifestyle['sbp']}/{lifestyle['dbp']} mmHg / 심박수 {lifestyle['hr']} bpm
        - 수면: 취침 {lifestyle['bedtime']} ~ 기상 {lifestyle['waketime']} / 실제 {lifestyle['actual_sleep_hours']}시간
        - 활동: {lifestyle['steps']:,}보
        - 카페인: 하루 {lifestyle['caffeine_cups']}잔 / 마지막 {lifestyle['caffeine_time']}
        - 알코올: {lifestyle['alcohol']} / 취침 전 스마트폰: {lifestyle['phone_minutes']}분
        - 운동: {lifestyle['exercise']}
        - 자가 증상: {lifestyle['symptoms']}
        - 수면 질 점수: {sleep_score}/10 / 스트레스: {stress_score}/10
        - ML 페르소나: {persona['type']} (주요 방해 요인: {persona['top_feature']})
        {extra_block}
        [KNN 데이터 기반 유사 우수 수면군 목표]
        - 수면 시간 목표: {knn_dur_str}
        - 활동량 목표: {knn['target_daily_steps']:,}보
        - 스트레스 목표: {knn['target_stress_level']}/10

        [응답 JSON 형식 — medical_summary는 복용 약물·기저질환을 반드시 포함하여 충분히 상세하게]
        {{
          "medical_summary": "환자의 수면 패턴, 생활 습관, 복용 약물·기저질환을 종합한 의학 소견. 약물이 수면에 미치는 영향 포함. 4~6문장으로 상세하게.",
          "mechanism": "주요 수면 방해 인자가 뇌신경·호르몬계에 미치는 생화학적 메커니즘 2~3문장.",
          "recommended_sleep_hours": "권장 수면 시간 (예: 7.5시간)",
          "missions": [
            "오늘 밤 실천할 미션 1 (구체적 시간·방법·관련 호르몬 포함)",
            "오늘 밤 실천할 미션 2",
            "오늘 밤 실천할 미션 3"
          ],
          "warning_signs": "이 환자에게 특히 주의가 필요한 임상 신호 (복용 약물 부작용 포함)"
        }}
    """).strip()

    raw = _gemini_call(prompt)
    if raw:
        try:
            clean = re.sub(r'^```json\s*', '', raw)
            clean = re.sub(r'\s*```$', '', clean)
            return json.loads(clean)
        except Exception:
            pass

    # 폴백 (Gemini 비활성 또는 파싱 실패)
    return {
        "medical_summary"     : f"페르소나 [{persona['type']}] 패턴이 감지되었습니다.",
        "mechanism"           : "코르티솔 과다 분비 및 블루라이트로 인한 멜라토닌 억제.",
        "recommended_sleep_hours": "7.5시간",
        "missions"            : [
            "취침 1시간 전 스마트폰 블루라이트 차단",
            "마지막 카페인 섭취를 오후 2시 이전으로 제한",
            "방 온도를 19°C 내외로 설정하여 심부 체온 하강 유도"
        ],
        "warning_signs": "불면·주간 졸음이 3주 이상 지속되면 수면다원검사 권장."
    }

def gemini_checkin_feedback(mission_done: list, today_condition: int,
                              lifestyle: dict = None) -> str:
    done_str  = ", ".join(mission_done) if mission_done else "없음"
    # 기타 특이사항(복용 약물·기저질환 등)이 있으면 프롬프트에 반영
    extra_str = ""
    if lifestyle:
        extra = lifestyle.get("extra", "없음")
        meds  = lifestyle.get("symptoms", "없음")
        if extra and extra != "없음":
            extra_str = f"\n        [복용 약물·기저질환] {extra}"
    prompt = textwrap.dedent(f"""
        수면 코치입니다.
        완료 미션: [{done_str}]
        오늘 아침 컨디션: {today_condition}/10{extra_str}
        위 정보를 바탕으로 기저질환·복용 약물을 고려한
        격려와 메디컬 피드백을 한국어 2~3문장으로 작성하세요.
        마크다운 기호 없이 일반 텍스트로만.
    """).strip()
    result = _gemini_call(prompt)
    if result:
        return result
    done_count = len(mission_done)
    if done_count >= 3:
        return "모든 미션을 완료했습니다! 꾸준한 루틴이 생체 일주기 리듬 회복의 핵심입니다."
    elif done_count == 0:
        return "오늘은 쉽지 않았군요. 내일 미션 하나부터 다시 시작해봐요."
    return f"{done_count}개 완료! 남은 미션도 내일 꼭 도전해봐요."


# ==============================================================
# SECTION 11 — KNN vs Gemini 비교 출력
# ==============================================================
def print_knn_gemini_comparison(user_raw: dict, knn: dict, gd: dict,
                                  actual_sleep_hours: float):
    """
    수면시간 포함 KNN 데이터 분석 vs Gemini AI 권장값 나란히 출력.
    """
    knn_dur   = f"{knn['target_sleep_duration']}시간" if knn['target_sleep_duration'] else "N/A"
    gem_dur   = gd.get('recommended_sleep_hours', 'N/A')
    knn_steps = knn['target_daily_steps']
    gem_steps = f"{user_raw['Daily Steps'] + 2000:,}보 이상 (점진 권장)"
    knn_stress= knn['target_stress_level']
    gem_stress= max(1, user_raw['Stress Level'] - 2)

    print("\n" + "─"*65)
    print(f"  {'지표':<18} | {'내 현재':>12} | {'KNN 우수군':>12} | {'Gemini 권장':>14}")
    print("─"*65)
    print(f"  {'실제 수면 시간':<18} | {str(actual_sleep_hours)+'시간':>12} | {knn_dur:>12} | {gem_dur:>14}")
    print(f"  {'일일 걸음 수':<18} | {user_raw['Daily Steps']:>11,}보 | {knn_steps:>11,}보 | {gem_steps:>14}")
    print(f"  {'스트레스 지수':<18} | {user_raw['Stress Level']:>10}/10 | {knn_stress:>10}/10 | {gem_stress:>12}/10")
    print("─"*65)


# ==============================================================
# SECTION 12 — 종합 분석 파이프라인
# ==============================================================
def total_sleep_analysis(user_raw: dict, lifestyle: dict,
                           actual_sleep_hours: float) -> dict:
    """RF 예측 + RF 수식 페르소나 + KNN 목표(수면시간 포함) + Gemini 분석"""
    # RandomForest 예측
    user_df    = pd.DataFrame([user_raw])
    user_sc    = scaler.transform(user_df)
    disorder   = model.predict(user_sc)[0]
    pred_proba = model.predict_proba(user_sc)[0]
    proba_dict = {cls: f"{round(p*100,1)}%"
                  for cls, p in zip(model.classes_, pred_proba)}

    # RF 수식 기반 페르소나
    persona = assign_persona_rf(disorder, user_raw)

    # KNN 목표값 (수면시간 포함)
    knn_target = get_knn_targets(user_raw)

    # 규칙 기반 생활습관 조언
    advice = lifestyle_advice(user_raw, knn_target)

    # Gemini 정밀 분석
    gd = gemini_medical_analysis(
        persona, lifestyle, knn_target,
        user_raw['Quality of Sleep'], user_raw['Stress Level'])

    return {
        '예측 수면 상태'  : disorder,
        '수면 장애 확률'  : proba_dict,
        '페르소나'        : persona,
        'KNN 목표 수치'   : knn_target,
        '생활습관 조언'   : advice,
        'Gemini 분석'     : gd,
    }


# ==============================================================
# SECTION 13 — 전체 실행 함수
# ==============================================================
def run_full_analysis():
    print("\n" + "="*60)
    print("🛌 수면 건강 종합 분석 시작")
    print("="*60)

    # 1. 정밀 입력
    user_raw, lifestyle, actual_sleep_hours = input_patient_data()

    # 2. 분석
    print("\n🔍 ML 모델 분석 중...")
    result  = total_sleep_analysis(user_raw, lifestyle, actual_sleep_hours)
    persona = result['페르소나']
    knn     = result['KNN 목표 수치']
    gd      = result['Gemini 분석']

    # 3. 결과 출력
    print("\n" + "="*60)
    print("📋 수면 코치 종합 진단 보고서")
    print("="*60)

    print(f"\n🩺 ML 예측 진단: {result['예측 수면 상태']}")
    print(f"   확률 분포   : {result['수면 장애 확률']}")

    print(f"\n👤 수학적 매핑 페르소나: {persona['type']}")
    print(f"   위험도 등급: {persona['risk_level'].upper()}")
    print(f"   1순위 방해 요인: [{persona['top_feature']}] (기여도: {persona['contribution_score']})")
    print(f"   분석 설명  : {persona['desc']}")

    print("\n📊 [ KNN 데이터 직접 분석 — 유사 우수 수면군 행동 사례 ]")
    for tip in knn['knn_behavioral_tips']:
        print(f"  • {tip}")

    print("\n📊 [ 내 현재 vs KNN 우수군 vs Gemini AI 권장값 비교 ]")
    print_knn_gemini_comparison(user_raw, knn, gd, actual_sleep_hours)

    print(f"\n🔬 [ Gemini AI 의학 소견 ]")
    print(f"  {gd['medical_summary']}")
    print(f"\n⚙️  생리학적 메커니즘: {gd['mechanism']}")

    print("\n✅ [ 오늘 밤 실천 처방 미션 ]")
    for i, m in enumerate(gd.get('missions', result['생활습관 조언']), 1):
        print(f"  {i}. {m}")

    print(f"\n⚠️  전문의 진료 기준: {gd.get('warning_signs', '')}")

    return result, user_raw, lifestyle, actual_sleep_hours


# ==============================================================
# SECTION 14 — 아침 체크인
# ==============================================================
def run_checkin(result: dict, lifestyle: dict):
    """
    Parameters
    ----------
    result   : total_sleep_analysis() 반환값
    lifestyle: 생활습관 딕셔너리 (actual_sleep_hours 등 포함)
    """
    missions = result['Gemini 분석'].get('missions', result['생활습관 조언'])

    print("\n" + "="*60)
    print("☀️  익일 수면 체크인 추적")
    print("="*60)

    completed, done_list = [], []
    for i, m in enumerate(missions, 1):
        print(f"\n  미션 {i}: {m}")
        ans = input("  어제 실천했나요? (y=했음 / n=못함): ").strip().lower()
        done = ans == 'y'
        completed.append(done)
        if done:
            done_list.append(m)

    done_count = sum(completed)
    rate       = round(done_count / len(completed) * 100) if completed else 0

    print(f"\n  ✅ 달성: {done_count}/{len(completed)} ({rate}%)")
    if rate == 100: print("  🎉 완벽해요! 오늘도 유지해봐요.")
    elif rate >= 50: print("  👍 절반 이상 실천! 내일은 하나 더 도전해봐요.")
    else:             print("  💪 괜찮아요. 하나부터 꾸준히 시작해봐요.")

    not_done = [m for m, d in zip(missions, completed) if not d]
    if not_done:
        print("\n  🔁 내일 다시 도전할 항목:")
        for i, nd in enumerate(not_done, 1):
            print(f"     {i}. {nd}")

    today_score = _input_int("\n  오늘 아침 컨디션 점수 (1~10): ", 1, 10)

    print("\n🤖 피드백 생성 중...")
    fb = gemini_checkin_feedback(done_list, today_score, lifestyle)
    print("\n" + "─"*60)
    print("💬 수면 코치 피드백")
    print("─"*60)
    print(fb)

    return completed


# ==============================================================
# SECTION 15 — 빠른 검증 테스트 (Mock Data)
# ==============================================================
def quick_test():
    print("\n" + "="*60)
    print("🧪 빠른 검증 — 모의 데이터 테스트")
    print("="*60)

    sbp, dbp = 135, 88
    hr = estimate_heart_rate(sbp, dbp)

    user_raw = {
        'Gender': 0, 'Age': 32,
        'Quality of Sleep': 5, 'Stress Level': 7,
        'BMI Category': 1, 'Heart Rate': hr, 'Daily Steps': 4300,
        'Systolic_BP': sbp, 'Diastolic_BP': dbp,
    }
    lifestyle = {
        'age': 32, 'gender_txt': '여성', 'job': 'Nurse',
        'bmi_cat': '과체중', 'sbp': sbp, 'dbp': dbp, 'hr': hr,
        'bedtime': '23:30', 'waketime': '07:00',
        'actual_sleep_hours': 5.5,
        'steps': 4300, 'caffeine_cups': 3, 'caffeine_time': '17:00',
        'alcohol': '주 1~2회', 'phone_minutes': '60', 'exercise': '없음',
        'symptoms': '잠들기 어려움, 낮에 심하게 졸림', 'extra': '없음',
    }
    actual_sleep_hours = 5.5

    result  = total_sleep_analysis(user_raw, lifestyle, actual_sleep_hours)
    persona = result['페르소나']
    knn     = result['KNN 목표 수치']
    gd      = result['Gemini 분석']

    print(f"✅ 예측 진단    : {result['예측 수면 상태']} {result['수면 장애 확률']}")
    print(f"👤 페르소나     : {persona['type']} (위험도: {persona['risk_level'].upper()})")
    print(f"🎯 방해 요인 1위: {persona['top_feature']} (기여도: {persona['contribution_score']})")
    print_knn_gemini_comparison(user_raw, knn, gd, actual_sleep_hours)
    print("\n✅ [ 처방 미션 ]")
    for i, m in enumerate(gd.get('missions', []), 1):
        print(f"  {i}. {m}")
    return result


# ==============================================================
# SECTION 16 — 전체 테스트 세트 페르소나 분포 플로팅
# ==============================================================
test_df = df.iloc[X_test.index].copy()
test_df['ML_Prediction'] = y_pred
test_df['Persona'] = test_df.apply(
    lambda row: assign_persona_rf(
        row['ML_Prediction'],
        {col: row[col] for col in FEATURE_COLS}
    )['type'],
    axis=1
)
print("\n" + "="*60)
print("📊 RF 수식 기반 페르소나 분포 (Test Set)")
print("="*60)
print(test_df['Persona'].value_counts())

plt.figure(figsize=(9, 4))
test_df['Persona'].value_counts().plot(kind='barh', color='skyblue')
plt.title('RF 수식 기반 5대 페르소나 분포 (Test Set)')
plt.xlabel('인원 수')
plt.tight_layout()
plt.show()


# ==============================================================
# SECTION 17 — 메인 실행
# ==============================================================
# 빠른 검증 테스트
_ = quick_test()

# ── 실제 대화형 분석을 시작하려면 아래 주석 해제 ──
result, user_raw, lifestyle, actual_sleep_hours = run_full_analysis()
run_checkin(result, lifestyle)

# ==============================================================================
# 수면 코치 서비스 — 최종 통합판 v4.0
#
# [통합 기준]
#   - 코드1: Gemini Secret 연동 + RF 수식 기반 페르소나
#   - 코드2: 정밀 하이브리드 입력 시스템 (숫자 수면시간 등)
#   - 코드3: KNN vs Gemini 비교 + 자유텍스트 입력 + K-Fold 검증
#
# [주요 수정 사항]
#   1. 페르소나: RF feature importance × |percentile - 0.5| × 2 수식 기반
#   2. KNN 목표값에 수면시간(Sleep Duration) 추가 → Gemini 비교 가능
#   3. 학습: K-Fold (5-Fold) 교차검증 + 혼동행렬·F1 출력
#   4. 입력 검증 강화 (나이 범위, 성별, 직업 목록 맞춤, 수치 범위 등)
#   5. 질문 한국어 친화적으로 개선 (입면→잠드는 시간, 야간각성→자다가 깨는 횟수 등)
#   6. 취침/기상 시간 선택 방식으로 변경 (선택 사항)
#   7. 기타 미입력 시 "없음" 자동 처리
# ==============================================================================

# ── 패키지 설치 (Colab 최초 1회) ──
# !pip install -q shap google-genai kaggle
# !sudo apt-get install -y fonts-nanum > /dev/null 2>&1

import os, json, re, textwrap
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import matplotlib as mpl
import matplotlib.font_manager as fm
import seaborn as sns

from sklearn.model_selection import train_test_split, StratifiedKFold, cross_val_score
from sklearn.preprocessing   import StandardScaler, MinMaxScaler
from sklearn.ensemble        import RandomForestClassifier
from sklearn.neighbors       import NearestNeighbors
from sklearn.metrics         import (classification_report, confusion_matrix,
                                      f1_score, accuracy_score)
import shap

# ── 한글 폰트 ──
font_path = '/usr/share/fonts/truetype/nanum/NanumGothic.ttf'
if os.path.exists(font_path):
    fm.fontManager.addfont(font_path)
    mpl.rc('font', family='NanumGothic')
else:
    mpl.rc('font', family='sans-serif')
mpl.rcParams['axes.unicode_minus'] = False
sns.set_theme(style='whitegrid')
print("✅ 라이브러리 및 한글 폰트 로드 완료")


# ==============================================================
# SECTION 1 — Gemini API 초기화 (Colab Secret 우선, 직접 입력 후순위)
# ==============================================================
GEMINI_ENABLED = False
gemini_client  = None
MODEL_NAME     = "gemini-2.5-flash"

try:
    from google import genai

    _api_key = None

    # 방법 1: Colab Secret
    try:
        from google.colab import userdata
        _api_key = userdata.get("GEMINI_API_KEY")
    except Exception:
        pass

    # 방법 2: 직접 하드코딩 (없으면 None 유지)
    if not _api_key:
        _DIRECT_KEY = ""   # ← 필요시 본인 키 입력
        if _DIRECT_KEY:
            _api_key = _DIRECT_KEY

    if _api_key:
        gemini_client  = genai.Client(api_key=_api_key)
        _test = gemini_client.models.generate_content(
            model=MODEL_NAME, contents="안녕")
        GEMINI_ENABLED = True
        print(f"🤖 [Gemini 모드 활성화] 모델: {MODEL_NAME}")
    else:
        print("ℹ️  GOOGLE_API_KEY 없음 → [순수 알고리즘 모드]")
except Exception as e:
    print(f"ℹ️  Gemini 연동 실패({e}) → [순수 알고리즘 모드]")


# ==============================================================
# SECTION 2 — Kaggle 데이터 로드 & 전처리
# ==============================================================
import subprocess

# ── Kaggle 인증 ──
KAGGLE_USERNAME = ""   # ← 본인 ID
KAGGLE_KEY      = ""   # ← 본인 KEY
# 또는 Colab 파일 업로드 방식 사용 (아래 주석 해제)
# from google.colab import files
# uploaded = files.upload()   # kaggle.json 업로드

os.makedirs('/root/.kaggle', exist_ok=True)
if KAGGLE_USERNAME and KAGGLE_KEY:
    with open('/root/.kaggle/kaggle.json', 'w') as f:
        json.dump({"username": KAGGLE_USERNAME, "key": KAGGLE_KEY}, f)
    os.chmod('/root/.kaggle/kaggle.json', 0o600)

subprocess.run(['kaggle','datasets','download','-d',
                'uom190346a/sleep-health-and-lifestyle-dataset'], check=True)
subprocess.run(['unzip','-q','-o',
                'sleep-health-and-lifestyle-dataset.zip'], check=True)

df = pd.read_csv('Sleep_health_and_lifestyle_dataset.csv')
df.columns = df.columns.str.strip()
print("원본 shape:", df.shape)
print("컬럼 목록:", df.columns.tolist())

# ── 기본 전처리 ──
df['Sleep Disorder'] = df['Sleep Disorder'].fillna('Normal')
df[['Systolic_BP','Diastolic_BP']] = (
    df['Blood Pressure'].str.split('/', expand=True).astype(int))

df['Gender'] = df['Gender'].map({'Female': 0, 'Male': 1})
df['BMI Category'] = df['BMI Category'].map(
    {'Normal': 0, 'Normal Weight': 0, 'Overweight': 1, 'Obese': 2})

# ── 직업 컬럼 확인 (입력 선택지 생성용) ──
if 'Occupation' in df.columns:
    JOB_LIST = sorted(df['Occupation'].dropna().unique().tolist())
else:
    JOB_LIST = ['Software Engineer','Doctor','Sales Representative',
                'Teacher','Nurse','Engineer','Accountant','Scientist',
                'Lawyer','Salesperson','Manager']
print("데이터셋 직업 목록:", JOB_LIST)

# ── 심박수 추정 수식 ──
def estimate_heart_rate(sbp: float, dbp: float) -> int:
    return int(np.clip(0.25 * sbp + 0.35 * dbp + 25, 45, 120))

if 'Heart Rate' not in df.columns or df['Heart Rate'].isnull().any():
    df['Heart Rate'] = df.apply(
        lambda r: estimate_heart_rate(r['Systolic_BP'], r['Diastolic_BP']), axis=1)
    print("⚠️  Heart Rate: 혈압 기반 추정값 사용")
else:
    print("✅ Heart Rate: 원본 데이터 사용")

print("\nSleep Disorder 분포:")
print(df['Sleep Disorder'].value_counts())


# ==============================================================
# SECTION 3 — EDA 시각화
# ==============================================================
fig, axes = plt.subplots(2, 2, figsize=(12, 8))
fig.suptitle('Sleep Disorder — EDA', fontsize=14)
sns.countplot(data=df, x='Sleep Disorder', ax=axes[0,0])
axes[0,0].set_title('Sleep Disorder 분포')
sns.boxplot(data=df, x='Sleep Disorder', y='Quality of Sleep', ax=axes[0,1])
axes[0,1].set_title('수면 질 by 진단')
sns.boxplot(data=df, x='Sleep Disorder', y='Stress Level', ax=axes[1,0])
axes[1,0].set_title('스트레스 수준 by 진단')
sns.scatterplot(data=df, x='Stress Level', y='Quality of Sleep',
                hue='Sleep Disorder', ax=axes[1,1])
axes[1,1].set_title('스트레스 vs 수면 질')
plt.tight_layout()
plt.show()


# ==============================================================
# SECTION 4 — 모델 학습 + K-Fold 교차검증
# ==============================================================
FEATURE_COLS = [
    'Gender', 'Age',
    'Quality of Sleep', 'Stress Level',
    'BMI Category', 'Heart Rate', 'Daily Steps',
    'Systolic_BP', 'Diastolic_BP',
]
TARGET_COL = 'Sleep Disorder'

X = df[FEATURE_COLS]
y = df[TARGET_COL]

# ── Train/Test 분할 ──
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42, stratify=y)

scaler         = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled  = scaler.transform(X_test)

model = RandomForestClassifier(
    n_estimators=200, max_depth=6,
    class_weight='balanced', random_state=42)
model.fit(X_train_scaled, y_train)

y_pred = model.predict(X_test_scaled)

print("\n" + "━"*60)
print("📊 수면 장애 진단 모델 — Hold-out Test 성능")
print("━"*60)
print(classification_report(y_test, y_pred))
print(f"✨ Macro F1 (Test): {f1_score(y_test, y_pred, average='macro'):.4f}")

# ── 혼동행렬 ──
plt.figure(figsize=(6, 5))
sns.heatmap(confusion_matrix(y_test, y_pred, labels=model.classes_),
            annot=True, fmt='d',
            xticklabels=model.classes_, yticklabels=model.classes_)
plt.title('Confusion Matrix (Test Set)')
plt.xlabel('Predicted'); plt.ylabel('Actual')
plt.tight_layout(); plt.show()

# ── Feature Importance ──
importance_df = pd.DataFrame({
    'Feature'   : FEATURE_COLS,
    'Importance': model.feature_importances_
}).sort_values('Importance', ascending=False)
plt.figure(figsize=(8, 4))
sns.barplot(data=importance_df, x='Importance', y='Feature')
plt.title('Feature Importance')
plt.tight_layout(); plt.show()

# ── K-Fold 교차검증 (5-Fold) ──
print("\n" + "="*60)
print("🔁 5-Fold Stratified 교차검증")
print("="*60)

scaler_kfold  = StandardScaler()
X_all_scaled  = scaler_kfold.fit_transform(X)

kf            = StratifiedKFold(n_splits=5, shuffle=True, random_state=42)
model_kfold   = RandomForestClassifier(
    n_estimators=200, max_depth=6,
    class_weight='balanced', random_state=42)

fold_f1s, fold_accs = [], []
print(f"\n{'Fold':<8} {'Accuracy':>12} {'Macro F1':>12}")
print("─"*35)

for fold, (tr_idx, val_idx) in enumerate(kf.split(X_all_scaled, y), 1):
    X_tr, X_val = X_all_scaled[tr_idx], X_all_scaled[val_idx]
    y_tr, y_val = y.iloc[tr_idx],       y.iloc[val_idx]
    model_kfold.fit(X_tr, y_tr)
    y_val_pred = model_kfold.predict(X_val)
    acc = accuracy_score(y_val, y_val_pred)
    f1  = f1_score(y_val, y_val_pred, average='macro')
    fold_f1s.append(f1); fold_accs.append(acc)
    print(f"Fold {fold:<3}  {acc:>12.4f}  {f1:>12.4f}")

cv_acc_mean = np.mean(fold_accs); cv_acc_std = np.std(fold_accs)
cv_f1_mean  = np.mean(fold_f1s);  cv_f1_std  = np.std(fold_f1s)
print("─"*35)
print(f"{'평균':<8} {cv_acc_mean:>12.4f}  {cv_f1_mean:>12.4f}")
print(f"{'표준편차':<8} {cv_acc_std:>12.4f}  {cv_f1_std:>12.4f}")

# K-Fold 시각화
fig2, ax2 = plt.subplots(1, 2, figsize=(10, 4))
ax2[0].bar(range(1,6), fold_accs, color='steelblue')
ax2[0].axhline(cv_acc_mean, color='red', linestyle='--',
               label=f'평균: {cv_acc_mean:.4f}')
ax2[0].set_title('K-Fold Accuracy'); ax2[0].legend()
ax2[1].bar(range(1,6), fold_f1s, color='darkorange')
ax2[1].axhline(cv_f1_mean, color='red', linestyle='--',
               label=f'평균: {cv_f1_mean:.4f}')
ax2[1].set_title('K-Fold Macro F1'); ax2[1].legend()
plt.tight_layout(); plt.show()

if cv_f1_std < 0.05:
    print("✅ 안정적인 모델 (표준편차 < 0.05)")
else:
    print("⚠️  모델 불안정 — 데이터 불균형 또는 과적합 의심")


# ── SHAP ──
explainer   = shap.TreeExplainer(model)
shap_values = explainer.shap_values(X_test_scaled)
shap.summary_plot(shap_values, X_test_scaled, feature_names=FEATURE_COLS)


# ==============================================================
# SECTION 5 — KNN 세팅 (수면시간 포함)
# ==============================================================
knn_scaler = StandardScaler()
# KNN에는 Sleep Duration도 포함하여 수면시간 비교 가능하게
KNN_COLS   = FEATURE_COLS + (['Sleep Duration'] if 'Sleep Duration' in df.columns else [])
knn_scaled = knn_scaler.fit_transform(df[KNN_COLS])
knn_model  = NearestNeighbors(n_neighbors=8, metric='euclidean')
knn_model.fit(knn_scaled)

def get_knn_targets(user_raw: dict) -> dict:
    """
    유사 수면 우수군의 데이터 기반 목표값 산출.
    수면시간(Sleep Duration)도 포함하여 Gemini 비교 가능하도록 수정.
    """
    # KNN_COLS에 Sleep Duration이 있으면 채워서 넣기
    knn_vec = {col: user_raw.get(col, df[col].mean()) for col in KNN_COLS}
    user_scaled = knn_scaler.transform(pd.DataFrame([knn_vec]))
    _, indices  = knn_model.kneighbors(user_scaled)
    similar     = df.iloc[indices[0]].copy()
    good        = similar[similar['Quality of Sleep'] >= 7]
    ref         = good if len(good) >= 2 else similar

    result = {
        'target_daily_steps'   : int(ref['Daily Steps'].mean()),
        'target_stress_level'  : round(ref['Stress Level'].mean(), 1),
        'target_quality'       : round(ref['Quality of Sleep'].mean(), 1),
        'target_hr'            : round(ref['Heart Rate'].mean(), 1),
        'reference_size'       : len(ref),
    }
    if 'Sleep Duration' in ref.columns:
        result['target_sleep_duration'] = round(ref['Sleep Duration'].mean(), 1)
    else:
        result['target_sleep_duration'] = None

    # 행동 팁 (KNN 직접 분석 문구)
    dur_str = f"{result['target_sleep_duration']}시간" if result['target_sleep_duration'] else "7~8시간"
    result['knn_behavioral_tips'] = [
        f"유사 우수 수면군은 하루 평균 {result['target_daily_steps']:,}보를 걸어 신체적 피로(아데노신)를 축적합니다.",
        f"우수 사례 그룹의 평균 실제 수면 시간은 {dur_str}입니다.",
        f"해당 그룹의 평균 스트레스 지수는 {result['target_stress_level']}/10 수준으로 통제됩니다."
    ]
    return result


# ==============================================================
# SECTION 6 — RF 수식 기반 페르소나 매핑 (코드1 로직 유지)
# ==============================================================
def assign_persona_rf(disorder: str, user_raw: dict) -> dict:
    """
    수식: Global Importance × |Percentile - 0.5| × 2
    → 사용자 개인 맞춤 최악의 방해 피처 도출 후 페르소나 매핑
    """
    global_importance = dict(zip(FEATURE_COLS, model.feature_importances_))
    user_contributions = {}
    user_percentiles   = {}

    for col in FEATURE_COLS:
        if col == 'Gender':
            continue
        percentile = (df[col] < user_raw[col]).mean()
        user_percentiles[col]   = percentile
        importance              = global_importance[col]
        user_contributions[col] = importance * abs(percentile - 0.5) * 2

    top_feature = max(user_contributions, key=user_contributions.get)

    feature_kr = {
        'Age'             : '나이 변동',
        'Quality of Sleep': '수면 질 부족',
        'Stress Level'    : '과도한 스트레스',
        'BMI Category'    : '체중 및 BMI 상태',
        'Heart Rate'      : '안정시 심박수 변동',
        'Daily Steps'     : '신체 활동 부족',
        'Systolic_BP'     : '수축기 혈압 지표',
        'Diastolic_BP'    : '이완기 혈압 지표',
    }
    top_name = feature_kr.get(top_feature, top_feature)

    # 진단 × 최악 피처 → 페르소나 매핑 트리
    if disorder == 'Normal':
        if top_feature in ['Daily Steps', 'Quality of Sleep']:
            ptype     = "🏃 Recovery Booster (활동 회복형)"
            desc      = (f"임상적 수면 장애는 없으나, [{top_name}] 요인이 "
                         "일상 회복 효율을 방해하는 1순위 인자로 식별되었습니다.")
            risk_level = "low"
        else:
            ptype     = "🌙 Deep Rest (안정적 수면형)"
            desc      = "생체 지표 및 생활 패턴이 전반적으로 이상적인 균형을 이루고 있습니다."
            risk_level = "low"

    elif disorder == 'Insomnia':
        if top_feature == 'Stress Level':
            ptype     = "⚡ Stress Sleeper (스트레스 과부하형)"
            desc      = (f"불면의 핵심 트리거는 [{top_name}]입니다. "
                         "코르티솔 과다 분비가 입면을 지속적으로 저해합니다.")
            risk_level = "high"
        else:
            ptype     = "🔄 Irregular Rhythm (수면 리듬 불균형형)"
            desc      = (f"[{top_name}]의 불균형이 주원인입니다. "
                         "일주기 리듬 회복을 위해 취침 시각 고정이 중요합니다.")
            risk_level = "medium"

    else:  # Sleep Apnea
        if top_feature in ['BMI Category', 'Systolic_BP', 'Diastolic_BP']:
            ptype     = "🫁 Obstructive Apnea Risk (체중·혈압성 호흡 불안형)"
            desc      = (f"위험 인자는 [{top_name}]입니다. "
                         "기도 협착 가능성과 심혈관계 과부하 위험이 동반될 수 있습니다.")
            risk_level = "high"
        else:
            ptype     = "🫁 Apnea Risk (일반 호흡 불안형)"
            desc      = (f"[{top_name}] 요인이 수면 중 호흡 효율 저하를 유발합니다. "
                         "자세 교정 및 모니터링이 권장됩니다.")
            risk_level = "high"

    return {
        'type'              : ptype,
        'desc'              : desc,
        'risk_level'        : risk_level,
        'top_feature'       : top_name,
        'contribution_score': round(user_contributions[top_feature], 4),
    }


# ==============================================================
# SECTION 7 — 생활습관 조언 (규칙 기반)
# ==============================================================
def lifestyle_advice(user_raw: dict, knn_target: dict) -> list:
    advice = []
    if user_raw['Stress Level'] > knn_target['target_stress_level']:
        advice.append("스트레스 지수가 건강군보다 높습니다. 명상 및 취침 전 스마트폰 차단을 권장합니다.")
    if user_raw['Daily Steps'] < knn_target['target_daily_steps']:
        gap = knn_target['target_daily_steps'] - user_raw['Daily Steps']
        advice.append(f"걸음 수가 목표 대비 {gap:,}보 부족합니다. 하루 20분 가벼운 걷기부터 시작하세요.")
    if user_raw['Heart Rate'] >= 80:
        advice.append("안정시 심박수가 높습니다. 카페인 섭취를 오후 2시 이전으로 제한하세요.")
    if user_raw['BMI Category'] >= 2:
        advice.append("비만 범주에 해당합니다. 체중 감량이 수면 무호흡 위험을 낮추는 근본 해결책입니다.")
    if not advice:
        advice.append("현재 패턴은 유사 건강 수면군과 비교해 매우 양호합니다! 이 습관을 유지하세요.")
    return advice


# ==============================================================
# SECTION 8 — 입력 검증 유틸리티
# ==============================================================
def _input_int(prompt: str, lo: int, hi: int, err_msg: str = None) -> int:
    """정수 입력 + 범위 검증 반복"""
    while True:
        raw = input(prompt).strip()
        try:
            val = int(raw)
            if lo <= val <= hi:
                return val
            print(f"  ⚠️  {lo}~{hi} 사이 숫자를 입력하세요.")
        except ValueError:
            print(f"  ⚠️  숫자를 입력해주세요.")

def _input_float(prompt: str, lo: float, hi: float) -> float:
    """실수 입력 + 범위 검증"""
    while True:
        raw = input(prompt).strip()
        try:
            val = float(raw)
            if lo < val <= hi:
                return val
            print(f"  ⚠️  {lo}~{hi} 사이 값을 입력하세요.")
        except ValueError:
            print("  ⚠️  숫자(소수점 가능)를 입력해주세요.")

def _input_choice(prompt: str, options: dict) -> str:
    """번호 → 값 매핑 선택 입력"""
    while True:
        raw = input(prompt).strip()
        if raw in options:
            return options[raw]
        print(f"  ⚠️  {list(options.keys())} 중 하나를 입력하세요.")

def _input_time_optional(prompt: str) -> str:
    """HH:MM 또는 Enter(모름/해당없음)"""
    raw = input(prompt + " (모르면 Enter 생략): ").strip()
    if not raw:
        return "미입력"
    # 간단 형식 허용 (23:30, 7:00 등)
    if re.match(r'^\d{1,2}:\d{2}$', raw):
        return raw
    print("  ⚠️  HH:MM 형식 또는 Enter로 생략하세요. 다시 입력합니다.")
    return _input_time_optional(prompt)


# ==============================================================
# SECTION 9 — 정밀 환자 데이터 입력 시스템 (최신 질문 개선)
# ==============================================================
def input_patient_data() -> tuple:
    """
    Returns
    -------
    user_raw   : ML 모델용 피처 딕셔너리
    lifestyle  : Gemini 프롬프트용 생활 습관 딕셔너리
    actual_sleep_hours : 사용자 직접 입력 수면 시간(float)
    """
    print("\n" + "="*60)
    print("    🛌 수면 건강 분석 — 정밀 데이터 입력")
    print("="*60)
    print("※ 번호로 선택하거나 숫자를 입력하세요. 모르는 항목은 Enter로 건너뛰세요.\n")

    # ──────────────────────────────────────────────
    # [1] 기본 인적 · 신체 정보
    # ──────────────────────────────────────────────
    print("[ 1. 기본 정보 ]")

    # 나이: 10~80세 범위 검증
    print("  나이를 입력하세요 (10세 미만 또는 80세 초과는 재입력 요청)")
    age = _input_int("  나이 (10~80): ", 10, 80)

    # 성별: 1=남성, 2=여성만 허용
    gender_code = _input_int("  성별 (1=남성, 2=여성): ", 1, 2) - 1  # 1→0, 2→1 매핑 아님
    gender_code = 1 if gender_code == 0 else 0   # 1=남성→1, 2=여성→0
    gender_txt  = "남성" if gender_code == 1 else "여성"

    # 직업: 데이터셋 실제 직업 목록
    print(f"\n  직업을 선택하세요:")
    job_options = {}
    for i, j in enumerate(JOB_LIST, 1):
        print(f"    {i:>2}. {j}")
        job_options[str(i)] = j
    job_options[str(len(JOB_LIST)+1)] = "기타"
    print(f"    {len(JOB_LIST)+1:>2}. 기타")
    job = _input_choice(f"  번호 입력 (1~{len(JOB_LIST)+1}): ", job_options)

    # BMI
    bmi_cat = _input_int("  BMI 등급 (0=정상체중, 1=과체중, 2=비만): ", 0, 2)

    # 걸음 수
    daily_steps = _input_int("  하루 평균 걸음 수 (예: 7000): ", 0, 100000)

    # 혈압 → 심박수 자동 추정
    sbp = _input_int("  수축기(최고) 혈압 mmHg (예: 120): ", 60, 220)
    dbp = _input_int("  이완기(최저) 혈압 mmHg (예: 80): ", 40, 140)
    hr  = estimate_heart_rate(sbp, dbp)
    print(f"  💓 혈압 연동 자동 추정 심박수: {hr} bpm")

    # ──────────────────────────────────────────────
    # [2] 수면 패턴
    # ──────────────────────────────────────────────
    print("\n[ 2. 수면 패턴 ]")

    # 취침·기상 시간은 선택 사항 (HH:MM 또는 Enter)
    bedtime  = _input_time_optional("  평소 취침 시간 (예: 23:30)")
    waketime = _input_time_optional("  평소 기상 시간 (예: 07:00)")

    # 실제 수면 시간 (정확한 숫자 입력)
    actual_sleep_hours = _input_float(
        "  ★ 실제 수면 시간은 몇 시간인가요? (예: 6.5): ", 0, 24)

    # 잠드는 데 걸리는 시간 (입면 소요)
    print("  잠드는 데 보통 얼마나 걸리나요?")
    sleep_onset_map = {
        "1": "5분 이내 (매우 빨리)", "2": "6~15분 (보통)",
        "3": "16~30분 (조금 걸림)", "4": "30분 이상 (오래 걸림)"
    }
    for k, v in sleep_onset_map.items():
        print(f"    {k}. {v}")
    sleep_onset_key  = _input_choice("  번호 입력 (1~4): ", sleep_onset_map)
    sleep_onset_weights = {"5분 이내 (매우 빨리)": 4, "6~15분 (보통)": 3,
                            "16~30분 (조금 걸림)": 2, "30분 이상 (오래 걸림)": 1}
    sq1_w = sleep_onset_weights[sleep_onset_key]

    # 자다가 깨는 횟수 (야간 각성 - 쉬운 표현)
    print("  자다가 깨는 경우가 얼마나 되나요?")
    wakeup_map = {
        "1": "거의 안 깸", "2": "1주일에 1~2번 깸",
        "3": "1주일에 3~4번 깸", "4": "매일 여러 번 깸"
    }
    for k, v in wakeup_map.items():
        print(f"    {k}. {v}")
    wakeup_key    = _input_choice("  번호 입력 (1~4): ", wakeup_map)
    wakeup_weights = {"거의 안 깸": 4, "1주일에 1~2번 깸": 3,
                       "1주일에 3~4번 깸": 2, "매일 여러 번 깸": 1}
    sq2_w = wakeup_weights[wakeup_key]

    # 자고 일어났을 때 개운한 정도 (수면의 질 대체)
    print("  자고 일어났을 때 얼마나 개운한가요?")
    refresh_map = {
        "1": "매우 개운함 (활기참)", "2": "어느 정도 개운함",
        "3": "약간 피로한 편", "4": "매우 피곤하고 무거움"
    }
    for k, v in refresh_map.items():
        print(f"    {k}. {v}")
    refresh_key     = _input_choice("  번호 입력 (1~4): ", refresh_map)
    refresh_weights = {"매우 개운함 (활기참)": 4, "어느 정도 개운함": 3,
                        "약간 피로한 편": 2, "매우 피곤하고 무거움": 1}
    sq3_w = refresh_weights[refresh_key]

    # 낮 동안 졸림/피로
    print("  낮 동안 졸리거나 피곤한 정도는?")
    daytime_map = {
        "1": "거의 없음", "2": "가끔 피곤함",
        "3": "자주 졸리고 피곤함", "4": "항상 너무 졸리고 힘듦"
    }
    for k, v in daytime_map.items():
        print(f"    {k}. {v}")
    daytime_key     = _input_choice("  번호 입력 (1~4): ", daytime_map)
    daytime_weights = {"거의 없음": 4, "가끔 피곤함": 3,
                        "자주 졸리고 피곤함": 2, "항상 너무 졸리고 힘듦": 1}
    sq5_w = daytime_weights[daytime_key]

    # 수면 시간 → 가중치 환산
    if   actual_sleep_hours >= 7.0: sq4_w = 4
    elif actual_sleep_hours >= 6.0: sq4_w = 3
    elif actual_sleep_hours >= 5.0: sq4_w = 2
    else:                            sq4_w = 1

    # 수면 질 종합 점수 계산 (5개 항목 합산 → 1~10 정규화)
    total_sleep_w = sq1_w + sq2_w + sq3_w + sq4_w + sq5_w
    min_sleep_w, max_sleep_w = 5, 20
    sleep_quality = int(round(np.clip(
        1 + 9 * (total_sleep_w - min_sleep_w) / (max_sleep_w - min_sleep_w), 1, 10)))

    # ──────────────────────────────────────────────
    # [3] 생활 습관
    # ──────────────────────────────────────────────
    print("\n[ 3. 생활 습관 ]")

    # 카페인 (음수·소수·100 초과 방지)
    caffeine_cups = _input_int("  하루 카페인 섭취 잔 수 (0~30, 예: 2): ", 0, 30)

    # 마지막 카페인 시간 (모름 옵션 포함)
    caffeine_time = _input_time_optional("  마지막 카페인 섭취 시간 (예: 15:00)")

    # 알코올
    alcohol = _input_choice(
        "  알코올 섭취 빈도 (0=없음, 1=주1~2회, 2=주3~4회, 3=매일): ",
        {"0": "없음", "1": "주 1~2회", "2": "주 3~4회", "3": "매일"}
    )

    # 취침 전 스마트폰 사용
    phone_minutes_raw = input("  취침 전 스마트폰 사용 시간(분, 없으면 Enter): ").strip()
    phone_minutes = phone_minutes_raw if phone_minutes_raw else "없음"

    # 운동 빈도 (0=없음 포함)
    exercise = _input_choice(
        "  운동 빈도 (0=없음, 1=주1~2회, 2=주3~4회, 3=매일): ",
        {"0": "없음", "1": "주 1~2회", "2": "주 3~4회", "3": "매일"}
    )

    # ──────────────────────────────────────────────
    # [4] 스트레스 정밀 설문
    # ──────────────────────────────────────────────
    print("\n[ 4. 스트레스 정밀 설문 ]")
    stress_qs = [
        ("SS1", "해야 할 일이 너무 많다는 느낌은?",
         {"1": (1,"거의 없음"), "2": (3,"가끔"), "3": (6,"자주"), "4": (9,"항상")}),
        ("SS2", "몸이 긴장되거나 어깨·목이 뭉치는 느낌은?",
         {"1": (1,"없음"), "2": (3,"가끔"), "3": (6,"자주"), "4": (9,"항상")}),
        ("SS3", "일상을 내가 스스로 컨트롤하고 있다는 느낌은?",
         {"1": (1,"충분히 통제"), "2": (3,"대체로 통제"), "3": (6,"통제 어려움"), "4": (9,"전혀 안 됨")}),
        ("SS4", "두통·소화불량 등 스트레스성 신체 증상은?",
         {"1": (1,"없음"), "2": (3,"가끔"), "3": (6,"자주"), "4": (9,"항상")}),
        ("SS5", "퇴근·하교 후 심리적으로 회복되는 느낌은?",
         {"1": (1,"충분히 회복"), "2": (3,"어느 정도"), "3": (6,"잘 안 됨"), "4": (9,"전혀 안 됨")}),
    ]
    stress_total = 0
    for sid, sq, opts in stress_qs:
        print(f"\n  {sq}")
        for k, (w, label) in opts.items():
            print(f"    {k}. {label}")
        key = _input_choice("  번호 입력 (1~4): ", {k: k for k in opts})
        stress_total += opts[key][0]

    # 스트레스 점수 정규화 → 1~10
    min_ss, max_ss = 5, 45
    stress_level = int(round(np.clip(
        1 + 9 * (stress_total - min_ss) / (max_ss - min_ss), 1, 10)))

    # 스트레스 수준 글자 표현
    if   stress_level <= 2: stress_label = "매우 낮음 (심리적 안정)"
    elif stress_level <= 4: stress_label = "낮음 (일상적 안정 상태)"
    elif stress_level <= 6: stress_label = "보통 (관리 필요 수준)"
    elif stress_level <= 8: stress_label = "높음 (코르티솔 과다 분비 가능)"
    else:                    stress_label = "매우 높음 ⚠️ (번아웃·불면 위험)"
    print(f"\n  📊 스트레스 점수: {stress_level}/10 — {stress_label}")

    # ──────────────────────────────────────────────
    # [5] 증상 및 기타
    # ──────────────────────────────────────────────
    print("\n[ 5. 주요 증상 선택 (쉼표로 구분, 없으면 Enter) ]")
    symptom_map = {
        "1": "잠들기 어려움", "2": "자다가 자주 깸", "3": "너무 일찍 잠에서 깸",
        "4": "낮에 심하게 졸림", "5": "만성 피로", "6": "잠자리 들면 잡생각이 많음",
        "7": "아침에 일어나도 피로함", "8": "두통"
    }
    for k, v in symptom_map.items():
        print(f"    {k}. {v}")
    symptom_input = input("  선택 번호 (예: 1,4,6 / 없으면 Enter): ").strip()
    if symptom_input:
        selected = [s.strip() for s in symptom_input.split(",") if s.strip()]
        symptoms = ", ".join(symptom_map[n] for n in selected if n in symptom_map) or "특이 증상 없음"
    else:
        symptoms = "없음"

    extra = input("\n  기타 특이사항 (복용 약물·기저질환, 없으면 Enter): ").strip() or "없음"

    # ── ML 피처 딕셔너리 ──
    user_raw = {
        'Gender'          : gender_code,
        'Age'             : age,
        'Quality of Sleep': sleep_quality,
        'Stress Level'    : stress_level,
        'BMI Category'    : bmi_cat,
        'Heart Rate'      : hr,
        'Daily Steps'     : daily_steps,
        'Systolic_BP'     : sbp,
        'Diastolic_BP'    : dbp,
    }

    # ── Gemini 프롬프트용 생활 습관 딕셔너리 ──
    lifestyle = {
        'age'               : age,
        'gender_txt'        : gender_txt,
        'job'               : job,
        'bmi_cat'           : ['정상', '과체중', '비만'][bmi_cat],
        'sbp'               : sbp,
        'dbp'               : dbp,
        'hr'                : hr,
        'bedtime'           : bedtime,
        'waketime'          : waketime,
        'actual_sleep_hours': actual_sleep_hours,
        'steps'             : daily_steps,
        'caffeine_cups'     : caffeine_cups,
        'caffeine_time'     : caffeine_time,
        'alcohol'           : alcohol,
        'phone_minutes'     : phone_minutes,
        'exercise'          : exercise,
        'symptoms'          : symptoms,
        'extra'             : extra,
    }

    print(f"\n✅ 입력 완료 | 수면 질 점수: {sleep_quality}/10 | 스트레스: {stress_level}/10")
    return user_raw, lifestyle, actual_sleep_hours


# ==============================================================
# SECTION 10 — Gemini 분석 엔진
# ==============================================================
def _gemini_call(prompt: str):
    """Gemini API 호출 공통 래퍼. 실패 시 None 반환."""
    if not GEMINI_ENABLED or not gemini_client:
        return None
    try:
        resp = gemini_client.models.generate_content(
            model=MODEL_NAME, contents=prompt)
        return resp.text.strip()
    except Exception as e:
        print(f"  ⚠️  Gemini 호출 실패: {e}")
        return None

def gemini_medical_analysis(persona: dict, lifestyle: dict, knn: dict,
                              sleep_score: int, stress_score: int) -> dict:
    """KNN 수면시간 포함 → Gemini 비교 가능."""
    knn_dur_str = (f"{knn['target_sleep_duration']}시간"
                   if knn['target_sleep_duration'] else "7~8시간")
    # 기타 특이사항(약물·기저질환) 별도 강조 블록으로 분리
    extra_block = ""
    if lifestyle.get("extra") and lifestyle["extra"] != "없음":
        extra_block = f"""
        [⚠️ 복용 약물 및 기저질환 — 반드시 아래 내용을 의학 소견에 명시적으로 반영할 것]
        {lifestyle["extra"]}
        위 약물·질환이 수면에 미치는 영향을 소견에 구체적으로 언급하세요.
        """

    prompt = textwrap.dedent(f"""
        당신은 수면의학 전문 AI 코치입니다.
        아래 통합 데이터를 분석하여 반드시 순수 JSON만 응답하세요 (마크다운 코드블록 없이).

        [환자 기본 데이터]
        - 인적: {lifestyle['age']}세 / {lifestyle['gender_txt']} / 직업: {lifestyle['job']}
        - 생체: BMI {lifestyle['bmi_cat']} / 혈압 {lifestyle['sbp']}/{lifestyle['dbp']} mmHg / 심박수 {lifestyle['hr']} bpm
        - 수면: 취침 {lifestyle['bedtime']} ~ 기상 {lifestyle['waketime']} / 실제 {lifestyle['actual_sleep_hours']}시간
        - 활동: {lifestyle['steps']:,}보
        - 카페인: 하루 {lifestyle['caffeine_cups']}잔 / 마지막 {lifestyle['caffeine_time']}
        - 알코올: {lifestyle['alcohol']} / 취침 전 스마트폰: {lifestyle['phone_minutes']}분
        - 운동: {lifestyle['exercise']}
        - 자가 증상: {lifestyle['symptoms']}
        - 수면 질 점수: {sleep_score}/10 / 스트레스: {stress_score}/10
        - ML 페르소나: {persona['type']} (주요 방해 요인: {persona['top_feature']})
        {extra_block}
        [KNN 데이터 기반 유사 우수 수면군 목표]
        - 수면 시간 목표: {knn_dur_str}
        - 활동량 목표: {knn['target_daily_steps']:,}보
        - 스트레스 목표: {knn['target_stress_level']}/10

        [응답 JSON 형식 — medical_summary는 복용 약물·기저질환을 반드시 포함하여 충분히 상세하게]
        {{
          "medical_summary": "환자의 수면 패턴, 생활 습관, 복용 약물·기저질환을 종합한 의학 소견. 약물이 수면에 미치는 영향 포함. 4~6문장으로 상세하게.",
          "mechanism": "주요 수면 방해 인자가 뇌신경·호르몬계에 미치는 생화학적 메커니즘 2~3문장.",
          "recommended_sleep_hours": "권장 수면 시간 (예: 7.5시간)",
          "missions": [
            "오늘 밤 실천할 미션 1 (구체적 시간·방법·관련 호르몬 포함)",
            "오늘 밤 실천할 미션 2",
            "오늘 밤 실천할 미션 3"
          ],
          "warning_signs": "이 환자에게 특히 주의가 필요한 임상 신호 (복용 약물 부작용 포함)"
        }}
    """).strip()

    raw = _gemini_call(prompt)
    if raw:
        try:
            clean = re.sub(r'^```json\s*', '', raw)
            clean = re.sub(r'\s*```$', '', clean)
            return json.loads(clean)
        except Exception:
            pass

    # 폴백 (Gemini 비활성 또는 파싱 실패)
    return {
        "medical_summary"     : f"페르소나 [{persona['type']}] 패턴이 감지되었습니다.",
        "mechanism"           : "코르티솔 과다 분비 및 블루라이트로 인한 멜라토닌 억제.",
        "recommended_sleep_hours": "7.5시간",
        "missions"            : [
            "취침 1시간 전 스마트폰 블루라이트 차단",
            "마지막 카페인 섭취를 오후 2시 이전으로 제한",
            "방 온도를 19°C 내외로 설정하여 심부 체온 하강 유도"
        ],
        "warning_signs": "불면·주간 졸음이 3주 이상 지속되면 수면다원검사 권장."
    }

def gemini_checkin_feedback(mission_done: list, today_condition: int,
                              lifestyle: dict = None) -> str:
    done_str  = ", ".join(mission_done) if mission_done else "없음"
    # 기타 특이사항(복용 약물·기저질환 등)이 있으면 프롬프트에 반영
    extra_str = ""
    if lifestyle:
        extra = lifestyle.get("extra", "없음")
        meds  = lifestyle.get("symptoms", "없음")
        if extra and extra != "없음":
            extra_str = f"\n        [복용 약물·기저질환] {extra}"
    prompt = textwrap.dedent(f"""
        수면 코치입니다.
        완료 미션: [{done_str}]
        오늘 아침 컨디션: {today_condition}/10{extra_str}
        위 정보를 바탕으로 기저질환·복용 약물을 고려한
        격려와 메디컬 피드백을 한국어 2~3문장으로 작성하세요.
        마크다운 기호 없이 일반 텍스트로만.
    """).strip()
    result = _gemini_call(prompt)
    if result:
        return result
    done_count = len(mission_done)
    if done_count >= 3:
        return "모든 미션을 완료했습니다! 꾸준한 루틴이 생체 일주기 리듬 회복의 핵심입니다."
    elif done_count == 0:
        return "오늘은 쉽지 않았군요. 내일 미션 하나부터 다시 시작해봐요."
    return f"{done_count}개 완료! 남은 미션도 내일 꼭 도전해봐요."


# ==============================================================
# SECTION 11 — KNN vs Gemini 비교 출력
# ==============================================================
def print_knn_gemini_comparison(user_raw: dict, knn: dict, gd: dict,
                                  actual_sleep_hours: float):
    """
    수면시간 포함 KNN 데이터 분석 vs Gemini AI 권장값 나란히 출력.
    """
    knn_dur   = f"{knn['target_sleep_duration']}시간" if knn['target_sleep_duration'] else "N/A"
    gem_dur   = gd.get('recommended_sleep_hours', 'N/A')
    knn_steps = knn['target_daily_steps']
    gem_steps = f"{user_raw['Daily Steps'] + 2000:,}보 이상 (점진 권장)"
    knn_stress= knn['target_stress_level']
    gem_stress= max(1, user_raw['Stress Level'] - 2)

    print("\n" + "─"*65)
    print(f"  {'지표':<18} | {'내 현재':>12} | {'KNN 우수군':>12} | {'Gemini 권장':>14}")
    print("─"*65)
    print(f"  {'실제 수면 시간':<18} | {str(actual_sleep_hours)+'시간':>12} | {knn_dur:>12} | {gem_dur:>14}")
    print(f"  {'일일 걸음 수':<18} | {user_raw['Daily Steps']:>11,}보 | {knn_steps:>11,}보 | {gem_steps:>14}")
    print(f"  {'스트레스 지수':<18} | {user_raw['Stress Level']:>10}/10 | {knn_stress:>10}/10 | {gem_stress:>12}/10")
    print("─"*65)


# ==============================================================
# SECTION 12 — 종합 분석 파이프라인
# ==============================================================
def total_sleep_analysis(user_raw: dict, lifestyle: dict,
                           actual_sleep_hours: float) -> dict:
    """RF 예측 + RF 수식 페르소나 + KNN 목표(수면시간 포함) + Gemini 분석"""
    # RandomForest 예측
    user_df    = pd.DataFrame([user_raw])
    user_sc    = scaler.transform(user_df)
    disorder   = model.predict(user_sc)[0]
    pred_proba = model.predict_proba(user_sc)[0]
    proba_dict = {cls: f"{round(p*100,1)}%"
                  for cls, p in zip(model.classes_, pred_proba)}

    # RF 수식 기반 페르소나
    persona = assign_persona_rf(disorder, user_raw)

    # KNN 목표값 (수면시간 포함)
    knn_target = get_knn_targets(user_raw)

    # 규칙 기반 생활습관 조언
    advice = lifestyle_advice(user_raw, knn_target)

    # Gemini 정밀 분석
    gd = gemini_medical_analysis(
        persona, lifestyle, knn_target,
        user_raw['Quality of Sleep'], user_raw['Stress Level'])

    return {
        '예측 수면 상태'  : disorder,
        '수면 장애 확률'  : proba_dict,
        '페르소나'        : persona,
        'KNN 목표 수치'   : knn_target,
        '생활습관 조언'   : advice,
        'Gemini 분석'     : gd,
    }


# ==============================================================
# SECTION 13 — 전체 실행 함수
# ==============================================================
def run_full_analysis():
    print("\n" + "="*60)
    print("🛌 수면 건강 종합 분석 시작")
    print("="*60)

    # 1. 정밀 입력
    user_raw, lifestyle, actual_sleep_hours = input_patient_data()

    # 2. 분석
    print("\n🔍 ML 모델 분석 중...")
    result  = total_sleep_analysis(user_raw, lifestyle, actual_sleep_hours)
    persona = result['페르소나']
    knn     = result['KNN 목표 수치']
    gd      = result['Gemini 분석']

    # 3. 결과 출력
    print("\n" + "="*60)
    print("📋 수면 코치 종합 진단 보고서")
    print("="*60)

    print(f"\n🩺 ML 예측 진단: {result['예측 수면 상태']}")
    print(f"   확률 분포   : {result['수면 장애 확률']}")

    print(f"\n👤 수학적 매핑 페르소나: {persona['type']}")
    print(f"   위험도 등급: {persona['risk_level'].upper()}")
    print(f"   1순위 방해 요인: [{persona['top_feature']}] (기여도: {persona['contribution_score']})")
    print(f"   분석 설명  : {persona['desc']}")

    print("\n📊 [ KNN 데이터 직접 분석 — 유사 우수 수면군 행동 사례 ]")
    for tip in knn['knn_behavioral_tips']:
        print(f"  • {tip}")

    print("\n📊 [ 내 현재 vs KNN 우수군 vs Gemini AI 권장값 비교 ]")
    print_knn_gemini_comparison(user_raw, knn, gd, actual_sleep_hours)

    print(f"\n🔬 [ Gemini AI 의학 소견 ]")
    print(f"  {gd['medical_summary']}")
    print(f"\n⚙️  생리학적 메커니즘: {gd['mechanism']}")

    print("\n✅ [ 오늘 밤 실천 처방 미션 ]")
    for i, m in enumerate(gd.get('missions', result['생활습관 조언']), 1):
        print(f"  {i}. {m}")

    print(f"\n⚠️  전문의 진료 기준: {gd.get('warning_signs', '')}")

    return result, user_raw, lifestyle, actual_sleep_hours


# ==============================================================
# SECTION 14 — 아침 체크인
# ==============================================================
def run_checkin(result: dict, lifestyle: dict):
    """
    Parameters
    ----------
    result   : total_sleep_analysis() 반환값
    lifestyle: 생활습관 딕셔너리 (actual_sleep_hours 등 포함)
    """
    missions = result['Gemini 분석'].get('missions', result['생활습관 조언'])

    print("\n" + "="*60)
    print("☀️  익일 수면 체크인 추적")
    print("="*60)

    completed, done_list = [], []
    for i, m in enumerate(missions, 1):
        print(f"\n  미션 {i}: {m}")
        ans = input("  어제 실천했나요? (y=했음 / n=못함): ").strip().lower()
        done = ans == 'y'
        completed.append(done)
        if done:
            done_list.append(m)

    done_count = sum(completed)
    rate       = round(done_count / len(completed) * 100) if completed else 0

    print(f"\n  ✅ 달성: {done_count}/{len(completed)} ({rate}%)")
    if rate == 100: print("  🎉 완벽해요! 오늘도 유지해봐요.")
    elif rate >= 50: print("  👍 절반 이상 실천! 내일은 하나 더 도전해봐요.")
    else:             print("  💪 괜찮아요. 하나부터 꾸준히 시작해봐요.")

    not_done = [m for m, d in zip(missions, completed) if not d]
    if not_done:
        print("\n  🔁 내일 다시 도전할 항목:")
        for i, nd in enumerate(not_done, 1):
            print(f"     {i}. {nd}")

    today_score = _input_int("\n  오늘 아침 컨디션 점수 (1~10): ", 1, 10)

    print("\n🤖 피드백 생성 중...")
    fb = gemini_checkin_feedback(done_list, today_score, lifestyle)
    print("\n" + "─"*60)
    print("💬 수면 코치 피드백")
    print("─"*60)
    print(fb)

    return completed


# ==============================================================
# SECTION 15 — 빠른 검증 테스트 (Mock Data)
# ==============================================================
def quick_test():
    print("\n" + "="*60)
    print("🧪 빠른 검증 — 모의 데이터 테스트")
    print("="*60)

    sbp, dbp = 135, 88
    hr = estimate_heart_rate(sbp, dbp)

    user_raw = {
        'Gender': 0, 'Age': 32,
        'Quality of Sleep': 5, 'Stress Level': 7,
        'BMI Category': 1, 'Heart Rate': hr, 'Daily Steps': 4300,
        'Systolic_BP': sbp, 'Diastolic_BP': dbp,
    }
    lifestyle = {
        'age': 32, 'gender_txt': '여성', 'job': 'Nurse',
        'bmi_cat': '과체중', 'sbp': sbp, 'dbp': dbp, 'hr': hr,
        'bedtime': '23:30', 'waketime': '07:00',
        'actual_sleep_hours': 5.5,
        'steps': 4300, 'caffeine_cups': 3, 'caffeine_time': '17:00',
        'alcohol': '주 1~2회', 'phone_minutes': '60', 'exercise': '없음',
        'symptoms': '잠들기 어려움, 낮에 심하게 졸림', 'extra': '없음',
    }
    actual_sleep_hours = 5.5

    result  = total_sleep_analysis(user_raw, lifestyle, actual_sleep_hours)
    persona = result['페르소나']
    knn     = result['KNN 목표 수치']
    gd      = result['Gemini 분석']

    print(f"✅ 예측 진단    : {result['예측 수면 상태']} {result['수면 장애 확률']}")
    print(f"👤 페르소나     : {persona['type']} (위험도: {persona['risk_level'].upper()})")
    print(f"🎯 방해 요인 1위: {persona['top_feature']} (기여도: {persona['contribution_score']})")
    print_knn_gemini_comparison(user_raw, knn, gd, actual_sleep_hours)
    print("\n✅ [ 처방 미션 ]")
    for i, m in enumerate(gd.get('missions', []), 1):
        print(f"  {i}. {m}")
    return result


# ==============================================================
# SECTION 16 — 전체 테스트 세트 페르소나 분포 플로팅
# ==============================================================
test_df = df.iloc[X_test.index].copy()
test_df['ML_Prediction'] = y_pred
test_df['Persona'] = test_df.apply(
    lambda row: assign_persona_rf(
        row['ML_Prediction'],
        {col: row[col] for col in FEATURE_COLS}
    )['type'],
    axis=1
)
print("\n" + "="*60)
print("📊 RF 수식 기반 페르소나 분포 (Test Set)")
print("="*60)
print(test_df['Persona'].value_counts())

plt.figure(figsize=(9, 4))
test_df['Persona'].value_counts().plot(kind='barh', color='skyblue')
plt.title('RF 수식 기반 5대 페르소나 분포 (Test Set)')
plt.xlabel('인원 수')
plt.tight_layout()
plt.show()


# ==============================================================
# SECTION 17 — 메인 실행
# ==============================================================
# 빠른 검증 테스트
_ = quick_test()

# ── 실제 대화형 분석을 시작하려면 아래 주석 해제 ──
result, user_raw, lifestyle, actual_sleep_hours = run_full_analysis()
run_checkin(result, lifestyle)

"""#전체 분포"""

# ==============================================================================
# [오류 수정판] 전체 데이터셋 대상 6대 페르소나 매핑 및 분포 시각화
# ==============================================================================

# 1. 코랩에 내장되지 않은 최소한의 폰트 설정만 진행 (pip 빌드 에러 원천 차단)
!sudo apt-get install -y fonts-nanum > /dev/null 2>&1

import os
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import matplotlib as mpl
import matplotlib.font_manager as fm
import seaborn as sns

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.ensemble import RandomForestClassifier

# 코랩 한글 깨짐 방지 폰트 세팅
font_path = '/usr/share/fonts/truetype/nanum/NanumGothic.ttf'
if os.path.exists(font_path):
    fm.fontManager.addfont(font_path)
    mpl.rc('font', family='NanumGothic')
else:
    mpl.rc('font', family='sans-serif')
mpl.rcParams['axes.unicode_minus'] = False
sns.set_theme(style='whitegrid', font='NanumGothic')

print("✅ 라이브러리 로드 및 한글 환경 설정 완료")


# 2. 데이터 세팅 (Kaggle 파일이 없을 경우를 대비한 가상 데이터 디펜스)
csv_filename = 'Sleep_health_and_lifestyle_dataset.csv'

if not os.path.exists(csv_filename):
    print("ℹ️ 원본 CSV 파일이 없어 분석용 가상 Sleep 데이터셋(374명 분)을 자동 생성합니다...")
    np.random.seed(42)
    mock_size = 374
    mock_df = pd.DataFrame({
        'Gender': np.random.choice(['Male', 'Female'], mock_size),
        'Age': np.random.randint(25, 60, mock_size),
        'Quality of Sleep': np.random.randint(4, 10, mock_size),
        'Stress Level': np.random.randint(3, 10, mock_size),
        'BMI Category': np.random.choice(['Normal', 'Overweight', 'Obese'], mock_size),
        'Heart Rate': np.random.randint(60, 90, mock_size),
        'Daily Steps': np.random.randint(3000, 11000, mock_size),
        'Blood Pressure': np.random.choice(['120/80', '130/85', '140/90', '115/75'], mock_size),
        'Sleep Disorder': np.random.choice([np.nan, 'Insomnia', 'Sleep Apnea'], mock_size, p=[0.6, 0.2, 0.2])
    })
    mock_df.to_csv(csv_filename, index=False)

# 데이터 로드 및 전처리 파이프라인
df_all = pd.read_csv(csv_filename)
df_all.columns = df_all.columns.str.strip()
df_all['Sleep Disorder'] = df_all['Sleep Disorder'].fillna('Normal')
df_all[['Systolic_BP', 'Diastolic_BP']] = df_all['Blood Pressure'].str.split('/', expand=True).astype(int)
df_all['Gender'] = df_all['Gender'].map({'Female': 0, 'Male': 1}).fillna(0).astype(int)
bmi_map = {'Normal': 0, 'Normal Weight': 0, 'Overweight': 1, 'Obese': 2}
df_all['BMI Category'] = df_all['BMI Category'].map(bmi_map).fillna(0).astype(int)


# 3. 모델 정의 및 전체 학습
FEATURE_COLS = ['Gender', 'Age', 'Quality of Sleep', 'Stress Level', 'BMI Category', 'Heart Rate', 'Daily Steps', 'Systolic_BP', 'Diastolic_BP']
TARGET_COL = 'Sleep Disorder'

X_all = df_all[FEATURE_COLS]
y_all = df_all[TARGET_COL]

scaler_all = StandardScaler()
X_all_scaled = scaler_all.fit_transform(X_all)

model_all = RandomForestClassifier(n_estimators=100, max_depth=6, class_weight='balanced', random_state=42)
model_all.fit(X_all_scaled, y_all)


# 4. 6대 페르소나 핵심 알고리즘 정의
def assign_persona_6def(disorder: str, user_raw: dict, df_train: pd.DataFrame, model_rf: RandomForestClassifier, feature_cols: list) -> str:
    global_importance = dict(zip(feature_cols, model_rf.feature_importances_))
    user_contributions = {}

    for col in feature_cols:
        if col == 'Gender': continue
        percentile = (df_train[col] < user_raw[col]).mean()
        user_contributions[col] = global_importance[col] * abs(percentile - 0.5) * 2

    top_feature = max(user_contributions, key=user_contributions.get)

    # 이미지 파이프라인 기획 구조 기반 6단 분기 매핑
    if disorder == 'Normal':
        if top_feature in ['Daily Steps', 'Quality of Sleep']:
            return "1. 🏃 Recovery Booster (활동 회복형)"
        else:
            return "2. 🌙 Deep Rest (안정적 수면형)"
    elif disorder == 'Insomnia':
        if top_feature == 'Stress Level':
            return "3. ⚡ Stress Sleeper (스트레스 과부하형)"
        else:
            return "4. 🔄 Irregular Rhythm (수면 리듬 불균형형)"
    else: # Sleep Apnea
        if top_feature in ['BMI Category', 'Systolic_BP', 'Diastolic_BP']:
            return "5. 🫁 Obstructive Apnea (체중·혈압성 호흡불안형)"
        else:
            return "6. 🌬️ Functional Apnea (기능성 호흡불안형)"


# 5. 전역 데이터셋에 페르소나 매핑 연산 적용
print("🎯 전체 데이터 행에 중요도X분위수 수식 반영하여 페르소나 추출 중...")
df_all['ML_Pred'] = model_all.predict(X_all_scaled)
df_all['Persona_Result'] = df_all.apply(
    lambda row: assign_persona_6def(
        disorder=row['ML_Pred'],
        user_raw={col: row[col] for col in FEATURE_COLS},
        df_train=df_all,
        model_rf=model_all,
        feature_cols=FEATURE_COLS
    ),
    axis=1
)


# 6. 통계 리포트 텍스트 출력
counts = df_all['Persona_Result'].value_counts().sort_index()
pcts = df_all['Persona_Result'].value_counts(normalize=True).sort_index() * 100

print("\n" + "=" * 65)
print("📊 [최종 결과] 전체 데이터셋 기준 6대 페르소나 분포 통계")
print("=" * 65)
for name in counts.index:
    print(f"• {name:<45} : {counts[name]:3d}명 ({pcts[name]:.1f}%)")
print("-" * 65)
print(f"📈 총 분석 대상 데이터 수: {len(df_all)}명")
print("=" * 65)


# 7. 분포 시각화 차트 플로팅
fig, axes = plt.subplots(1, 2, figsize=(16, 6))
fig.suptitle('전체 수면 데이터셋 기반 6대 페르소나 최종 분포 현황', fontsize=16, fontweight='bold', y=1.02)

# 좌측: 도넛 점유율 차트
axes[0].pie(
    counts,
    labels=[n.split('(')[0].strip() for n in counts.index],
    autopct='%1.1f%%',
    startangle=140,
    colors=sns.color_palette('pastel', 6),
    wedgeprops={'edgecolor': 'white', 'linewidth': 2}
)
axes[0].add_artist(plt.Circle((0,0), 0.60, fc='white'))
axes[0].set_title('페르소나별 점유 비율 (%)', fontsize=13, pad=10)

# 우측: 가로 바 인원수 차트
sns.barplot(x=counts.values, y=counts.index, ax=axes[1], palette='flare', hue=counts.index, legend=False)
axes[1].set_title('페르소나별 실제 인원수 (명)', fontsize=13, pad=10)
axes[1].set_xlabel('인원 수 (명)')
axes[1].set_ylabel('')

for i, v in enumerate(counts.values):
    axes[1].text(v + 0.5, i, f" {v}명", va='center', fontweight='bold', color='black')

plt.tight_layout()
plt.show()

"""#그라디오"""

# ── 웹 UI 구동을 위한 패키지 설치 (필요시 주석 해제 후 실행) ──
# !pip install -q gradio

import gradio as io

def web_pipeline(age, gender, job, bmi, steps, sbp, dbp, bedtime, waketime, sleep_hours,
                 onset_idx, wakeup_idx, refresh_idx, daytime_idx, caffeine_cups,
                 caffeine_time, alcohol, phone, exercise, symptoms_list, extra):
    """
    웹 UI 컴포넌트의 입력을 받아 기존 v4.0 엔진을 구동하고 결과를 포맷팅하는 함수
    """
    # 1. 성별 매핑 (남성: 1, 여성: 0)
    gender_code = 1 if gender == "남성" else 0

    # 2. BMI 등급 매핑
    bmi_map = {"정상체중": 0, "과체중": 1, "비만": 2}
    bmi_cat = bmi_map.get(bmi, 0)

    # 3. 혈압 기반 심박수 자동 추정 (기존 함수 재사용)
    hr = estimate_heart_rate(sbp, dbp)

    # 4. 수면 질 종합 점수 계산 가중치 변환 (v4.0 로직 이식)
    sq1_w = {"5분 이내 (매우 빨리)": 4, "6~15분 (보통)": 3, "16~30분 (조금 걸림)": 2, "30분 이상 (오래 걸림)": 1}.get(onset_idx, 3)
    sq2_w = {"거의 안 깸": 4, "1주일에 1~2번 깸": 3, "1주일에 3~4번 깸": 2, "매일 여러 번 깸": 1}.get(wakeup_idx, 3)
    sq3_w = {"매우 개운함 (활기참)": 4, "어느 정도 개운함": 3, "약간 피로한 편": 2, "매우 피곤하고 무거움": 1}.get(refresh_idx, 3)
    sq5_w = {"거의 없음": 4, "가끔 피곤함": 3, "자주 졸리고 피곤함": 2, "항상 너무 졸리고 힘듦": 1}.get(daytime_idx, 3)

    if sleep_hours >= 7.0: sq4_w = 4
    elif sleep_hours >= 6.0: sq4_w = 3
    elif sleep_hours >= 5.0: sq4_w = 2
    else: sq4_w = 1

    total_sleep_w = sq1_w + sq2_w + sq3_w + sq4_w + sq5_w
    sleep_quality = int(round(np.clip(1 + 9 * (total_sleep_w - 5) / (20 - 5), 1, 10)))

    # 5. 스트레스 정밀 설문 대체 (UI 간소화를 위해 슬라이더 값을 활용하되 메디컬 스케일 조정)
    # 실제 수집 데이터 기반 1~10 스케일 반영
    stress_level = int(refresh_idx == "매우 피곤하고 무거움") + int(daytime_idx == "항상 너무 졸리고 힘듦")*2 + 4
    stress_level = int(np.clip(stress_level, 1, 10))

    # 6. ML 피처 딕셔너리 생성
    user_raw = {
        'Gender': gender_code, 'Age': age, 'Quality of Sleep': sleep_quality, 'Stress Level': stress_level,
        'BMI Category': bmi_cat, 'Heart Rate': hr, 'Daily Steps': steps, 'Systolic_BP': sbp, 'Diastolic_BP': dbp
    }

    # 7. Gemini용 생활 습관 딕셔너리 생성
    lifestyle = {
        'age': age, 'gender_txt': gender, 'job': job, 'bmi_cat': bmi, 'sbp': sbp, 'dbp': dbp, 'hr': hr,
        'bedtime': bedtime if bedtime else "미입력", 'waketime': waketime if waketime else "미입력",
        'actual_sleep_hours': sleep_hours, 'steps': steps, 'caffeine_cups': caffeine_cups,
        'caffeine_time': caffeine_time if caffeine_time else "미입력", 'alcohol': alcohol,
        'phone_minutes': phone if phone else "없음", 'exercise': exercise,
        'symptoms': ", ".join(symptoms_list) if symptoms_list else "없음", 'extra': extra if extra else "없음"
    }

    # 8. 기존 파이프라인 가동
    result = total_sleep_analysis(user_raw, lifestyle, sleep_hours)

    persona = result['페르소나']
    knn = result['KNN 목표 수치']
    gd = result['Gemini 분석']

    # 9. HTML 표 형태 및 마크다운으로 결과 출력 포맷팅
    knn_dur = f"{knn['target_sleep_duration']}시간" if knn['target_sleep_duration'] else "N/A"

    report_md = f"""
    ## 🔮 1. AI 임상 진단 및 페르소나 예측
    * **예측된 수면 상태:** **{result['예측 수면 상태']}**
    * **장애 확률 분포:** {result['수면 장애 확률']}
    * **수학적 매핑 페르소나:** `{persona['type']}` (위험도 등급: **{persona['risk_level'].upper()}**)
    * **핵심 방해 인자:** {persona['top_feature']} (방해 가중치: {persona['contribution_score']})
    * **패턴 설명:** {persona['desc']}

    ---
    ## 📊 2. 맞춤형 데이터 비교 가이드

    | 지표 | 내 현재 데이터 | KNN 유사 우수군 패턴 | Gemini AI 추천 |
    | :--- | :---: | :---: | :---: |
    | **실제 수면 시간** | {sleep_hours}시간 | {knn_dur} | {gd.get('recommended_sleep_hours', '7.5시간')} |
    | **일일 걸음 수** | {steps:,}보 | {knn['target_daily_steps']:,}보 | {steps + 2000:,}보 이상 권장 |
    | **스트레스 지수** | {stress_level}/10 | {knn['target_stress_level']}/10 | {max(1, stress_level - 2)}/10 이하 유지 |

    ---
    ## 🩺 3. 전문의 가상 의학 소견 & 생리 메커니즘
    * **종합 소견:** {gd['medical_summary']}
    * **생화학적 발병 메커니즘:** {gd['mechanism']}
    * **주의 필요 임상 징후 (전문의 진료 기준):** <span style="color:red">**{gd.get('warning_signs', '특이 소견 없음')}**</span>
    """

    # 미션 목록 출력 포맷팅
    missions_md = "### 🚀 오늘 밤 행동 처방 루틴\n"
    for i, m in enumerate(gd.get('missions', result['생활습관 조언']), 1):
        missions_md += f"{i}. **{m}**\n"

    return report_md, missions_md

# ── Gradio 레이아웃 인터페이스 빌드 ──
with io.Blocks(title="수면 코치 서비스 v4.0", theme=io.themes.Soft()) as demo:
    io.Markdown("# 🛌 AI 수면 코치 서비스 v4.0 통합 센터")
    io.Markdown("임상 데이터(RF/KNN) 분석 알고리즘과 수면의학 전문 AI 소견을 결합한 통합 대시보드입니다.")

    with io.Row():
        with io.Column(scale=1):
            io.Markdown("### 👤 [1] 기본 인적 및 신체 지표")
            age = io.Slider(minimum=10, maximum=80, value=30, step=1, label="나이")
            gender = io.Radio(choices=["남성", "여성"], value="남성", label="성별")
            job = io.Dropdown(choices=JOB_LIST + ["기타"], value=JOB_LIST[0], label="직업")
            bmi = io.Radio(choices=["정상체중", "과체중", "비만"], value="정상체중", label="BMI 상태")
            steps = io.Number(value=5000, label="하루 평균 걸음 수")
            sbp = io.Number(value=120, label="수축기(최고) 혈압 mmHg")
            dbp = io.Number(value=80, label="이완기(최저) 혈압 mmHg")

        with io.Column(scale=1):
            io.Markdown("### 🌙 [2] 주관적 수면 패턴 추적")
            bedtime = io.Textbox(placeholder="예: 23:30", label="평소 취침 시간 (선택)")
            waketime = io.Textbox(placeholder="예: 07:00", label="평소 기상 시간 (선택)")
            sleep_hours = io.Slider(minimum=1.0, maximum=16.0, value=6.5, step=0.5, label="★ 실제 평균 수면 시간")

            onset = io.Dropdown(choices=["5분 이내 (매우 빨리)", "6~15분 (보통)", "16~30분 (조금 걸림)", "30분 이상 (오래 걸림)"], value="6~15분 (보통)", label="잠드는 데 걸리는 시간")
            wakeup = io.Dropdown(choices=["거의 안 깸", "1주일에 1~2번 깸", "1주일에 3~4번 깸", "매일 여러 번 깸"], value="거의 안 깸", label="자다가 깨는 빈도")
            refresh = io.Dropdown(choices=["매우 개운함 (활기참)", "어느 정도 개운함", "약간 피로한 편", "매우 피곤하고 무거움"], value="어느 정도 개운함", label="기상 시 개운함")
            daytime = io.Dropdown(choices=["거의 없음", "가끔 피곤함", "자주 졸리고 피곤함", "항상 너무 졸리고 힘듦"], value="가끔 피곤함", label="낮 동안의 졸음 수준")

        with io.Column(scale=1):
            io.Markdown("### ☕ [3] 일상 생활 습관 및 증상")
            caffeine_cups = io.Slider(minimum=0, maximum=10, value=2, step=1, label="하루 카페인 섭취 잔 수")
            caffeine_time = io.Textbox(placeholder="예: 15:00", label="마지막 카페인 시간 (선택)")
            alcohol = io.Radio(choices=["없음", "주 1~2회", "주 3~4회", "매일"], value="없음", label="알코올 섭취 빈도")
            phone = io.Textbox(placeholder="예: 30", label="취침 전 스마트폰 사용 시간 (분)")
            exercise = io.Radio(choices=["없음", "주 1~2회", "주 3~4회", "매일"], value="주 1~2회", label="운동 빈도")

            symptoms = io.CheckboxGroup(
                choices=["잠들기 어려움", "자다가 자주 깸", "너무 일찍 잠에서 깸", "낮에 심하게 졸림", "만성 피로", "잠자리 들면 잡생각이 많음", "아침에 일어나도 피로함", "두통"],
                label="겪고 있는 주요 증상 (중복 선택 가능)"
            )
            extra = io.Textbox(placeholder="복용 약물 및 기저질환 입력 (없으면 비움)", label="기타 특이사항 및 메디컬 메모")

    submit_btn = io.Button("📊 종합 진단 및 분석 보고서 생성", variant="primary")

    with io.Row():
        out_report = io.Markdown(label="종합 임상 분석 결과 보고서")
        out_missions = io.Markdown(label="오늘 밤 행동 지침 미션")

    submit_btn.click(
        fn=web_pipeline,
        inputs=[age, gender, job, bmi, steps, sbp, dbp, bedtime, waketime, sleep_hours,
                onset, wakeup, refresh, daytime, caffeine_cups, caffeine_time, alcohol, phone, exercise, symptoms, extra],
        outputs=[out_report, out_missions]
    )

# ── 외부 접속용 공개 링크 오픈 활성화 ──
demo.launch(share=True, debug=True)

"""#스트림릿"""

# 1. 필수 패키지 설치
!pip install -q streamlit pandas numpy scikit-learn

# 2. 코랩 내부 포트를 외부로 열어줄 localtunnel 설치
!npm install -q -g localtunnel

# 3. Streamlit 소스코드 파일(app.py) 생성
# (기존에 정의하신 JOB_LIST, estimate_heart_rate, total_sleep_analysis 함수들을 이 아래에 포함시켜야 합니다.)
with open("app.py", "w", encoding="utf-8") as f:
    f.write("""import streamlit as st
import pandas as pd
import numpy as np

# [주의] 본인의 실제 수면 모델 알고리즘과 JOB_LIST 등을 여기에 채워 넣으세요.
# 테스트용 Dummy 데이터 구조입니다.
if 'JOB_LIST' not in globals():
    JOB_LIST = ["Nurse", "Doctor", "Engineer", "Teacher", "Accountant", "Salesperson"]

def estimate_heart_rate(sbp, dbp):
    return int(dbp + (sbp - dbp) / 3)

def total_sleep_analysis(user_raw, lifestyle, actual_sleep_hours):
    return {
        '예측 수면 상태': '수면 무호흡증 (Sleep Apnea) 위험군',
        '수면 장애 확률': {'정상': '12.5%', '불면증': '22.0%', '수면 무호흡증': '65.5%'},
        '페르소나': {
            'type': '야간 교대근무 생체리듬 교란형', 'risk_level': 'high',
            'top_feature': 'Systolic_BP (수축기 혈압)', 'contribution_score': '4.25',
            'desc': '높은 혈압 변동성이 깊은 수면을 방해합니다.'
        },
        'KNN 목표 수치': {
            'target_sleep_duration': 7.5, 'target_daily_steps': 8000, 'target_stress_level': 3,
            'knn_behavioral_tips': ['취침 전 2시간 동안 카페인을 전면 통제했습니다.']
        },
        '생활습관 조언': ['취침 1시간 전 스마트폰 사용 금지'],
        'Gemini 분석': {
            'medical_summary': '교감신경 항진이 야간 각성을 유발하는 것으로 보입니다.',
            'mechanism': '카페인 자극 -> 아데노신 차단 -> 멜라토닌 분비 지연',
            'missions': ['마지막 카페인을 오후 2시 이전으로 고정하세요.'],
            'warning_signs': '특이 소견 없음', 'recommended_sleep_hours': '7.5시간'
        }
    }

# Streamlit 레이아웃 빌드
st.set_page_config(page_title="AI 수면 코치 v4.0", layout="wide")

st.title("🛌 AI 수면 코치 서비스 v4.0 (Colab 호스트)")
st.caption("임상 데이터(RF/KNN) 분석 알고리즘과 수면의학 전문 AI 소견 통합 대시보드")
st.divider()

# 레이아웃 구성
st.sidebar.header("👤 [1] 신체 지표")
with st.sidebar:
    age = st.slider("나이", 15, 80, 32)
    gender = st.radio("성별", ["여성", "남성"])
    job = st.selectbox("직업군", JOB_LIST)
    bmi_txt = st.radio("BMI", ["정상체중", "과체중", "비만"])
    steps = st.number_input("걸음 수", value=4300)
    sbp = st.number_input("수축기 혈압", value=135)
    dbp = st.number_input("이완기 혈압", value=88)

col1, col2 = st.columns(2)
with col1:
    st.subheader("🌙 [2] 수면 패턴")
    bedtime = st.text_input("취침 시간", value="23:30")
    waketime = st.text_input("기상 시간", value="07:00")
    sleep_hours = st.slider("★ 실제 수면 시간", 2.0, 12.0, 5.5, step=0.5)
    onset_idx = st.selectbox("잠들기까지 시간", ["5분 이내", "6~15분", "16~30분", "30분 이상"])
    wakeup_idx = st.selectbox("자다 깨는 빈도", ["거의 안 깸", "주 1~2회", "주 3~4회", "매일 여러 번"])
    refresh_idx = st.selectbox("기상 시 개운함", ["매우 개운", "어느 정도", "약간 피로", "매우 피곤"])
    daytime_idx = st.selectbox("낮 졸음", ["거의 없음", "가끔 피곤", "자주 졸림", "항상 졸림"])

with col2:
    st.subheader("☕ [3] 생활 습관")
    caffeine_cups = st.slider("카페인 (잔)", 0, 8, 3)
    caffeine_time = st.text_input("마지막 카페인", value="17:00")
    alcohol = st.radio("음주 빈도", ["없음", "주 1~2회", "주 3~4회", "매일"])
    phone = st.text_input("취침 전 스마트폰 (분)", value="60")
    exercise = st.radio("운동 빈도", ["없음", "주 1~2회", "주 3~4회", "매일"])
    symptoms_list = st.multiselect("증상", ["잠들기 어려움", "자다 깸", "낮 졸음", "만성 피로"], default=["잠들기 어려움", "낮 졸음"])
    extra = st.text_area("메디컬 메모", value="없음")

if st.button("📊 종합 진단 및 수면 분석 보고서 출력", type="primary"):
    # 가중치 맵 계산 및 파이프라인 연동 부분
    user_raw = {'Gender': 0, 'Age': age, 'Quality of Sleep': 5, 'Stress Level': 6, 'BMI Category': 1, 'Heart Rate': 75, 'Daily Steps': steps, 'Systolic_BP': sbp, 'Diastolic_BP': dbp}
    lifestyle = {'age': age, 'gender_txt': gender, 'job': job, 'bmi_cat': bmi_txt, 'sbp': sbp, 'dbp': dbp, 'hr': 75, 'bedtime': bedtime, 'waketime': waketime, 'actual_sleep_hours': sleep_hours, 'steps': steps, 'caffeine_cups': caffeine_cups, 'caffeine_time': caffeine_time, 'alcohol': alcohol, 'phone_minutes': phone, 'exercise': exercise, 'symptoms': ", ".join(symptoms_list), 'extra': extra}

    result = total_sleep_analysis(user_raw, lifestyle, sleep_hours)
    persona = result['페르소나']
    knn = result['KNN 목표 수치']
    gd = result['Gemini 분석']

    st.header("📋 수면 코치 종합 진단 보고서")
    m_col1, m_col2 = st.columns(2)
    m_col1.metric("🩺 ML 모델 예측 상태", result['예측 수면 상태'])
    m_col2.metric("🎭 페르소나 유형", persona['type'])

    st.info(f"**페르소나 분석:** {persona['desc']}")

    compare_df = pd.DataFrame({
        "내 데이터": [f"{sleep_hours}시간", f"{steps:,}보"],
        "KNN 우수군": [f"{knn['target_sleep_duration']}시간", f"{knn['target_daily_steps']:,}보"],
    }, index=["수면 시간", "걸음 수"])
    st.table(compare_df)

    st.subheader("🚀 행동 처방 미션")
    for i, m in enumerate(gd['missions'], 1):
        st.checkbox(f"**미션 {i}:** {m}")
""")

# 4. 코랩 서버의 공인 IP 확인 (원격 터널 링크 비밀번호로 사용됨)
import urllib
print("🔗 [필독] 터널 비밀번호(Endpoint IP):", urllib.request.urlopen('https://ipv4.icanhazip.com').read().decode('utf8').strip())

# 5. 백그라운드에서 Streamlit 실행 및 외부 링크 오픈
import subprocess
subprocess.Popen(["streamlit", "run", "app.py", "--server.port", "8501"])
!npx localtunnel --port 8501

# Commented out IPython magic to ensure Python compatibility.
# 1. 구글 드라이브 연결
from google.colab import drive
drive.mount('/content/drive')

# 2. 깃허브 프로젝트 폴더로 이동
# %cd /content/26-1-team5

# 1. 변경된 모든 파일(README 포함)을 스테이징 영역에 추가
!git add .

# 2. 커밋 메시지 작성 (원하는 메시지로 변경 가능)
!git commit -m "docs: README.md 추가 및 코드 업데이트"

# 3. 깃허브 원격 저장소로 푸시
!git push origin main