# -*- coding: utf-8 -*-
"""다코스 프로젝트 수면조언 성공만 수정

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1sVW-kh5lIynV6epQuTL0r6l2rB6LvQjf
"""

# Commented out IPython magic to ensure Python compatibility.
# %%writefile README.md
# # 26-1-team5 프로젝트
# 
# 이 프로젝트는 Google Colab 환경에서 개발되었습니다.
# 
# ## 실행 방법
# 1. 코랩에서 이 노트북을 엽니다.
# 2. 상단 메뉴에서 `런타임` -> `모두 실행`을 누릅니다.

"""GEMINI없는거"""

# =========================================================
# 수면 장애 예측 + 5대 페르소나 + 생활습관 추천 시스템 v3
# [코랩 완전 독립 실행 — 외부 API 없음]
#
# 변경 사항:
#   1. 수면 질 & 스트레스 → 5문항 설문 + 규칙 기반 자동 채점
#      (PSQI / PSS 임상 척도 가중치 로직 내장)
#   2. 심박수 → 혈압 기반 자동 추정 (추가 입력 불필요)
#   3. anthropic 패키지 완전 제거
# =========================================================


# =========================================================
# CELL 1 — 패키지 설치 (코랩 첫 실행 시 한 번만)
# =========================================================

# !pip install -q shap


# =========================================================
# CELL 2 — 라이브러리 임포트
# =========================================================

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import matplotlib
import seaborn as sns

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.ensemble import RandomForestClassifier
from sklearn.neighbors import NearestNeighbors
from sklearn.metrics import classification_report, confusion_matrix, f1_score

import shap

# 한글 폰트 설정 (코랩)
try:
    matplotlib.rc('font', family='NanumGothic')
except Exception:
    pass
matplotlib.rcParams['axes.unicode_minus'] = False
sns.set(style='whitegrid')

print("✅ 라이브러리 로드 완료")


# =========================================================
# CELL 3 — 데이터 불러오기 & 전처리
#
# 데이터셋 업로드 방법 (둘 중 하나):
#
# [방법 A] 직접 업로드
#   from google.colab import files
#   files.upload()   # Sleep_health_and_lifestyle_dataset.csv 선택
#
# [방법 B] Kaggle API
#   !pip install -q kaggle
#   # Kaggle API 키를 코랩 Secrets에 등록 후:
#   !kaggle datasets download -d uom190346a/sleep-health-and-lifestyle-dataset
#   !unzip -q sleep-health-and-lifestyle-dataset.zip
# =========================================================
from google.colab import files
uploaded = files.upload()

# kaggle.json 업로드


# =========================
# 2. Kaggle API 설정
# =========================

import os

# kaggle 폴더 생성
os.makedirs('/root/.kaggle', exist_ok=True)

# kaggle.json 이동
!mv kaggle.json /root/.kaggle/

# 권한 설정
!chmod 600 /root/.kaggle/kaggle.json


# =========================
# 3. 데이터셋 다운로드
# =========================

!kaggle datasets download -d uom190346a/sleep-health-and-lifestyle-dataset


# =========================
# 4. 압축 해제
# =========================

!unzip sleep-health-and-lifestyle-dataset.zip
df = pd.read_csv('Sleep_health_and_lifestyle_dataset.csv')
df = pd.read_csv('Sleep_health_and_lifestyle_dataset.csv')
print("원본 shape:", df.shape)
print(df.head())

# 결측치 처리
df['Sleep Disorder'] = df['Sleep Disorder'].fillna('Normal')
print("\nSleep Disorder 분포:")
print(df['Sleep Disorder'].value_counts())

# 혈압 분리
df[['Systolic_BP', 'Diastolic_BP']] = (
    df['Blood Pressure'].str.split('/', expand=True).astype(int)
)

# 성별 인코딩
df['Gender'] = df['Gender'].map({'Female': 0, 'Male': 1})

# BMI 서열 인코딩
bmi_map = {'Normal': 0, 'Normal Weight': 0, 'Overweight': 1, 'Obese': 2}
df['BMI Category'] = df['BMI Category'].map(bmi_map)

# ----------------------------------------------------------
# 심박수 대안 — 혈압 기반 자동 추정
#
# 근거: Palatini et al. (2006) Heart Rate as a Risk Factor
# 추정식: HR = 0.25 × SBP + 0.35 × DBP + 25  (±8 bpm)
# 원본 컬럼이 있으면 그대로 사용, 없거나 null이면 추정값 사용
# ----------------------------------------------------------
def estimate_heart_rate(sbp: float, dbp: float) -> int:
    hr = 0.25 * sbp + 0.35 * dbp + 25
    return int(np.clip(hr, 45, 120))

if 'Heart Rate' not in df.columns or df['Heart Rate'].isnull().any():
    df['Heart Rate'] = df.apply(
        lambda r: estimate_heart_rate(r['Systolic_BP'], r['Diastolic_BP']), axis=1
    )
    print("⚠️  Heart Rate: 혈압 기반 추정값 사용")
else:
    print("✅ Heart Rate: 원본 데이터 사용")


# =========================================================
# CELL 4 — 규칙 기반 설문 채점 시스템
#
# PSQI(Pittsburgh Sleep Quality Index) 기반 수면 질 채점
# PSS(Perceived Stress Scale) 기반 스트레스 채점
#
# 설계 원칙:
#   - 각 문항 응답(1~4)에 임상 가중치 부여
#   - 문항별 점수 합산 후 1~10 구간으로 선형 변환
#   - 수면 질: 높을수록 좋음 (1=매우 나쁨, 10=매우 좋음)
#   - 스트레스: 높을수록 나쁨 (1=없음, 10=극심)
# =========================================================

# ----------------------------------------------------------
# 수면 질 설문 5문항
# 각 문항: (ID, 질문, 선택지, 가중치_리스트)
#   가중치: 응답 1번이 index 0, 4번이 index 3
#   수면 질은 응답 번호가 낮을수록 좋음 → 가중치 높게
# ----------------------------------------------------------
SLEEP_QUESTIONS = [
    {
        "id"      : "SQ1",
        "question": "잠들기까지 얼마나 걸리나요?",
        "options" : ["① 5분 이내", "② 6~15분", "③ 16~30분", "④ 30분 이상"],
        "weights" : [4, 3, 2, 1],   # 빠를수록 수면 질 좋음
    },
    {
        "id"      : "SQ2",
        "question": "밤 중에 깨는 빈도는?",
        "options" : ["① 거의 없음", "② 주 1~2회", "③ 주 3~4회", "④ 매일 여러 번"],
        "weights" : [4, 3, 2, 1],   # 적게 깰수록 좋음
    },
    {
        "id"      : "SQ3",
        "question": "아침에 일어났을 때 개운함은?",
        "options" : ["① 매우 개운함", "② 보통", "③ 약간 피로함", "④ 매우 피로함"],
        "weights" : [4, 3, 2, 1],
    },
    {
        "id"      : "SQ4",
        "question": "실제 수면 시간은?",
        "options" : ["① 7~9시간", "② 6~7시간", "③ 5~6시간", "④ 5시간 미만"],
        "weights" : [4, 3, 2, 1],   # PSQI 권장 수면 7~9시간
    },
    {
        "id"      : "SQ5",
        "question": "낮 동안 졸림이나 피로감은?",
        "options" : ["① 거의 없음", "② 가끔", "③ 자주", "④ 항상"],
        "weights" : [4, 3, 2, 1],
    },
]

# ----------------------------------------------------------
# 스트레스 설문 5문항
# ----------------------------------------------------------
STRESS_QUESTIONS = [
    {
        "id"      : "SS1",
        "question": "최근 일주일간 해야 할 일이 너무 많다는 느낌은?",
        "options" : ["① 거의 없음", "② 가끔", "③ 자주", "④ 항상"],
        "weights" : [1, 3, 6, 9],   # 많을수록 스트레스 높음
    },
    {
        "id"      : "SS2",
        "question": "몸이 긴장되거나 어깨/목이 뭉치는 느낌은?",
        "options" : ["① 없음", "② 가끔", "③ 자주", "④ 항상"],
        "weights" : [1, 3, 6, 9],
    },
    {
        "id"      : "SS3",
        "question": "일상을 스스로 통제하고 있다는 느낌은?",
        "options" : ["① 충분히 통제됨", "② 대체로 통제됨", "③ 통제가 어려움", "④ 전혀 통제 안 됨"],
        "weights" : [1, 3, 6, 9],   # PSS 통제감 역산 문항
    },
    {
        "id"      : "SS4",
        "question": "두통·소화불량 등 스트레스성 신체 증상은?",
        "options" : ["① 없음", "② 가끔", "③ 자주", "④ 항상"],
        "weights" : [1, 3, 6, 9],
    },
    {
        "id"      : "SS5",
        "question": "퇴근/하교 후 심리적으로 회복되는 느낌은?",
        "options" : ["① 충분히 회복됨", "② 어느 정도", "③ 잘 안 됨", "④ 전혀 안 됨"],
        "weights" : [1, 3, 6, 9],
    },
]


def score_sleep_quality(answers: dict) -> tuple:
    """
    수면 질 설문 응답 → 1~10 점수 변환 (PSQI 가중치 기반)

    Parameters
    ----------
    answers : {"SQ1": 1~4, "SQ2": 1~4, ...}

    Returns
    -------
    (score: int, detail: str)
    """
    total = 0
    max_possible = 0
    for q in SLEEP_QUESTIONS:
        ans_idx = answers[q["id"]] - 1          # 1~4 → 0~3 인덱스
        total        += q["weights"][ans_idx]
        max_possible += max(q["weights"])

    # 가중치 합을 1~10 구간으로 선형 변환
    min_possible = sum(min(q["weights"]) for q in SLEEP_QUESTIONS)
    score = 1 + 9 * (total - min_possible) / (max_possible - min_possible)
    score = int(round(np.clip(score, 1, 10)))

    # 등급 설명
    if score >= 8:
        detail = "우수 — PSQI 기준 매우 양호한 수면 상태"
    elif score >= 6:
        detail = "양호 — 경미한 수면 문제 존재, 개선 여지 있음"
    elif score >= 4:
        detail = "주의 — 임상적 수면 장애 경계 수준"
    else:
        detail = "위험 — 전문의 상담 권장"

    return score, detail


def score_stress(answers: dict) -> tuple:
    """
    스트레스 설문 응답 → 1~10 점수 변환 (PSS 가중치 기반)

    Parameters
    ----------
    answers : {"SS1": 1~4, "SS2": 1~4, ...}

    Returns
    -------
    (score: int, detail: str)
    """
    total = 0
    max_possible = 0
    for q in STRESS_QUESTIONS:
        ans_idx = answers[q["id"]] - 1
        total        += q["weights"][ans_idx]
        max_possible += max(q["weights"])

    min_possible = sum(min(q["weights"]) for q in STRESS_QUESTIONS)
    score = 1 + 9 * (total - min_possible) / (max_possible - min_possible)
    score = int(round(np.clip(score, 1, 10)))

    if score <= 3:
        detail = "낮음 — 심리적 안정 상태"
    elif score <= 5:
        detail = "보통 — 일상적 스트레스 수준"
    elif score <= 7:
        detail = "높음 — 코르티솔 과다 분비 가능성"
    else:
        detail = "매우 높음 — 번아웃·불면 위험, 즉각적 관리 필요"

    return score, detail


def collect_survey_cli(questions: list, category: str) -> dict:
    """CLI 방식으로 설문 응답 수집"""
    print(f"\n{'─'*55}")
    print(f"  📋 {category} 설문 (1~4 중 하나 입력)")
    print(f"{'─'*55}")
    answers = {}
    for q in questions:
        print(f"\n{q['id']}. {q['question']}")
        for opt in q['options']:
            print(f"     {opt}")
        while True:
            try:
                val = int(input("  → 입력 (1~4): ").strip())
                if 1 <= val <= 4:
                    answers[q['id']] = val
                    break
                print("  ⚠️  1~4 사이 숫자를 입력하세요.")
            except ValueError:
                print("  ⚠️  숫자만 입력하세요.")
    return answers


# =========================================================
# CELL 5 — EDA 시각화
# =========================================================

fig, axes = plt.subplots(2, 2, figsize=(12, 8))
fig.suptitle('Sleep Disorder — EDA', fontsize=14)

sns.countplot(data=df, x='Sleep Disorder', ax=axes[0, 0])
axes[0, 0].set_title('Sleep Disorder 분포')

sns.boxplot(data=df, x='Sleep Disorder', y='Quality of Sleep', ax=axes[0, 1])
axes[0, 1].set_title('수면 질 by 진단')

sns.boxplot(data=df, x='Sleep Disorder', y='Stress Level', ax=axes[1, 0])
axes[1, 0].set_title('스트레스 수준 by 진단')

sns.scatterplot(
    data=df, x='Stress Level', y='Quality of Sleep',
    hue='Sleep Disorder', ax=axes[1, 1]
)
axes[1, 1].set_title('스트레스 vs 수면 질')

plt.tight_layout()
plt.show()


# =========================================================
# CELL 6 — 피처 설정 & 모델 학습
# =========================================================

FEATURE_COLS = [
    'Gender', 'Age',
    'Quality of Sleep',
    'Stress Level',
    'BMI Category',
    'Heart Rate',
    'Daily Steps',
    'Systolic_BP',
    'Diastolic_BP',
]
TARGET_COL = 'Sleep Disorder'

X = df[FEATURE_COLS]
y = df[TARGET_COL]

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42, stratify=y
)

scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled  = scaler.transform(X_test)

model = RandomForestClassifier(
    n_estimators=200, max_depth=6,
    class_weight='balanced', random_state=42
)
model.fit(X_train_scaled, y_train)

y_pred  = model.predict(X_test_scaled)
y_proba = model.predict_proba(X_test_scaled)

print("\n" + "━" * 60)
print("📊 수면 장애 진단 모델 성능 리포트")
print("━" * 60)
print(classification_report(y_test, y_pred))
print(f"✨ Macro F1-Score: {f1_score(y_test, y_pred, average='macro'):.4f}")

# 혼동 행렬
plt.figure(figsize=(6, 5))
sns.heatmap(
    confusion_matrix(y_test, y_pred, labels=model.classes_),
    annot=True, fmt='d',
    xticklabels=model.classes_,
    yticklabels=model.classes_,
)
plt.title('Confusion Matrix')
plt.xlabel('Predicted')
plt.ylabel('Actual')
plt.show()

# Feature Importance
importance_df = pd.DataFrame({
    'Feature'   : FEATURE_COLS,
    'Importance': model.feature_importances_
}).sort_values('Importance', ascending=False)

plt.figure(figsize=(8, 5))
sns.barplot(data=importance_df, x='Importance', y='Feature')
plt.title('Feature Importance')
plt.tight_layout()
plt.show()


# =========================================================
# CELL 7 — SHAP 해석
# =========================================================

explainer   = shap.TreeExplainer(model)
shap_values = explainer.shap_values(X_test_scaled)
shap.summary_plot(shap_values, X_test_scaled, feature_names=FEATURE_COLS)


# =========================================================
# CELL 8 — 페르소나 매핑 함수
# =========================================================

def assign_persona(disorder: str, user_data: dict) -> dict:
    stress  = user_data['Stress Level']
    quality = user_data['Quality of Sleep']

    if disorder == 'Normal':
        if quality >= 7 and stress <= 5:
            return {
                'type'      : '🌙 Deep Rest (안정적 수면형)',
                'desc'      : (
                    'PSQI 국제 기준 "매우 우수한 수면 상태"입니다. '
                    '부교감신경이 활성화된 심리적 안정 상태로, '
                    '현재 수면 패턴을 유지하는 것이 최선입니다.'
                ),
                'risk_level': 'low',
            }
        else:
            return {
                'type'      : '🏃 Recovery Booster (활동 회복형)',
                'desc'      : (
                    'JCSM 논문 기준, 신체 활동 이후 수면을 통해 '
                    '근육 합성 및 뇌 노폐물 제거를 진행 중인 상태입니다. '
                    '수면의 질을 7점 이상으로 끌어올리면 회복 효율이 더욱 높아집니다.'
                ),
                'risk_level': 'low',
            }

    elif disorder == 'Insomnia':
        if stress >= 6:
            return {
                'type'      : '⚡ Stress Sleeper (스트레스 과부하형)',
                'desc'      : (
                    '임상적 고스트레스(High Stress)군으로, 코르티솔 호르몬이 '
                    '뇌의 각성을 유지시켜 입면을 방해하는 전형적인 스트레스성 불면 상태입니다. '
                    '취침 전 스마트폰 차단, 4-7-8 호흡법 실천을 권장합니다.'
                ),
                'risk_level': 'high',
            }
        else:
            return {
                'type'      : '🔄 Irregular Rhythm (수면 리듬 불균형형)',
                'desc'      : (
                    'World Sleep Society 기준 생체 리듬 붕괴 상태입니다. '
                    '스트레스가 극심하지 않음에도 잦은 수면 분절이 발생합니다. '
                    '취침·기상 시각을 고정하는 수면 제한 요법(Sleep Restriction Therapy)을 권장합니다.'
                ),
                'risk_level': 'medium',
            }

    else:  # Sleep Apnea
        return {
            'type'      : '🫁 Apnea Risk (호흡 불안형)',
            'desc'      : (
                'Mayo Clinic 연구 기준, 수면 중 기도 협착으로 반복적인 '
                '호흡 정지가 발생하는 상태입니다. BMI 관리 및 측면 수면 자세 유지, '
                '필요 시 수면 전문의 상담을 강력히 권장합니다.'
            ),
            'risk_level': 'high',
        }


# =========================================================
# CELL 9 — KNN 추천 + 생활습관 조언
# =========================================================

knn_scaler = StandardScaler()
knn_scaled = knn_scaler.fit_transform(df[FEATURE_COLS])
knn = NearestNeighbors(n_neighbors=8, metric='euclidean')
knn.fit(knn_scaled)


def recommend_sleep(user_raw: dict) -> dict:
    user_df    = pd.DataFrame([user_raw])
    user_sc    = knn_scaler.transform(user_df)
    _, indices = knn.kneighbors(user_sc)
    similar    = df.iloc[indices[0]]
    good       = similar[similar['Quality of Sleep'] >= 7]
    ref        = good if len(good) >= 2 else similar
    return {
        'target_daily_steps' : int(ref['Daily Steps'].mean()),
        'target_stress_level': round(ref['Stress Level'].mean(), 1),
        'target_quality'     : round(ref['Quality of Sleep'].mean(), 1),
        'reference_size'     : len(ref),
    }


def lifestyle_advice(user_raw: dict, knn_target: dict) -> list:
    advice = []
    if user_raw['Stress Level'] > knn_target['target_stress_level']:
        diff = round(user_raw['Stress Level'] - knn_target['target_stress_level'], 1)
        advice.append(
            f"스트레스 수준이 유사 건강 수면군 평균보다 {diff}점 높습니다. "
            "명상, 취침 1시간 전 스마트폰 차단을 권장합니다."
        )
    if user_raw['Daily Steps'] < knn_target['target_daily_steps']:
        diff = knn_target['target_daily_steps'] - user_raw['Daily Steps']
        advice.append(
            f"걸음 수가 목표 대비 {diff:,}보 부족합니다. "
            "하루 20분 걷기부터 시작하세요."
        )
    if user_raw['Heart Rate'] >= 80:
        advice.append(
            "심박수가 높은 편입니다(≥80 bpm). "
            "카페인 섭취를 오후 2시 이전으로 제한하고 규칙적인 유산소 운동을 권장합니다."
        )
    if user_raw['BMI Category'] >= 2:
        advice.append(
            "비만(Obese) 범주에 해당합니다. "
            "체중 감량은 수면무호흡 위험을 직접적으로 낮추는 가장 효과적인 개입입니다."
        )
    if not advice:
        advice.append("현재 생활 패턴은 유사 건강 수면군과 비교해 양호합니다. 현재 습관을 유지하세요.")
    return advice


# =========================================================
# CELL 10 — 전체 분석 함수
# =========================================================

def total_sleep_analysis(user_raw: dict) -> dict:
    user_df    = pd.DataFrame([user_raw])
    user_sc    = scaler.transform(user_df)
    pred_class = model.predict(user_sc)[0]
    pred_proba = model.predict_proba(user_sc)[0]
    proba_dict = {
        cls: f"{round(prob * 100, 1)}%"
        for cls, prob in zip(model.classes_, pred_proba)
    }
    persona    = assign_persona(pred_class, user_raw)
    knn_target = recommend_sleep(user_raw)
    advice     = lifestyle_advice(user_raw, knn_target)
    return {
        '예측 수면 상태': pred_class,
        '수면 장애 확률': proba_dict,
        '페르소나'      : persona,
        'KNN 목표 수치' : knn_target,
        '생활습관 조언' : advice,
    }


# =========================================================
# CELL 11 — 신규 사용자 분석 실행 (설문 + 채점 + 결과)
#
# 이 셀을 실행하면:
#   1. 수면 질 5문항 응답 → 규칙 기반 자동 채점 (1~10)
#   2. 스트레스 5문항 응답 → 규칙 기반 자동 채점 (1~10)
#   3. 기본 정보 입력 (나이, 성별, BMI, 혈압, 걸음 수)
#   4. 심박수 혈압으로 자동 추정
#   5. 수면 장애 예측 + 페르소나 + 조언 출력
# =========================================================

def run_full_analysis():
    print("\n" + "=" * 55)
    print("🛌 수면 건강 종합 분석")
    print("=" * 55)

    # STEP 1: 수면 질 설문
    sleep_answers = collect_survey_cli(SLEEP_QUESTIONS, "수면 질")
    sleep_score, sleep_detail = score_sleep_quality(sleep_answers)
    print(f"\n  ✅ 수면 질 점수 : {sleep_score}/10")
    print(f"     {sleep_detail}")

    # STEP 2: 스트레스 설문
    stress_answers = collect_survey_cli(STRESS_QUESTIONS, "스트레스")
    stress_score, stress_detail = score_stress(stress_answers)
    print(f"\n  ✅ 스트레스 점수 : {stress_score}/10")
    print(f"     {stress_detail}")

    # STEP 3: 기본 정보 입력
    print("\n" + "─" * 55)
    print("  📝 기본 정보 입력")
    print("─" * 55)
    gender      = int(input("성별 (0=여성, 1=남성): ").strip())
    age         = int(input("나이: ").strip())
    print("BMI 카테고리:  0=정상  1=과체중  2=비만")
    bmi_cat     = int(input("BMI 카테고리 (0/1/2): ").strip())
    daily_steps = int(input("하루 평균 걸음 수 (예: 7000): ").strip())
    print("혈압 입력 (mmHg)")
    sbp         = int(input("  수축기 혈압 (예: 120): ").strip())
    dbp         = int(input("  이완기 혈압 (예: 80) : ").strip())

    # 심박수 자동 추정
    hr = estimate_heart_rate(sbp, dbp)
    print(f"\n  💓 심박수 자동 추정: {hr} bpm  (혈압 기반 ±8 bpm)")

    # STEP 4: 사용자 딕셔너리 조립
    user_raw = {
        'Gender'          : gender,
        'Age'             : age,
        'Quality of Sleep': sleep_score,
        'Stress Level'    : stress_score,
        'BMI Category'    : bmi_cat,
        'Heart Rate'      : hr,
        'Daily Steps'     : daily_steps,
        'Systolic_BP'     : sbp,
        'Diastolic_BP'    : dbp,
    }

    # STEP 5: 분석 & 출력
    result  = total_sleep_analysis(user_raw)
    persona = result['페르소나']
    knn     = result['KNN 목표 수치']

    print("\n" + "=" * 55)
    print("📋 분석 결과")
    print("=" * 55)
    print(f"\n  🔵 수면 질 점수  : {sleep_score}/10  ({sleep_detail})")
    print(f"  🔴 스트레스 점수 : {stress_score}/10  ({stress_detail})")
    print(f"\n  🩺 예측 수면 장애 : {result['예측 수면 상태']}")
    print(f"  📊 확률 분포      : {result['수면 장애 확률']}")
    print(f"\n  👤 페르소나  : {persona['type']}")
    print(f"  ⚠️  리스크    : {persona['risk_level'].upper()}")
    print(f"\n  📖 설명:")
    print(f"     {persona['desc']}")
    print(f"\n  💡 생활습관 조언:")
    for i, adv in enumerate(result['생활습관 조언'], 1):
        print(f"     {i}. {adv}")
    print(f"\n  🎯 KNN 유사 건강 수면군 목표:")
    print(f"     걸음 수  : {knn['target_daily_steps']:,} 보")
    print(f"     스트레스 : {knn['target_stress_level']}/10")
    print(f"     수면 질  : {knn['target_quality']}/10")

    return result, user_raw


# 실행 (주석 해제 후 사용)
# result, user_raw = run_full_analysis()


# =========================================================
# CELL 12 — 빠른 검증 테스트 (고정 입력값, 설문 없음)
# =========================================================

def quick_test():
    print("\n" + "=" * 55)
    print("🧪 빠른 검증 테스트")
    print("=" * 55)

    # 수면 질 — 입면 오래 걸리고 자주 깨는 케이스
    mock_sleep = {"SQ1": 3, "SQ2": 3, "SQ3": 3, "SQ4": 2, "SQ5": 3}
    # 스트레스 — 높은 케이스
    mock_stress = {"SS1": 4, "SS2": 3, "SS3": 3, "SS4": 3, "SS5": 3}

    sleep_score,  sleep_detail  = score_sleep_quality(mock_sleep)
    stress_score, stress_detail = score_stress(mock_stress)

    sbp, dbp = 130, 85
    hr = estimate_heart_rate(sbp, dbp)

    user_raw = {
        'Gender'          : 0,
        'Age'             : 32,
        'Quality of Sleep': sleep_score,
        'Stress Level'    : stress_score,
        'BMI Category'    : 1,
        'Heart Rate'      : hr,
        'Daily Steps'     : 4500,
        'Systolic_BP'     : sbp,
        'Diastolic_BP'    : dbp,
    }

    result  = total_sleep_analysis(user_raw)
    persona = result['페르소나']

    print(f"\n  수면 질 채점  : {sleep_score}/10  — {sleep_detail}")
    print(f"  스트레스 채점 : {stress_score}/10  — {stress_detail}")
    print(f"  심박수 추정   : {hr} bpm  (수축기 {sbp} / 이완기 {dbp})")
    print(f"  예측 수면 장애 : {result['예측 수면 상태']}")
    print(f"  확률           : {result['수면 장애 확률']}")
    print(f"  페르소나       : {persona['type']}")
    print(f"  리스크         : {persona['risk_level'].upper()}")
    print(f"  조언           : {result['생활습관 조언'][0]}")
    return result


result = quick_test()


# =========================================================
# CELL 13 — 테스트 세트 전체 페르소나 분포
# =========================================================

test_df = df.iloc[X_test.index].copy()
test_df['ML_Prediction'] = y_pred
test_df['Persona'] = test_df.apply(
    lambda row: assign_persona(
        row['ML_Prediction'],
        {col: row[col] for col in FEATURE_COLS}
    )['type'],
    axis=1
)

print("\n" + "=" * 55)
print("📊 테스트 세트 페르소나 분포")
print("=" * 55)
print(test_df['Persona'].value_counts())

plt.figure(figsize=(9, 4))
test_df['Persona'].value_counts().plot(kind='barh')
plt.title('5대 페르소나 분포 (Test Set)')
plt.xlabel('인원 수')
plt.tight_layout()
plt.show()


# =========================================================
# CELL 14 — [선택] 웨어러블 CSV 심박수 연동
#
# 삼성 헬스 / 애플 워치 / Fitbit CSV에서
# 안정시 심박수를 자동으로 읽어오는 보조 함수입니다.
#
# 사용법:
#   from google.colab import files
#   uploaded = files.upload()          # 웨어러블 CSV 선택
#   csv_name = list(uploaded.keys())[0]
#   hr = read_wearable_hr(csv_name, source="samsung")
# =========================================================

def read_wearable_hr(filepath, source="samsung", date_col=None, hr_col=None):
    """
    웨어러블 CSV → 최근 7일 안정시 심박수 평균 추출

    source 별 기본 컬럼:
      samsung : start_time, heart_rate
      apple   : startDate,  value
      fitbit  : dateTime,   value
      custom  : date_col, hr_col 직접 지정
    """
    col_map = {
        "samsung": ("start_time", "heart_rate"),
        "apple"  : ("startDate",  "value"),
        "fitbit" : ("dateTime",   "value"),
        "custom" : (date_col or "date", hr_col or "heart_rate"),
    }
    dcol, hcol = col_map.get(source, col_map["custom"])

    try:
        wdf     = pd.read_csv(filepath, parse_dates=[dcol])
        cutoff  = wdf[dcol].max() - pd.Timedelta(days=7)
        recent  = wdf[wdf[dcol] >= cutoff]
        # 하위 25% = 안정시 심박수 추정
        thresh  = recent[hcol].quantile(0.25)
        resting = recent[recent[hcol] <= thresh][hcol]
        avg_hr  = int(resting.mean())
        print(f"✅ 웨어러블 연동 성공 — 안정시 심박수: {avg_hr} bpm (최근 7일)")
        return avg_hr
    except Exception as e:
        print(f"⚠️  웨어러블 CSV 읽기 실패: {e}\n    혈압 추정값을 대신 사용합니다.")
        return None

"""의학적인 내용이 너무 적은 느낌이어서 LLM을 API로 불러오고자함

# **시크릿 버전 + 모델 성공 버전**
"""

# =========================================================
# 수면 코치 서비스 — 코랩 단일 파일 (Gemini API 연동)
#
# 설치: !pip install -q google-generativeai shap
# Gemini API 키: https://aistudio.google.com (무료)
# =========================================================


# =========================================================
# CELL 1 — 패키지 설치
# =========================================================
# !pip install -q google-generativeai shap scikit-learn pandas numpy joblib

# CELL 1 — 패키지 설치
!pip install -q -U google-genai scikit-learn pandas numpy
# =========================================================
# CELL 2 — 라이브러리 임포트
# =========================================================
import pandas as pd
import numpy as np
import json
import google.generativeai as genai
import os
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.ensemble import RandomForestClassifier
from sklearn.neighbors import NearestNeighbors
from sklearn.metrics import classification_report, f1_score


print("✅ 라이브러리 로드 완료")


# =========================================================
# CELL 3 — Gemini API 초기화
# =========================================================
# aistudio.google.com 에서 무료 발급
# =========================================================
# CELL 3 — Gemini API 초기화 (Secret 버전)
# =========================================================
#GEMINI_API_KEY = "AIzaSyDgjWuwPUOsbFErTtoOvx7liJ1NuoMia3Q"
'''
from google.colab import userdata
import google.generativeai as genai
# Colab Secret에서 API Key 읽기
GEMINI_API_KEY = userdata.get("GOOGLE_API_KEY")

# Gemini 설정
genai.configure(api_key=GEMINI_API_KEY)

genai.configure(api_key=GEMINI_API_KEY)

gemini = genai.GenerativeModel("gemini-2.0-flash")

# 연결 테스트
try:
    test = gemini.generate_content("안녕")
    print("✅ Gemini 연결 성공")
except Exception as e:
    print(f"❌ Gemini 연결 실패: {e}")
    '''

from google.colab import userdata
import google.generativeai as genai
#from google import genai



# Colab Secret에서 API Key 읽기

GEMINI_API_KEY = userdata.get("GOOGLE_API_KEY")
genai.configure(api_key=GEMINI_API_KEY)

# 실제 사용 가능한 모델 이름 확인 후 선택
available = [
    m.name for m in genai.list_models()
    if "generateContent" in m.supported_generation_methods
]
print("사용 가능한 모델:", available)

# gemini-2.0-flash가 있으면 쓰고, 없으면 첫 번째 모델 사용
target = "models/gemini-2.5-flash"
model_name = target if target in available else available[0]
print(f"선택된 모델: {model_name}")

gemini = genai.GenerativeModel(model_name)

'''
# 연결 테스트
try:
    test = gemini.generate_content("안녕")
    print("✅ Gemini 연결 성공")
except Exception as e:
    print(f"❌ Gemini 연결 실패: {e}")
 '''
# =========================================================
# CELL 4 — 데이터 로드 & 전처리
# =========================================================
# Kaggle 데이터셋 다운로드 (kaggle.json 업로드 후 실행)
# from google.colab import files
# files.upload()  # kaggle.json 선택
# import os
# os.makedirs('/root/.kaggle', exist_ok=True)
# !mv kaggle.json /root/.kaggle/
# !chmod 600 /root/.kaggle/kaggle.json
from google.colab import files
uploaded = files.upload()

# kaggle.json 업로드


# =========================
# 2. Kaggle API 설정
# =========================

import os

# kaggle 폴더 생성
os.makedirs('/root/.kaggle', exist_ok=True)

# kaggle.json 이동
!mv kaggle.json /root/.kaggle/

# 권한 설정
!chmod 600 /root/.kaggle/kaggle.json


# =========================
# 3. 데이터셋 다운로드
# =========================

!kaggle datasets download -d uom190346a/sleep-health-and-lifestyle-dataset


# =========================
# 4. 압축 해제
# =========================

!unzip sleep-health-and-lifestyle-dataset.zip
df = pd.read_csv('Sleep_health_and_lifestyle_dataset.csv')
print("원본 shape:", df.shape)

# 결측치 처리
df['Sleep Disorder'] = df['Sleep Disorder'].fillna('Normal')

# 혈압 분리
df[['Systolic_BP', 'Diastolic_BP']] = (
    df['Blood Pressure'].str.split('/', expand=True).astype(int)
)

# 성별 인코딩
df['Gender'] = df['Gender'].map({'Female': 0, 'Male': 1})

# BMI 서열 인코딩
bmi_map = {'Normal': 0, 'Normal Weight': 0, 'Overweight': 1, 'Obese': 2}
df['BMI Category'] = df['BMI Category'].map(bmi_map)

# 심박수 추정 (혈압 기반)
def estimate_heart_rate(sbp, dbp):
    return int(np.clip(0.25 * sbp + 0.35 * dbp + 25, 45, 120))

if 'Heart Rate' not in df.columns or df['Heart Rate'].isnull().any():
    df['Heart Rate'] = df.apply(
        lambda r: estimate_heart_rate(r['Systolic_BP'], r['Diastolic_BP']), axis=1
    )

print("✅ 전처리 완료")
print(df['Sleep Disorder'].value_counts())


# =========================================================
# CELL 5 — 모델 학습
# =========================================================
FEATURE_COLS = [
    'Gender', 'Age',
    'Quality of Sleep',
    'Stress Level',
    'BMI Category',
    'Heart Rate',
    'Daily Steps',
    'Systolic_BP',
    'Diastolic_BP',
]

X = df[FEATURE_COLS]
y = df['Sleep Disorder']

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42, stratify=y
)

# RandomForest (수면 장애 예측)
scaler = StandardScaler()
X_train_sc = scaler.fit_transform(X_train)
X_test_sc  = scaler.transform(X_test)

model = RandomForestClassifier(
    n_estimators=200, max_depth=6,
    class_weight='balanced', random_state=42
)
model.fit(X_train_sc, y_train)

y_pred = model.predict(X_test_sc)
print("\n📊 모델 성능")
print(classification_report(y_test, y_pred))
print(f"Macro F1: {f1_score(y_test, y_pred, average='macro'):.4f}")

# KNN (유사 건강 수면군 추천)
knn_scaler = StandardScaler()
knn_scaled = knn_scaler.fit_transform(df[FEATURE_COLS])
knn_model  = NearestNeighbors(n_neighbors=8, metric='euclidean')
knn_model.fit(knn_scaled)

print("✅ 모델 학습 완료")


# =========================================================
# CELL 6 — 설문 데이터 & 채점 함수
# =========================================================
SLEEP_QUESTIONS = [
    {
        "id": "SQ1", "question": "잠들기까지 얼마나 걸리나요?",
        "options": ["① 5분 이내", "② 6~15분", "③ 16~30분", "④ 30분 이상"],
        "weights": [4, 3, 2, 1],
    },
    {
        "id": "SQ2", "question": "밤 중에 깨는 빈도는?",
        "options": ["① 거의 없음", "② 주 1~2회", "③ 주 3~4회", "④ 매일 여러 번"],
        "weights": [4, 3, 2, 1],
    },
    {
        "id": "SQ3", "question": "아침에 일어났을 때 개운함은?",
        "options": ["① 매우 개운함", "② 보통", "③ 약간 피로함", "④ 매우 피로함"],
        "weights": [4, 3, 2, 1],
    },
    {
        "id": "SQ4", "question": "실제 수면 시간은?",
        "options": ["① 7~9시간", "② 6~7시간", "③ 5~6시간", "④ 5시간 미만"],
        "weights": [4, 3, 2, 1],
    },
    {
        "id": "SQ5", "question": "낮 동안 졸림이나 피로감은?",
        "options": ["① 거의 없음", "② 가끔", "③ 자주", "④ 항상"],
        "weights": [4, 3, 2, 1],
    },
]

STRESS_QUESTIONS = [
    {
        "id": "SS1", "question": "최근 해야 할 일이 너무 많다는 느낌은?",
        "options": ["① 거의 없음", "② 가끔", "③ 자주", "④ 항상"],
        "weights": [1, 3, 6, 9],
    },
    {
        "id": "SS2", "question": "몸이 긴장되거나 어깨·목이 뭉치는 느낌은?",
        "options": ["① 없음", "② 가끔", "③ 자주", "④ 항상"],
        "weights": [1, 3, 6, 9],
    },
    {
        "id": "SS3", "question": "일상을 스스로 통제하고 있다는 느낌은?",
        "options": ["① 충분히 통제됨", "② 대체로 통제됨", "③ 통제가 어려움", "④ 전혀 통제 안 됨"],
        "weights": [1, 3, 6, 9],
    },
    {
        "id": "SS4", "question": "두통·소화불량 등 스트레스성 신체 증상은?",
        "options": ["① 없음", "② 가끔", "③ 자주", "④ 항상"],
        "weights": [1, 3, 6, 9],
    },
    {
        "id": "SS5", "question": "퇴근·하교 후 심리적으로 회복되는 느낌은?",
        "options": ["① 충분히 회복됨", "② 어느 정도", "③ 잘 안 됨", "④ 전혀 안 됨"],
        "weights": [1, 3, 6, 9],
    },
]


def score_sleep_quality(answers: dict) -> int:
    total = sum(q["weights"][answers[q["id"]] - 1] for q in SLEEP_QUESTIONS)
    min_w = sum(min(q["weights"]) for q in SLEEP_QUESTIONS)
    max_w = sum(max(q["weights"]) for q in SLEEP_QUESTIONS)
    return int(round(np.clip(1 + 9 * (total - min_w) / (max_w - min_w), 1, 10)))


def score_stress(answers: dict) -> int:
    total = sum(q["weights"][answers[q["id"]] - 1] for q in STRESS_QUESTIONS)
    min_w = sum(min(q["weights"]) for q in STRESS_QUESTIONS)
    max_w = sum(max(q["weights"]) for q in STRESS_QUESTIONS)
    return int(round(np.clip(1 + 9 * (total - min_w) / (max_w - min_w), 1, 10)))


def collect_survey_cli(questions: list, category: str) -> dict:
    print(f"\n{'─'*55}")
    print(f"  📋 {category} 설문 (1~4 중 하나 입력)")
    print(f"{'─'*55}")
    answers = {}
    for q in questions:
        print(f"\n{q['id']}. {q['question']}")
        for opt in q['options']:
            print(f"     {opt}")
        while True:
            try:
                val = int(input("  → 입력 (1~4): ").strip())
                if 1 <= val <= 4:
                    answers[q['id']] = val
                    break
                print("  ⚠️  1~4 사이 숫자를 입력하세요.")
            except ValueError:
                print("  ⚠️  숫자만 입력하세요.")
    return answers


# =========================================================
# CELL 7 — 페르소나 매핑
# =========================================================
def assign_persona(disorder: str, stress: int, quality: int) -> dict:
    if disorder == 'Normal':
        if quality >= 7 and stress <= 4:
            return {
                "type": "🌙 Deep Rest (안정적 수면형)",
                "risk": "낮음",
                "desc": "부교감신경이 활성화된 심리적 안정 상태입니다. PSQI 기준 매우 우수한 수면 상태입니다.",
            }
        else:
            return {
                "type": "🏃 Recovery Booster (활동 회복형)",
                "risk": "낮음",
                "desc": "글림프 시스템을 통한 뇌 노폐물 제거가 진행 중인 상태입니다. 수면 질 7점 이상이 목표입니다.",
            }
    elif disorder == 'Insomnia':
        if stress >= 6:
            return {
                "type": "⚡ Stress Sleeper (스트레스 과부하형)",
                "risk": "높음",
                "desc": "코르티솔 과다 분비로 HPA축이 과활성화되어 멜라토닌 분비가 억제된 상태입니다.",
            }
        else:
            return {
                "type": "🔄 Irregular Rhythm (수면 리듬 불균형형)",
                "risk": "중간",
                "desc": "일주기리듬(Circadian Rhythm) 붕괴 상태로, 취침·기상 시각 고정이 최우선입니다.",
            }
    else:
        return {
            "type": "🫁 Apnea Risk (호흡 불안형)",
            "risk": "높음",
            "desc": "수면 중 기도 협착으로 반복적 호흡 정지가 발생, 산소포화도 저하가 심혈관계에 부담을 줍니다.",
        }


# =========================================================
# CELL 8 — KNN 목표 수치
# =========================================================
def get_knn_targets(user_raw: dict) -> dict:
    user_df = pd.DataFrame([user_raw])
    user_sc = knn_scaler.transform(user_df)
    _, indices = knn_model.kneighbors(user_sc)
    similar = df.iloc[indices[0]]
    good    = similar[similar['Quality of Sleep'] >= 7]
    ref     = good if len(good) >= 2 else similar
    return {
        "target_daily_steps":  int(ref['Daily Steps'].mean()),
        "target_stress_level": round(ref['Stress Level'].mean(), 1),
        "target_quality":      round(ref['Quality of Sleep'].mean(), 1),
    }


# =========================================================
# CELL 9 — Gemini 호출 함수들
# =========================================================
def gemini_medical_analysis(persona: dict, user_raw: dict, knn: dict) -> dict:
    """
    수면 유형 기반 의학 분석 + 오늘의 미션 생성
    반환: { medical_summary, mechanism, recommended_sleep_hours, missions, warning_signs }
    """
    prompt = f"""
당신은 수면의학 전문 AI 코치입니다.
아래 사용자 데이터를 보고 반드시 JSON 형식으로만 응답하세요.
마크다운 코드블록 없이 순수 JSON만 출력하세요.

[사용자 데이터]
- 수면 유형: {persona['type']}
- 수면 질 점수: {user_raw['Quality of Sleep']}/10
- 스트레스 점수: {user_raw['Stress Level']}/10
- 나이: {user_raw['Age']}세, 성별: {'남성' if user_raw['Gender'] == 1 else '여성'}
- BMI: {'정상' if user_raw['BMI Category'] == 0 else '과체중' if user_raw['BMI Category'] == 1 else '비만'}
- 심박수: {user_raw['Heart Rate']} bpm
- 혈압: {user_raw['Systolic_BP']}/{user_raw['Diastolic_BP']} mmHg
- 하루 걸음 수: {user_raw['Daily Steps']:,}보
- 유사 건강군 목표 걸음 수: {knn['target_daily_steps']:,}보

[응답 JSON 형식]
{{
  "medical_summary": "이 수면 유형의 핵심 의학적 의미 2~3문장 (호르몬, 신경계 포함)",
  "mechanism": "수면 장애 발생 생리적 메커니즘 1~2문장",
  "recommended_sleep_hours": "권장 수면 시간 (예: 7~8시간)",
  "missions": [
    "오늘 밤 바로 실천할 구체적 미션 1 (행동 + 이유 포함)",
    "오늘 밤 바로 실천할 구체적 미션 2",
    "오늘 밤 바로 실천할 구체적 미션 3"
  ],
  "warning_signs": "전문의 방문 기준 1~2문장"
}}
"""
    try:
        response = gemini.generate_content(prompt)
        text = response.text.strip().replace("```json", "").replace("```", "").strip()
        return json.loads(text)
    except Exception as e:
        print(f"⚠️ Gemini 호출 오류: {e}")
        return {
            "medical_summary": "분석 중 오류가 발생했습니다.",
            "mechanism": "",
            "recommended_sleep_hours": "7~8시간",
            "missions": [
                "취침 1시간 전 스마트폰 차단하기",
                "실내 온도 18~20°C로 낮추기",
                "4-7-8 호흡법으로 5분간 긴장 풀기",
            ],
            "warning_signs": "2주 이상 지속되면 수면 전문의 상담을 권장합니다.",
        }


def gemini_checkin_feedback(yesterday_sleep: int, mission_done: list, today_condition: int) -> str:
    """체크인 데이터 기반 다음날 아침 피드백 생성"""
    prompt = f"""
당신은 수면 코치입니다. 아래 체크인 데이터를 보고
격려와 다음 단계 조언을 2~3문장으로 한국어로 작성하세요.
마크다운 없이 일반 텍스트로만 응답하세요.

어제 수면 점수: {yesterday_sleep}/10
완료한 미션: {', '.join(mission_done) if mission_done else '없음'}
오늘 아침 컨디션: {today_condition}/10
"""
    try:
        response = gemini.generate_content(prompt)
        return response.text.strip()
    except Exception as e:
        print(f"⚠️ Gemini 호출 오류: {e}")
        return "꾸준한 실천이 수면 질 개선의 핵심입니다. 오늘도 화이팅!"


# =========================================================
# CELL 10 — 전체 분석 함수
# =========================================================
def total_sleep_analysis(user_raw: dict) -> dict:
    # RF 예측
    user_df  = pd.DataFrame([user_raw])
    user_sc  = scaler.transform(user_df)
    disorder = model.predict(user_sc)[0]
    proba    = model.predict_proba(user_sc)[0]
    proba_dict = {c: f"{round(p*100, 1)}%" for c, p in zip(model.classes_, proba)}

    # 페르소나, KNN
    sleep_score  = user_raw['Quality of Sleep']
    stress_score = user_raw['Stress Level']
    persona      = assign_persona(disorder, stress_score, sleep_score)
    knn          = get_knn_targets(user_raw)

    # Gemini 의학 분석
    print("\n🤖 Gemini 분석 중...")
    gemini_data = gemini_medical_analysis(persona, user_raw, knn)

    return {
        "disorder":    disorder,
        "proba":       proba_dict,
        "persona":     persona,
        "knn":         knn,
        "gemini":      gemini_data,
    }


# =========================================================
# CELL 11 — 설문 + 분석 실행 함수
# =========================================================
def run_full_analysis():
    print("\n" + "=" * 55)
    print("🛌 수면 건강 종합 분석")
    print("=" * 55)

    # 수면 질 설문
    sleep_answers = collect_survey_cli(SLEEP_QUESTIONS, "수면 질")
    sleep_score, = score_sleep_quality(sleep_answers),
    sleep_score   = sleep_score[0] if isinstance(sleep_score, tuple) else sleep_score
    sleep_score   = score_sleep_quality(sleep_answers)

    # 스트레스 설문
    stress_answers = collect_survey_cli(STRESS_QUESTIONS, "스트레스")
    stress_score   = score_stress(stress_answers)

    print(f"\n  ✅ 수면 질 점수  : {sleep_score}/10")
    print(f"  ✅ 스트레스 점수 : {stress_score}/10")

    # 기본 정보 입력
    print("\n" + "─" * 55)
    print("  📝 기본 정보 입력")
    print("─" * 55)
    gender  = int(input("성별 (0=여성, 1=남성): ").strip())
    age     = int(input("나이: ").strip())
    print("BMI:  0=정상  1=과체중  2=비만")
    bmi_cat = int(input("BMI (0/1/2): ").strip())
    steps   = int(input("하루 평균 걸음 수 (예: 7000): ").strip())
    sbp     = int(input("수축기 혈압 (예: 120): ").strip())
    dbp     = int(input("이완기 혈압 (예: 80): ").strip())
    hr      = estimate_heart_rate(sbp, dbp)
    print(f"\n  💓 심박수 자동 추정: {hr} bpm")

    user_raw = {
        'Gender':           gender,
        'Age':              age,
        'Quality of Sleep': sleep_score,
        'Stress Level':     stress_score,
        'BMI Category':     bmi_cat,
        'Heart Rate':       hr,
        'Daily Steps':      steps,
        'Systolic_BP':      sbp,
        'Diastolic_BP':     dbp,
    }

    result  = total_sleep_analysis(user_raw)
    persona = result['persona']
    knn     = result['knn']
    gd      = result['gemini']

    print("\n" + "=" * 55)
    print("📋 분석 결과")
    print("=" * 55)
    print(f"\n  🩺 예측 수면 장애 : {result['disorder']}")
    print(f"  📊 확률 분포      : {result['proba']}")
    print(f"\n  👤 페르소나  : {persona['type']}")
    print(f"  ⚠️  리스크    : {persona['risk']}")
    print(f"  📖 설명      : {persona['desc']}")

    print(f"\n  🔬 [Gemini] 의학적 분석")
    print(f"     {gd['medical_summary']}")
    if gd.get('mechanism'):
        print(f"\n  ⚙️  메커니즘: {gd['mechanism']}")
    print(f"\n  ⏰ 권장 수면 시간: {gd['recommended_sleep_hours']}")

    print(f"\n  ✅ 오늘의 미션:")
    for i, m in enumerate(gd.get('missions', []), 1):
        print(f"     {i}. {m}")

    print(f"\n  ⚠️  전문의 상담 기준: {gd.get('warning_signs', '')}")

    print(f"\n  🎯 KNN 유사 건강 수면군 목표:")
    print(f"     걸음 수  : {knn['target_daily_steps']:,}보")
    print(f"     스트레스 : {knn['target_stress_level']}/10")
    print(f"     수면 질  : {knn['target_quality']}/10")

    return result, user_raw


# =========================================================
# CELL 12 — 체크인 함수 (다음날 아침 실행)
# =========================================================
def run_checkin(yesterday_sleep_score: int, missions: list):
    print("\n" + "=" * 55)
    print("☀️ 오늘 아침 체크인")
    print("=" * 55)

    print("\n어제 미션 중 완료한 항목 번호를 입력하세요 (예: 1 3)")
    for i, m in enumerate(missions, 1):
        print(f"  {i}. {m}")

    done_idx  = input("완료 번호 (없으면 엔터): ").strip().split()
    done_idx  = [int(x)-1 for x in done_idx if x.isdigit()]
    done_list = [missions[i] for i in done_idx if 0 <= i < len(missions)]

    today_score = int(input("\n오늘 아침 컨디션 점수 (1~10): ").strip())

    print("\n🤖 Gemini 피드백 생성 중...")
    feedback = gemini_checkin_feedback(yesterday_sleep_score, done_list, today_score)

    print("\n" + "─" * 55)
    print("💬 Gemini 코치 피드백")
    print("─" * 55)
    print(feedback)

    return {"done": done_list, "today_score": today_score, "feedback": feedback}


# =========================================================
# CELL 13 — 빠른 테스트 (고정값, 설문 없음)
# =========================================================
'''
def quick_test():
    print("\n" + "=" * 55)
    print("🧪 빠른 검증 테스트 (Gemini 연동 확인)")
    print("=" * 55)

    mock_sleep  = {"SQ1": 3, "SQ2": 3, "SQ3": 3, "SQ4": 2, "SQ5": 3}
    mock_stress = {"SS1": 4, "SS2": 3, "SS3": 3, "SS4": 3, "SS5": 3}

    sleep_score  = score_sleep_quality(mock_sleep)
    stress_score = score_stress(mock_stress)
    sbp, dbp     = 130, 85
    hr           = estimate_heart_rate(sbp, dbp)

    user_raw = {
        'Gender': 0, 'Age': 32,
        'Quality of Sleep': sleep_score,
        'Stress Level':     stress_score,
        'BMI Category':     1,
        'Heart Rate':       hr,
        'Daily Steps':      4500,
        'Systolic_BP':      sbp,
        'Diastolic_BP':     dbp,
    }

    result  = total_sleep_analysis(user_raw)
    persona = result['persona']
    gd      = result['gemini']

    print(f"\n  수면 질 채점  : {sleep_score}/10")
    print(f"  스트레스 채점 : {stress_score}/10")
    print(f"  심박수 추정   : {hr} bpm")
    print(f"  예측 수면 장애 : {result['disorder']}")
    print(f"  확률           : {result['proba']}")
    print(f"  페르소나       : {persona['type']}")

    print(f"\n  [Gemini] 의학 분석:")
    print(f"  {gd['medical_summary']}")
    print(f"\n  [Gemini] 권장 수면: {gd['recommended_sleep_hours']}")
    print(f"\n  [Gemini] 오늘의 미션:")
    for i, m in enumerate(gd.get('missions', []), 1):
        print(f"    {i}. {m}")
    print(f"\n  [Gemini] 전문의 기준: {gd.get('warning_signs', '')}")

    return result
    '''


# =========================================================
# CELL 14 — 실행
# =========================================================

# 빠른 테스트 (Gemini 연동 확인)
#result = quick_test()

# 실제 설문 분석 실행 (주석 해제 후 사용)
result, user_raw = run_full_analysis()

#체크인 실행 (run_full_analysis 다음날 아침에 실행)
missions = result['gemini']['missions']
sleep_score = user_raw['Quality of Sleep']  # run_full_analysis 사용 시
checkin = run_checkin(sleep_score, missions)

"""# **직접+모델**"""

# =========================================================
# 수면 코치 서비스 — 코랩 단일 파일 (Gemini API 연동)
#
# 설치: !pip install -q google-generativeai shap
# Gemini API 키: https://aistudio.google.com (무료)
# =========================================================


# =========================================================
# CELL 1 — 패키지 설치
# =========================================================
# !pip install -q google-generativeai shap scikit-learn pandas numpy joblib


# =========================================================
# CELL 2 — 라이브러리 임포트
# =========================================================
import pandas as pd
import numpy as np
import json
from google import genai
import os
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.ensemble import RandomForestClassifier
from sklearn.neighbors import NearestNeighbors
from sklearn.metrics import classification_report, f1_score


print("✅ 라이브러리 로드 완료")


# =========================================================
# =========================================================
# CELL 3 — Gemini API 초기화 (직접 입력 버전)
# =========================================================
!pip install -q -U google-genai

from google import genai

# ↓ 여기에 본인 API 키 직접 입력
GEMINI_API_KEY = "AIzaSyDgjWuwPUOsbFErTtoOvx7liJ1NuoMia3Q"

client = genai.Client(api_key=GEMINI_API_KEY)
MODEL_NAME = "gemini-2.5-flash"

print(f"✅ Gemini 초기화 완료 (모델: {MODEL_NAME})")
# =========================================================
# CELL 4 — 데이터 로드 & 전처리
# =========================================================
# Kaggle 데이터셋 다운로드 (kaggle.json 업로드 후 실행)
# from google.colab import files
# files.upload()  # kaggle.json 선택
# import os
# os.makedirs('/root/.kaggle', exist_ok=True)
# !mv kaggle.json /root/.kaggle/
# !chmod 600 /root/.kaggle/kaggle.json
from google.colab import files
uploaded = files.upload()

# kaggle.json 업로드


# =========================
# 2. Kaggle API 설정
# =========================

import os

# kaggle 폴더 생성
os.makedirs('/root/.kaggle', exist_ok=True)

# kaggle.json 이동
!mv kaggle.json /root/.kaggle/

# 권한 설정
!chmod 600 /root/.kaggle/kaggle.json


# =========================
# 3. 데이터셋 다운로드
# =========================

!kaggle datasets download -d uom190346a/sleep-health-and-lifestyle-dataset


# =========================
# 4. 압축 해제
# =========================

!unzip sleep-health-and-lifestyle-dataset.zip
df = pd.read_csv('Sleep_health_and_lifestyle_dataset.csv')
print("원본 shape:", df.shape)

# 결측치 처리
df['Sleep Disorder'] = df['Sleep Disorder'].fillna('Normal')

# 혈압 분리
df[['Systolic_BP', 'Diastolic_BP']] = (
    df['Blood Pressure'].str.split('/', expand=True).astype(int)
)

# 성별 인코딩
df['Gender'] = df['Gender'].map({'Female': 0, 'Male': 1})

# BMI 서열 인코딩
bmi_map = {'Normal': 0, 'Normal Weight': 0, 'Overweight': 1, 'Obese': 2}
df['BMI Category'] = df['BMI Category'].map(bmi_map)

# 심박수 추정 (혈압 기반)
def estimate_heart_rate(sbp, dbp):
    return int(np.clip(0.25 * sbp + 0.35 * dbp + 25, 45, 120))

if 'Heart Rate' not in df.columns or df['Heart Rate'].isnull().any():
    df['Heart Rate'] = df.apply(
        lambda r: estimate_heart_rate(r['Systolic_BP'], r['Diastolic_BP']), axis=1
    )

print("✅ 전처리 완료")
print(df['Sleep Disorder'].value_counts())


# =========================================================
# CELL 5 — 모델 학습
# =========================================================
FEATURE_COLS = [
    'Gender', 'Age',
    'Quality of Sleep',
    'Stress Level',
    'BMI Category',
    'Heart Rate',
    'Daily Steps',
    'Systolic_BP',
    'Diastolic_BP',
]

X = df[FEATURE_COLS]
y = df['Sleep Disorder']

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42, stratify=y
)

# RandomForest (수면 장애 예측)
scaler = StandardScaler()
X_train_sc = scaler.fit_transform(X_train)
X_test_sc  = scaler.transform(X_test)

model = RandomForestClassifier(
    n_estimators=200, max_depth=6,
    class_weight='balanced', random_state=42
)
model.fit(X_train_sc, y_train)

y_pred = model.predict(X_test_sc)
print("\n📊 모델 성능")
print(classification_report(y_test, y_pred))
print(f"Macro F1: {f1_score(y_test, y_pred, average='macro'):.4f}")

# KNN (유사 건강 수면군 추천)
knn_scaler = StandardScaler()
knn_scaled = knn_scaler.fit_transform(df[FEATURE_COLS])
knn_model  = NearestNeighbors(n_neighbors=8, metric='euclidean')
knn_model.fit(knn_scaled)

print("✅ 모델 학습 완료")


# =========================================================
# CELL 6 — 설문 데이터 & 채점 함수
# =========================================================
SLEEP_QUESTIONS = [
    {
        "id": "SQ1", "question": "잠들기까지 얼마나 걸리나요?",
        "options": ["① 5분 이내", "② 6~15분", "③ 16~30분", "④ 30분 이상"],
        "weights": [4, 3, 2, 1],
    },
    {
        "id": "SQ2", "question": "밤 중에 깨는 빈도는?",
        "options": ["① 거의 없음", "② 주 1~2회", "③ 주 3~4회", "④ 매일 여러 번"],
        "weights": [4, 3, 2, 1],
    },
    {
        "id": "SQ3", "question": "아침에 일어났을 때 개운함은?",
        "options": ["① 매우 개운함", "② 보통", "③ 약간 피로함", "④ 매우 피로함"],
        "weights": [4, 3, 2, 1],
    },
    {
        "id": "SQ4", "question": "실제 수면 시간은?",
        "options": ["① 7~9시간", "② 6~7시간", "③ 5~6시간", "④ 5시간 미만"],
        "weights": [4, 3, 2, 1],
    },
    {
        "id": "SQ5", "question": "낮 동안 졸림이나 피로감은?",
        "options": ["① 거의 없음", "② 가끔", "③ 자주", "④ 항상"],
        "weights": [4, 3, 2, 1],
    },
]

STRESS_QUESTIONS = [
    {
        "id": "SS1", "question": "최근 해야 할 일이 너무 많다는 느낌은?",
        "options": ["① 거의 없음", "② 가끔", "③ 자주", "④ 항상"],
        "weights": [1, 3, 6, 9],
    },
    {
        "id": "SS2", "question": "몸이 긴장되거나 어깨·목이 뭉치는 느낌은?",
        "options": ["① 없음", "② 가끔", "③ 자주", "④ 항상"],
        "weights": [1, 3, 6, 9],
    },
    {
        "id": "SS3", "question": "일상을 스스로 통제하고 있다는 느낌은?",
        "options": ["① 충분히 통제됨", "② 대체로 통제됨", "③ 통제가 어려움", "④ 전혀 통제 안 됨"],
        "weights": [1, 3, 6, 9],
    },
    {
        "id": "SS4", "question": "두통·소화불량 등 스트레스성 신체 증상은?",
        "options": ["① 없음", "② 가끔", "③ 자주", "④ 항상"],
        "weights": [1, 3, 6, 9],
    },
    {
        "id": "SS5", "question": "퇴근·하교 후 심리적으로 회복되는 느낌은?",
        "options": ["① 충분히 회복됨", "② 어느 정도", "③ 잘 안 됨", "④ 전혀 안 됨"],
        "weights": [1, 3, 6, 9],
    },
]


def score_sleep_quality(answers: dict) -> int:
    total = sum(q["weights"][answers[q["id"]] - 1] for q in SLEEP_QUESTIONS)
    min_w = sum(min(q["weights"]) for q in SLEEP_QUESTIONS)
    max_w = sum(max(q["weights"]) for q in SLEEP_QUESTIONS)
    return int(round(np.clip(1 + 9 * (total - min_w) / (max_w - min_w), 1, 10)))


def score_stress(answers: dict) -> int:
    total = sum(q["weights"][answers[q["id"]] - 1] for q in STRESS_QUESTIONS)
    min_w = sum(min(q["weights"]) for q in STRESS_QUESTIONS)
    max_w = sum(max(q["weights"]) for q in STRESS_QUESTIONS)
    return int(round(np.clip(1 + 9 * (total - min_w) / (max_w - min_w), 1, 10)))


def collect_survey_cli(questions: list, category: str) -> dict:
    print(f"\n{'─'*55}")
    print(f"  📋 {category} 설문 (1~4 중 하나 입력)")
    print(f"{'─'*55}")
    answers = {}
    for q in questions:
        print(f"\n{q['id']}. {q['question']}")
        for opt in q['options']:
            print(f"     {opt}")
        while True:
            try:
                val = int(input("  → 입력 (1~4): ").strip())
                if 1 <= val <= 4:
                    answers[q['id']] = val
                    break
                print("  ⚠️  1~4 사이 숫자를 입력하세요.")
            except ValueError:
                print("  ⚠️  숫자만 입력하세요.")
    return answers


# =========================================================
# CELL 7 — 페르소나 매핑
# =========================================================
def assign_persona(disorder: str, stress: int, quality: int) -> dict:
    if disorder == 'Normal':
        if quality >= 7 and stress <= 4:
            return {
                "type": "🌙 Deep Rest (안정적 수면형)",
                "risk": "낮음",
                "desc": "부교감신경이 활성화된 심리적 안정 상태입니다. PSQI 기준 매우 우수한 수면 상태입니다.",
            }
        else:
            return {
                "type": "🏃 Recovery Booster (활동 회복형)",
                "risk": "낮음",
                "desc": "글림프 시스템을 통한 뇌 노폐물 제거가 진행 중인 상태입니다. 수면 질 7점 이상이 목표입니다.",
            }
    elif disorder == 'Insomnia':
        if stress >= 6:
            return {
                "type": "⚡ Stress Sleeper (스트레스 과부하형)",
                "risk": "높음",
                "desc": "코르티솔 과다 분비로 HPA축이 과활성화되어 멜라토닌 분비가 억제된 상태입니다.",
            }
        else:
            return {
                "type": "🔄 Irregular Rhythm (수면 리듬 불균형형)",
                "risk": "중간",
                "desc": "일주기리듬(Circadian Rhythm) 붕괴 상태로, 취침·기상 시각 고정이 최우선입니다.",
            }
    else:
        return {
            "type": "🫁 Apnea Risk (호흡 불안형)",
            "risk": "높음",
            "desc": "수면 중 기도 협착으로 반복적 호흡 정지가 발생, 산소포화도 저하가 심혈관계에 부담을 줍니다.",
        }


# =========================================================
# CELL 8 — KNN 목표 수치
# =========================================================
def get_knn_targets(user_raw: dict) -> dict:
    user_df = pd.DataFrame([user_raw])
    user_sc = knn_scaler.transform(user_df)
    _, indices = knn_model.kneighbors(user_sc)
    similar = df.iloc[indices[0]]
    good    = similar[similar['Quality of Sleep'] >= 7]
    ref     = good if len(good) >= 2 else similar
    return {
        "target_daily_steps":  int(ref['Daily Steps'].mean()),
        "target_stress_level": round(ref['Stress Level'].mean(), 1),
        "target_quality":      round(ref['Quality of Sleep'].mean(), 1),
    }


# =========================================================
# CELL 9 — Gemini 호출 함수들
# =========================================================
def gemini_medical_analysis(persona: dict, user_raw: dict, knn: dict) -> dict:
    """
    수면 유형 기반 의학 분석 + 오늘의 미션 생성
    반환: { medical_summary, mechanism, recommended_sleep_hours, missions, warning_signs }
    """
    prompt = f"""
당신은 수면의학 전문 AI 코치입니다.
아래 사용자 데이터를 보고 반드시 JSON 형식으로만 응답하세요.
마크다운 코드블록 없이 순수 JSON만 출력하세요.

[사용자 데이터]
- 수면 유형: {persona['type']}
- 수면 질 점수: {user_raw['Quality of Sleep']}/10
- 스트레스 점수: {user_raw['Stress Level']}/10
- 나이: {user_raw['Age']}세, 성별: {'남성' if user_raw['Gender'] == 1 else '여성'}
- BMI: {'정상' if user_raw['BMI Category'] == 0 else '과체중' if user_raw['BMI Category'] == 1 else '비만'}
- 심박수: {user_raw['Heart Rate']} bpm
- 혈압: {user_raw['Systolic_BP']}/{user_raw['Diastolic_BP']} mmHg
- 하루 걸음 수: {user_raw['Daily Steps']:,}보
- 유사 건강군 목표 걸음 수: {knn['target_daily_steps']:,}보

[응답 JSON 형식]
{{
  "medical_summary": "이 수면 유형의 핵심 의학적 의미 2~3문장 (호르몬, 신경계 포함)",
  "mechanism": "수면 장애 발생 생리적 메커니즘 1~2문장",
  "recommended_sleep_hours": "권장 수면 시간 (예: 7~8시간)",
  "missions": [
    "오늘 밤 바로 실천할 구체적 미션 1 (행동 + 이유 포함)",
    "오늘 밤 바로 실천할 구체적 미션 2",
    "오늘 밤 바로 실천할 구체적 미션 3"
  ],
  "warning_signs": "전문의 방문 기준 1~2문장"
}}
"""
    try:
        response = client.models.generate_content(
            model=MODEL_NAME,
            contents=prompt
            )
        text = response.text.strip().replace("```json", "").replace("```", "").strip()
        return json.loads(text)
    except Exception as e:
        print(f"⚠️ Gemini 호출 오류: {e}")
        return {
            "medical_summary": "분석 중 오류가 발생했습니다.",
            "mechanism": "",
            "recommended_sleep_hours": "7~8시간",
            "missions": [
                "취침 1시간 전 스마트폰 차단하기",
                "실내 온도 18~20°C로 낮추기",
                "4-7-8 호흡법으로 5분간 긴장 풀기",
            ],
            "warning_signs": "2주 이상 지속되면 수면 전문의 상담을 권장합니다.",
        }


def gemini_checkin_feedback(yesterday_sleep: int, mission_done: list, today_condition: int) -> str:
    """체크인 데이터 기반 다음날 아침 피드백 생성"""
    prompt = f"""
당신은 수면 코치입니다. 아래 체크인 데이터를 보고
격려와 다음 단계 조언을 2~3문장으로 한국어로 작성하세요.
마크다운 없이 일반 텍스트로만 응답하세요.

어제 수면 점수: {yesterday_sleep}/10
완료한 미션: {', '.join(mission_done) if mission_done else '없음'}
오늘 아침 컨디션: {today_condition}/10
"""
    try:
        response = gemini.generate_content(prompt)
        return response.text.strip()
    except Exception as e:
        print(f"⚠️ Gemini 호출 오류: {e}")
        return "꾸준한 실천이 수면 질 개선의 핵심입니다. 오늘도 화이팅!"


# =========================================================
# CELL 10 — 전체 분석 함수
# =========================================================
def total_sleep_analysis(user_raw: dict) -> dict:
    # RF 예측
    user_df  = pd.DataFrame([user_raw])
    user_sc  = scaler.transform(user_df)
    disorder = model.predict(user_sc)[0]
    proba    = model.predict_proba(user_sc)[0]
    proba_dict = {c: f"{round(p*100, 1)}%" for c, p in zip(model.classes_, proba)}

    # 페르소나, KNN
    sleep_score  = user_raw['Quality of Sleep']
    stress_score = user_raw['Stress Level']
    persona      = assign_persona(disorder, stress_score, sleep_score)
    knn          = get_knn_targets(user_raw)

    # Gemini 의학 분석
    print("\n🤖 Gemini 분석 중...")
    gemini_data = gemini_medical_analysis(persona, user_raw, knn)

    return {
        "disorder":    disorder,
        "proba":       proba_dict,
        "persona":     persona,
        "knn":         knn,
        "gemini":      gemini_data,
    }


# =========================================================
# CELL 11 — 설문 + 분석 실행 함수
# =========================================================
def run_full_analysis():
    print("\n" + "=" * 55)
    print("🛌 수면 건강 종합 분석")
    print("=" * 55)

    # 수면 질 설문
    sleep_answers = collect_survey_cli(SLEEP_QUESTIONS, "수면 질")
    sleep_score, = score_sleep_quality(sleep_answers),
    sleep_score   = sleep_score[0] if isinstance(sleep_score, tuple) else sleep_score
    sleep_score   = score_sleep_quality(sleep_answers)

    # 스트레스 설문
    stress_answers = collect_survey_cli(STRESS_QUESTIONS, "스트레스")
    stress_score   = score_stress(stress_answers)

    print(f"\n  ✅ 수면 질 점수  : {sleep_score}/10")
    print(f"  ✅ 스트레스 점수 : {stress_score}/10")

    # 기본 정보 입력
    print("\n" + "─" * 55)
    print("  📝 기본 정보 입력")
    print("─" * 55)
    gender  = int(input("성별 (0=여성, 1=남성): ").strip())
    age     = int(input("나이: ").strip())
    print("BMI:  0=정상  1=과체중  2=비만")
    bmi_cat = int(input("BMI (0/1/2): ").strip())
    steps   = int(input("하루 평균 걸음 수 (예: 7000): ").strip())
    sbp     = int(input("수축기 혈압 (예: 120): ").strip())
    dbp     = int(input("이완기 혈압 (예: 80): ").strip())
    hr      = estimate_heart_rate(sbp, dbp)
    print(f"\n  💓 심박수 자동 추정: {hr} bpm")

    user_raw = {
        'Gender':           gender,
        'Age':              age,
        'Quality of Sleep': sleep_score,
        'Stress Level':     stress_score,
        'BMI Category':     bmi_cat,
        'Heart Rate':       hr,
        'Daily Steps':      steps,
        'Systolic_BP':      sbp,
        'Diastolic_BP':     dbp,
    }

    result  = total_sleep_analysis(user_raw)
    persona = result['persona']
    knn     = result['knn']
    gd      = result['gemini']

    print("\n" + "=" * 55)
    print("📋 분석 결과")
    print("=" * 55)
    print(f"\n  🩺 예측 수면 장애 : {result['disorder']}")
    print(f"  📊 확률 분포      : {result['proba']}")
    print(f"\n  👤 페르소나  : {persona['type']}")
    print(f"  ⚠️  리스크    : {persona['risk']}")
    print(f"  📖 설명      : {persona['desc']}")

    print(f"\n  🔬 [Gemini] 의학적 분석")
    print(f"     {gd['medical_summary']}")
    if gd.get('mechanism'):
        print(f"\n  ⚙️  메커니즘: {gd['mechanism']}")
    print(f"\n  ⏰ 권장 수면 시간: {gd['recommended_sleep_hours']}")

    print(f"\n  ✅ 오늘의 미션:")
    for i, m in enumerate(gd.get('missions', []), 1):
        print(f"     {i}. {m}")

    print(f"\n  ⚠️  전문의 상담 기준: {gd.get('warning_signs', '')}")

    print(f"\n  🎯 KNN 유사 건강 수면군 목표:")
    print(f"     걸음 수  : {knn['target_daily_steps']:,}보")
    print(f"     스트레스 : {knn['target_stress_level']}/10")
    print(f"     수면 질  : {knn['target_quality']}/10")

    return result, user_raw


# =========================================================
# CELL 12 — 체크인 함수 (다음날 아침 실행)
# =========================================================
def run_checkin(yesterday_sleep_score: int, missions: list):
    print("\n" + "=" * 55)
    print("☀️ 오늘 아침 체크인")
    print("=" * 55)

    print("\n어제 미션 중 완료한 항목 번호를 입력하세요 (예: 1 3)")
    for i, m in enumerate(missions, 1):
        print(f"  {i}. {m}")

    done_idx  = input("완료 번호 (없으면 엔터): ").strip().split()
    done_idx  = [int(x)-1 for x in done_idx if x.isdigit()]
    done_list = [missions[i] for i in done_idx if 0 <= i < len(missions)]

    today_score = int(input("\n오늘 아침 컨디션 점수 (1~10): ").strip())

    print("\n🤖 Gemini 피드백 생성 중...")
    feedback = gemini_checkin_feedback(yesterday_sleep_score, done_list, today_score)

    print("\n" + "─" * 55)
    print("💬 Gemini 코치 피드백")
    print("─" * 55)
    print(feedback)

    return {"done": done_list, "today_score": today_score, "feedback": feedback}


# =========================================================
# CELL 13 — 빠른 테스트 (고정값, 설문 없음)
# =========================================================
'''
def quick_test():
    print("\n" + "=" * 55)
    print("🧪 빠른 검증 테스트 (Gemini 연동 확인)")
    print("=" * 55)

    mock_sleep  = {"SQ1": 3, "SQ2": 3, "SQ3": 3, "SQ4": 2, "SQ5": 3}
    mock_stress = {"SS1": 4, "SS2": 3, "SS3": 3, "SS4": 3, "SS5": 3}

    sleep_score  = score_sleep_quality(mock_sleep)
    stress_score = score_stress(mock_stress)
    sbp, dbp     = 130, 85
    hr           = estimate_heart_rate(sbp, dbp)

    user_raw = {
        'Gender': 0, 'Age': 32,
        'Quality of Sleep': sleep_score,
        'Stress Level':     stress_score,
        'BMI Category':     1,
        'Heart Rate':       hr,
        'Daily Steps':      4500,
        'Systolic_BP':      sbp,
        'Diastolic_BP':     dbp,
    }

    result  = total_sleep_analysis(user_raw)
    persona = result['persona']
    gd      = result['gemini']

    print(f"\n  수면 질 채점  : {sleep_score}/10")
    print(f"  스트레스 채점 : {stress_score}/10")
    print(f"  심박수 추정   : {hr} bpm")
    print(f"  예측 수면 장애 : {result['disorder']}")
    print(f"  확률           : {result['proba']}")
    print(f"  페르소나       : {persona['type']}")

    print(f"\n  [Gemini] 의학 분석:")
    print(f"  {gd['medical_summary']}")
    print(f"\n  [Gemini] 권장 수면: {gd['recommended_sleep_hours']}")
    print(f"\n  [Gemini] 오늘의 미션:")
    for i, m in enumerate(gd.get('missions', []), 1):
        print(f"    {i}. {m}")
    print(f"\n  [Gemini] 전문의 기준: {gd.get('warning_signs', '')}")

    return result
    '''


# =========================================================
# CELL 14 — 실행
# =========================================================

# 빠른 테스트 (Gemini 연동 확인)
#result = quick_test()

# 실제 설문 분석 실행 (주석 해제 후 사용)
result, user_raw = run_full_analysis()

#체크인 실행 (run_full_analysis 다음날 아침에 실행)
missions = result['gemini']['missions']
sleep_score = user_raw['Quality of Sleep']  # run_full_analysis 사용 시
checkin = run_checkin(sleep_score, missions)

"""#**시크릿 연결 성공 여부 확인 코드**

"""

!pip install -q -U google-genai

from google import genai  # ← 이게 올바른 임포트 (google as genai 아님)
from google.colab import userdata

# 변수 초기화
client = None
GEMINI_API_KEY = None

try:
    GEMINI_API_KEY = userdata.get("GEMINI_API_KEY")
    client = genai.Client(api_key=GEMINI_API_KEY)  # api_key가 아니라 GEMINI_API_KEY
    print("✅ API 키 로드 성공")
except Exception as e:
    print(f"❌ 키 로드 실패: {e}")

# client가 실제로 이번 셀에서 만들어진 경우에만 테스트
if client:
    try:
        response = client.models.generate_content(
            model='gemini-2.5-flash',  # 2.5-flash는 불안정할 수 있음
            contents='안녕 연결 확인용 텍스트야.'
        )
        print(f"✅ Gemini 연결 성공!")
        print(f"🤖 응답: {response.text.strip()}")
    except Exception as e:
        print(f"❌ Gemini 연결 실패: {e}")
else:
    print("⛔ client가 없어서 연결 테스트를 건너뜁니다.")

"""# **API KEY 직접 입력 성공 여부 확인 코드**"""

!pip install -q -U google-genai

from google import genai

# 변수 초기화
client = None
GEMINI_API_KEY = "AIzaSyDgjWuwPUOsbFErTtoOvx7liJ1NuoMia3Q"  # ← 직접 입력

try:
    client = genai.Client(api_key=GEMINI_API_KEY)
    print("✅ API 키 로드 성공")
except Exception as e:
    print(f"❌ 키 로드 실패: {e}")

if client:
    try:
        response = client.models.generate_content(
            model='gemini-2.5-flash',
            contents='안녕 연결 확인용 텍스트야.'
        )
        print(f"✅ Gemini 연결 성공!")
        print(f"🤖 응답: {response.text.strip()}")
    except Exception as e:
        print(f"❌ Gemini 연결 실패: {e}")
else:
    print("⛔ client가 없어서 연결 테스트를 건너뜁니다.")

"""# **모든 항목 직접 입력할 수 있는 모델인데 mbti식이 없고 체크인 방식 없음 (시크릿)**

그리고 코드 여기 고쳐야할 듯 여유있는 걸로 가게 gemini 모델
"""

import google.generativeai as genai
from google.colab import userdata

# ── 0. API 키 설정 ──────────────────────────────────────────────
api_key = userdata.get('GAPIKey')
genai.configure(api_key=api_key)


# ── 1. 데이터 입력 함수 ─────────────────────────────────────────
def input_patient_data():
    print("=" * 55)
    print("   수면장애 환자 데이터 입력 시스템")
    print("=" * 55)
    print("※ 각 항목을 입력 후 Enter를 누르세요.")
    print("※ 모르는 항목은 Enter를 눌러 건너뛸 수 있습니다.\n")

    data = {}

    # ── 기본 정보 ──
    print("[ 기본 정보 ]")
    data['age']    = input("  연령 (예: 38): ").strip() or "미입력"
    gender_input   = input("  성별 (1=남성, 2=여성, 3=기타): ").strip()
    data['gender'] = {"1": "남성", "2": "여성", "3": "기타"}.get(gender_input, "미입력")
    job_map = {"1": "사무직", "2": "교대 근무직", "3": "자유직/재택", "4": "학생", "5": "기타"}
    job_input      = input("  직업 (1=사무직, 2=교대근무, 3=자유직/재택, 4=학생, 5=기타): ").strip()
    data['job']    = job_map.get(job_input, "미입력")

    # ── 수면 패턴 ──
    print("\n[ 수면 패턴 ]")
    data['bedtime']      = input("  취침 시간 (예: 23:30): ").strip() or "미입력"
    data['waketime']     = input("  기상 시간 (예: 07:00): ").strip() or "미입력"
    data['sleep_onset']  = input("  입면 소요 시간 (분, 예: 60): ").strip() or "미입력"
    data['wakeup_count'] = input("  야간 각성 횟수 (회, 예: 2): ").strip() or "미입력"
    quality_map = {"1": "매우 나쁨", "2": "나쁨", "3": "보통", "4": "좋음", "5": "매우 좋음"}
    quality_input        = input("  수면의 질 (1=매우나쁨 ~ 5=매우좋음): ").strip()
    data['sleep_quality'] = quality_map.get(quality_input, "미입력")

    # ── 생활 습관 ──
    print("\n[ 생활 습관 ]")
    data['caffeine_cups']  = input("  일일 카페인 섭취량 (잔, 예: 2): ").strip() or "0"
    data['caffeine_time']  = input("  마지막 카페인 섭취 시간 (예: 15:00): ").strip() or "미입력"
    alcohol_map = {"1": "없음", "2": "주 1~2회", "3": "주 3~4회", "4": "매일"}
    alcohol_input          = input("  알코올 섭취 빈도 (1=없음, 2=주1~2회, 3=주3~4회, 4=매일): ").strip()
    data['alcohol']        = alcohol_map.get(alcohol_input, "미입력")
    data['phone_minutes']  = input("  취침 전 스마트폰 사용 시간 (분, 예: 40): ").strip() or "미입력"
    exercise_map = {"1": "없음", "2": "주 1~2회", "3": "주 3~4회", "4": "매일"}
    exercise_input         = input("  운동 빈도 (1=없음, 2=주1~2회, 3=주3~4회, 4=매일): ").strip()
    data['exercise']       = exercise_map.get(exercise_input, "미입력")

    # ── 증상 및 심리 상태 ──
    print("\n[ 증상 및 심리 상태 ]")
    data['stress_level'] = input("  스트레스 수준 (1~10, 예: 7): ").strip() or "미입력"

    symptom_map = {
        "1": "입면 어려움",
        "2": "중간에 자주 깸",
        "3": "이른 기상",
        "4": "주간 졸음",
        "5": "만성 피로",
        "6": "야간 불안/잡생각",
        "7": "기상 후 피로감",
        "8": "두통",
    }
    print("  주요 증상 (쉼표로 구분, 예: 1,4,5)")
    print("  1=입면어려움  2=중간에깸  3=이른기상  4=주간졸음")
    print("  5=만성피로    6=야간불안  7=기상후피로  8=두통")
    symptom_input  = input("  선택: ").strip()
    selected_nums  = [s.strip() for s in symptom_input.split(",") if s.strip()]
    data['symptoms'] = ", ".join(symptom_map[n] for n in selected_nums if n in symptom_map) or "미입력"

    data['extra'] = input("  기타 특이사항 (복용 약물, 기저질환 등): ").strip() or "없음"

    return data


# ── 2. 프롬프트 생성 함수 ────────────────────────────────────────
def build_prompt(data):
    return f"""다음 환자 데이터를 바탕으로 아래 형식에 맞춰 분석해줘.

[환자 데이터]
- 연령/성별/직업: {data['age']}세 / {data['gender']} / {data['job']}
- 취침 시간: {data['bedtime']} / 기상 시간: {data['waketime']}
- 입면 소요 시간: {data['sleep_onset']}분
- 야간 각성 횟수: {data['wakeup_count']}회
- 수면의 질 (주관): {data['sleep_quality']}
- 카페인 섭취: 하루 {data['caffeine_cups']}잔, 마지막 섭취 {data['caffeine_time']}
- 알코올 섭취: {data['alcohol']}
- 취침 전 스마트폰 사용: {data['phone_minutes']}분
- 운동 빈도: {data['exercise']}
- 스트레스 수준: {data['stress_level']}/10
- 주요 증상: {data['symptoms']}
- 기타: {data['extra']}

[분석 형식]
1. 의학적 소견
   - 수면 유형 진단 (불면증, 수면위상지연 등)
   - 주요 원인 분석
   - 위험 요소 평가

2. 생화학 기반 행동 처방
   - 멜라토닌 분비 최적화 방법
   - 코르티솔 조절 전략
   - 세로토닌/도파민 균형 유지 방법
   - 구체적 행동 지침 (시간대별)

3. 우선순위 개선 항목 3가지 (가장 시급한 것부터)
"""


# ── 3. AI 분석 함수 ──────────────────────────────────────────────
def analyze_with_gemini(prompt):
    model = genai.GenerativeModel('models/gemini-3.5-flash') # Changed 'models/gemini-1.5-flash' to 'models/gemini-3.5-flash'
    print("\n" + "=" * 55)
    print("   AI 분석 결과")
    print("=" * 55 + "\n")
    response = model.generate_content(prompt)
    print(response.text)


# ── 4. 메인 실행 ────────────────────────────────────────────────
if __name__ == "__main__":
    patient_data = input_patient_data()

    print("\n" + "-" * 55)
    print("입력된 데이터를 확인하고 분석을 시작합니다...")
    print("-" * 55)

    prompt = build_prompt(patient_data)
    analyze_with_gemini(prompt)

"""웹"""

!pip install streamlit -q
!npm install -g localtunnel -q

# Commented out IPython magic to ensure Python compatibility.
# %%writefile app.py
# import streamlit as st
# import pandas as pd
# import numpy as np
# import json
# import os
# from sklearn.model_selection import train_test_split
# from sklearn.preprocessing import StandardScaler
# from sklearn.ensemble import RandomForestClassifier
# from sklearn.neighbors import NearestNeighbors
# 
# # 페이지 제목 및 설정
# st.set_page_config(page_title="수면 건강 종합 진단", layout="centered")
# st.title("🛌 수면 건강 종합 진단 서비스")
# st.markdown("---")
# 
# @st.cache_resource
# def load_and_train():
#     if not os.path.exists('Sleep_health_and_lifestyle_dataset.csv'):
#         return None, None, None, None
# 
#     df = pd.read_csv('Sleep_health_and_lifestyle_dataset.csv')
#     df['Sleep Disorder'] = df['Sleep Disorder'].fillna('Normal')
#     df[['Systolic_BP', 'Diastolic_BP']] = df['Blood Pressure'].str.split('/', expand=True).astype(int)
#     df['Gender'] = df['Gender'].map({'Female': 0, 'Male': 1})
#     bmi_map = {'Normal': 0, 'Normal Weight': 0, 'Overweight': 1, 'Obese': 2}
#     df['BMI Category'] = df['BMI Category'].map(bmi_map)
# 
#     def estimate_heart_rate(sbp, dbp):
#         return int(np.clip(0.25 * sbp + 0.35 * dbp + 25, 45, 120))
#     if 'Heart Rate' not in df.columns or df['Heart Rate'].isnull().any():
#         df['Heart Rate'] = df.apply(lambda r: estimate_heart_rate(r['Systolic_BP'], r['Diastolic_BP']), axis=1)
# 
#     FEATURE_COLS = ['Gender', 'Age', 'Quality of Sleep', 'Stress Level', 'BMI Category', 'Heart Rate', 'Daily Steps', 'Systolic_BP', 'Diastolic_BP']
#     X = df[FEATURE_COLS]
#     y = df['Sleep Disorder']
# 
#     scaler = StandardScaler()
#     X_sc = scaler.fit_transform(X)
#     model = RandomForestClassifier(n_estimators=200, max_depth=6, class_weight='balanced', random_state=42)
#     model.fit(X_sc, y)
# 
#     knn_scaler = StandardScaler()
#     knn_scaled = knn_scaler.fit_transform(df[FEATURE_COLS])
#     knn_model = NearestNeighbors(n_neighbors=8, metric='euclidean')
#     knn_model.fit(knn_scaled)
# 
#     return df, scaler, model, knn_model
# 
# df, scaler, model, knn_model = load_and_train()
# 
# if df is None:
#     st.error("⚠️ 'Sleep_health_and_lifestyle_dataset.csv' 파일을 찾을 수 없습니다. Kaggle 다운로드를 먼저 실행해 주세요.")
#     st.stop()
# 
# def assign_persona(disorder, stress, quality):
#     if disorder == 'Normal':
#         if quality >= 7 and stress <= 4:
#             return {"type": "🌙 Deep Rest (안정적 수면형)", "risk": "낮음", "desc": "부교감신경이 활성화된 심리적 안정 상태입니다. PSQI 기준 매우 우수한 수면 상태입니다."}
#         else:
#             return {"type": "🏃 Recovery Booster (활동 회복형)", "risk": "낮음", "desc": "글림프 시스템을 통한 뇌 노폐물 제거가 진행 중인 상태입니다. 수면 질 7점 이상이 목표입니다."}
#     elif disorder == 'Insomnia':
#         if stress >= 6:
#             return {"type": "⚡ Stress Sleeper (스트레스 과부하형)", "risk": "높음", "desc": "코르티솔 과다 분비로 HPA축이 과활성화되어 멜라토닌 분비가 억제된 상태입니다."}
#         else:
#             return {"type": "🔄 Irregular Rhythm (수면 리듬 불균형형)", "risk": "중간", "desc": "일주기리듬(Circadian Rhythm) 붕괴 상태로, 취침·기상 시각 고정이 최우선입니다."}
#     else:
#         return {"type": "🫁 Apnea Risk (호흡 불안형)", "risk": "높음", "desc": "수면 중 기도 협착으로 반복적 호흡 정지가 발생, 산소포화도 저하가 심혈관계에 부담을 줍니다."}
# 
# def get_knn_targets(user_raw):
#     FEATURE_COLS = ['Gender', 'Age', 'Quality of Sleep', 'Stress Level', 'BMI Category', 'Heart Rate', 'Daily Steps', 'Systolic_BP', 'Diastolic_BP']
#     knn_scaler = StandardScaler()
#     knn_scaled = knn_scaler.fit_transform(df[FEATURE_COLS])
#     user_df = pd.DataFrame([user_raw])
#     user_sc = knn_scaler.transform(user_df)
#     _, indices = knn_model.kneighbors(user_sc)
#     similar = df.iloc[indices[0]]
#     good = similar[similar['Quality of Sleep'] >= 7]
#     ref = good if len(good) >= 2 else similar
#     return {
#         "target_daily_steps": int(ref['Daily Steps'].mean()),
#         "target_stress_level": round(ref['Stress Level'].mean(), 1),
#         "target_quality": round(ref['Quality of Sleep'].mean(), 1),
#     }
# 
# def gemini_medical_analysis_mock(persona, user_raw, knn):
#     return {
#         "medical_summary": f"입력하신 데이터 분석 결과, 현재 {persona['type']} 경향이 뚜렷하게 관찰됩니다. 자율신경계 균형과 호르몬 분비 주기를 정상화하기 위한 라이프스타일 교정이 요구됩니다.",
#         "mechanism": "과도한 신체적/심리적 스트레스 유인 혹은 수면 환경 불일치로 인해 생체 시계인 일주기 리듬이 일시적으로 교란된 상태입니다.",
#         "recommended_sleep_hours": "7~8시간",
#         "missions": [
#             "취침 1시간 전 스마트폰 및 블루라이트 완전히 차단하기",
#             "실내 온도를 약간 서늘한 18~20°C로 세팅하여 심부체온 낮추기",
#             "눕기 전 4-7-8 호흡법을 5분간 실시하여 교감신경 가라앉히기"
#         ],
#         "warning_signs": "주 3회 이상의 수면 곤란이 2주 이상 지속될 경우, 수면전문의 전문 상담을 권장합니다."
#     }
# 
# st.header("📋 1단계: 수면 및 라이프스타일 정보 입력")
# col1, col2 = st.columns(2)
# with col1:
#     gender_input = st.selectbox("성별을 선택하세요", ["여성", "남성"])
#     gender = 1 if gender_input == "남성" else 0
# with col2:
#     age = st.slider("나이 (세)", 10, 100, 30)
# 
# col3, col4, col5 = st.columns(3)
# with col3:
#     bmi_input = st.selectbox("BMI 체형 분류", ["정상 체중", "과체중", "비만"])
#     bmi_cat = {"정상 체중": 0, "과체중": 1, "비만": 2}[bmi_input]
# with col4:
#     sbp = st.number_input("수축기 혈압 (최고)", value=120)
# with col5:
#     dbp = st.number_input("이완기 혈압 (최저)", value=80)
# 
# steps = st.number_input("하루 평균 걸음 수 (보)", value=7000, step=500)
# 
# st.subheader("📊 주관적 상태 평가")
# sleep_score = st.slider("최근 나의 수면의 질 점수 (1~10)", 1, 10, 5)
# stress_score = st.slider("최근 나의 스트레스 지수 (1~10)", 1, 10, 5)
# 
# hr = int(np.clip(0.25 * sbp + 0.35 * dbp + 25, 45, 120))
# st.info(f"💓 혈압 기반 자동 추정 심박수: **{hr} bpm**")
# st.markdown("---")
# 
# if st.button("🚀 종합 수면 건강 분석하기", type="primary"):
#     user_raw = {
#         'Gender': gender, 'Age': age, 'Quality of Sleep': sleep_score,
#         'Stress Level': stress_score, 'BMI Category': bmi_cat,
#         'Heart Rate': hr, 'Daily Steps': steps, 'Systolic_BP': sbp, 'Diastolic_BP': dbp
#     }
#     user_df = pd.DataFrame([user_raw])
#     user_sc = scaler.transform(user_df)
#     disorder = model.predict(user_sc)[0]
#     proba = model.predict_proba(user_sc)[0]
#     proba_dict = {c: f"{round(p*100, 1)}%" for c, p in zip(model.classes_, proba)}
# 
#     persona = assign_persona(disorder, stress_score, sleep_score)
#     knn = get_knn_targets(user_raw)
#     gd = gemini_medical_analysis_mock(persona, user_raw, knn)
# 
#     st.header("🎯 분석 결과 레포트")
#     st.subheader(f"👤 배정된 수면 페르소나: **{persona['type']}**")
#     st.warning(f"**위험도 레벨:** {persona['risk']} | **상태 설명:** {persona['desc']}")
# 
#     st.subheader("🩺 AI 수면 장애 위험도 예측 (Random Forest)")
#     st.write(f"가장 유력한 진단: **{disorder}**")
#     st.table(pd.DataFrame([proba_dict], index=["예측 확률"]))
# 
#     st.subheader("🎯 데이터 분석 기반 추천 목표 (KNN 유사 그룹 비교)")
#     col_a, col_b, col_col = st.columns(3)
#     col_a.metric(label="목표 걸음 수", value=f"{knn['target_daily_steps']:,} 보", delta=int(knn['target_daily_steps'] - steps))
#     col_b.metric(label="목표 스트레스 지수", value=f"{knn['target_stress_level']}/10", delta=round(knn['target_stress_level'] - stress_score, 1), delta_color="inverse")
#     col_col.metric(label="목표 수면의 질", value=f"{knn['target_quality']}/10", delta=round(knn['target_quality'] - sleep_score, 1))
# 
#     st.markdown("---")
#     st.subheader("🔬 의학 전문가 종합 코멘트 (By Gemini)")
#     st.write(gd['medical_summary'])
#     st.caption(f"**생리적 메커니즘:** {gd['mechanism']}")
#     st.info(f"⏰ **당신에게 권장하는 일일 수면 시간:** {gd['recommended_sleep_hours']}")
# 
#     st.subheader("✅ 오늘 밤 실천할 행동 미션")
#     for idx, mission in enumerate(gd['missions'], 1):
#         st.checkbox(f"{idx}. {mission}", key=f"m_{idx}")
# 
#     st.error(f"⚠️ **전문의 상담 기준:** {gd['warning_signs']}")

import subprocess
subprocess.Popen(["streamlit", "run", "app.py", "--server.port", "8501"])

!npx localtunnel --port 8501

# Commented out IPython magic to ensure Python compatibility.

# 1. 구글 드라이브 연결
from google.colab import drive
drive.mount('/content/drive')

# 2. 깃허브 프로젝트 폴더로 이동
# %cd /content/26-1-team5

# 1. 변경된 모든 파일(README 포함)을 스테이징 영역에 추가
!git add .

# 2. 커밋 메시지 작성 (원하는 메시지로 변경 가능)
!git commit -m "docs: README.md 추가 및 코드 업데이트"

# 3. 깃허브 원격 저장소로 푸시
!git push origin main

"""# 깃허브 지운 코드(노트북이 알고 이쓴 내용)
!git clone https://github.com/imminjoouuoouu/26-1-team5.git
%cd 26-1-team5
!git add .
!git commit -m "add colab code"
!git push
원격 저장소 주소를 토큰이 포함된 주소로 갱신합니다.
!git remote set-url origin https://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@github.com/imminjoouuoouu/26-1-team5.git
!git add README.md
!git commit -m "docs: README.md 추가"
!git push origin main
"""